### ISSUE TITLE
A (valid) xtend expression systematically freezes eclipse

### ISSUE THREAD

**Issue by alexandrebouchard** [eclipse/xtext-xtend#1005]
The following file causes eclipse's xtend compiler to freeze (consuming 700% CPUs, never terminating building, and getting unresponsive / Mac OS's ball of death spinning forever in eclipse):

```
package mypack

class MyClass {
  
  def static double test() {
    val mu = 0.0
    val beta = 0.0
    val double L = 0.0
    val int a = 0
    val int b = 0
    val double lambda = 0.0
    val double sa = 0.0
    val double sb = 0.0
    return mu * (sa + lambda * (sb - sa) - 0.5 * mu * (a + lambda * (b - a)))
  }
  
}
```

The culprit seems to be the long-ish return statement. If I make is just a bit shorter (eg removing the "mu *" part, then it eventually compiles fine. Maybe a corner of the parsing logic hides an exponential-complexity algorithm?

Eclipse DSL 4.11.0
Xtend 2.16

**Comment by cdietrich** [comment]
sample code also needs insane amounts of memory

**Comment by szarnekow** [comment]
To make it bearable, extract (even more) local vars, e.g for the `(a + lambda * (b-a)))`

**Comment by ArneDeutsch** [comment]
Started to investigate this a bit. So far I can see a quadratic algorithm that scales with number of variables * depth of expression. In `XbaseTypeComputer` the method `getBestCandidate` is gone through once per variable in scope and is called by `computeTypes` and in the next expresion depth calls `getBestCandidate` again. Guess this results in quadratic behaviour but have not yet an idea how to solve it.

**Comment by szarnekow** [comment]
Generally speaking the algorithm depends on the number of overloads in the scope. The binary ops are heavily overloaded for all kinds of types.
Assuming an expression `a + (b - c)`, the RHS of the addition will be asked for its type at least the number of overloads of `+` times. Let's say it's 60. Now `c` is asked for it's type the number of times `-` is overloaded, let's say `30`. So `c` is asked 60*30=1800 times for its type. 

This is a long standing problem / situation and there are plans how this can be solved (e.g. guaranteeing that each expression is visited only once). But that is certainly not something that can be fixed on the go.

**Comment by alexandrebouchard** [comment]
Thanks for the pointers guys. 

Could memoization be used as a first attempt solution in getBestCandidate? I.e. caching the (input list, result) of getBestCandidate (using e.g. guava's excellent LoadingCache to make sure memory does not blow up as a result). 

It all depends on if we can get quick to compute identity or hashcode on the input List of ILinkingCandidate's. When it is called several times, is it with the exact same List object, or with different List objects? In the former case caching would seem a no-brainer, in the latter case the need for linear time hashcode computation would probably defy the cache speed up.

**Comment by szarnekow** [comment]
I'm afraid memoization won't cut it since the state involved is rather complex and could even depend on specific language semantics (the type inference is not only implemented for Xtend but for all Xbase expressions).

**Comment by ArneDeutsch** [comment]
Above change seems to work well. On master the code from the ticket freezes eclipse. With the change it is lightning fast :).

**Comment by alexandrebouchard** [comment]
Amazing, thank you, I am eager to try it, long mathematical expressions are common in our xtext-based probabilistic programming language library (https://www.stat.ubc.ca/~bouchard/blang/)

**Comment by szarnekow** [comment]
The fixes will be available in the next nightly build.
