### ISSUE TITLE
XtendInstallDebugInfoMojoIT.simpleSMAP is flaky

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1013]
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:IT-SNAPSHOT:compile (default) on project simple: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:IT-SNAPSHOT:compile failed: Plugin org.eclipse.xtend:xtend-maven-plugin:IT-SNAPSHOT or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.xtend:xtend-maven-plugin:jar:IT-SNAPSHOT -> org.eclipse.emf:org.eclipse.emf.codegen:jar:2.19.0 -> org.eclipse.jdt:org.eclipse.jdt.launching:jar:[3.5.0,4.0.0): No versions available for org.eclipse.jdt:org.eclipse.jdt.launching:jar:[3.5.0,4.0.0) within specified range -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:IT-SNAPSHOT:compile (default) on project simple: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:IT-SNAPSHOT:compile failed: Plugin org.eclipse.xtend:xtend-maven-plugin:IT-SNAPSHOT or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.xtend:xtend-maven-plugin:jar:IT-SNAPSHOT ->

**Comment by cdietrich** [comment]
wonder if we miss that thing in the bom and or why it is needed and not downloaded

**Comment by cdietrich** [comment]
questions
- why do we need emf.codegen at all
- if we need it do we need the jd.launching transitive dependency

**Comment by szarnekow** [comment]
> * why do we need emf.codegen at all

IIRC it is only used to figure the types from the `java.lang` package.
Which is trivial to implement based on ClassLoader.getResource("java/lang/<<simplename>>.class")

**Comment by cdietrich** [comment]
Fixed in 2.22
