### ISSUE TITLE
Outdated web site xtend-lang.org

### ISSUE THREAD

**Issue by vladdu** [eclipse/xtext-xtend#1028]
I'm not sure if this is the right place to mention this, but I'd consider it a bug.

The web page doesn't seem to have been updated since around 2015. All videos and blogs are from 2015 or older (and some of the links are dead). Supporting Java 8 is a big thing, despite it being launched in 2014.

I was talking to a friend about xtend, and he pointed out that as a potential new user, this is a big warning signal.

**Comment by cdietrich** [comment]
see also https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2019/12/03/version-2-20-0

**Comment by vladdu** [comment]
Ah, okay, I had missed that. But it's not a surprise. Unfortunate, but it happens...

Something like that notice could be published on the xtend page, to make it clear that there is very little development happening.

**Comment by cdietrich** [comment]
i have no idea how to formulate that

**Comment by miklossy** [comment]
Thanks @vladdu for making us aware of the outdated [Xtend website](https://www.eclipse.org/xtend/) !

I will investigate what we can do to make it more up-to-date.

**Comment by miklossy** [comment]
@vladdu I updated the Xtend community page. It would be awesome if you could take a look at it. I am closing it now, kindly open a new issue if you see further places for improvements.

Fixed in 2.22
