### ISSUE TITLE
Xtend generates unused imports for classes in the same package

### ISSUE THREAD

**Issue by ivaniesta14** [eclipse/xtext-xtend#1029]
_This issue was marked as resolved in #1014, however no commits related to this part of that issue were linked._

Xtend generates imports (in the compiled .java files) for all classes used in a .xtend file, even for those in the same package. Eclipse (starting in 4.15 (2020-03)) raises a warning for the latter.

As a simple way to test this, just referencing a class from another in the same .xtend file also triggers the warning. Take, for example, an `@Active` annotation with its processor on the same file.

**Comment by cdietrich** [comment]
this is fixed in 2.22 which is not out yet and the commit is here:
https://github.com/eclipse/xtext-extras/pull/573

**Comment by ivaniesta14** [comment]
I was referring to the fact that those warnings also show up in _classes_ too¹, not just annotations:

![image](https://user-images.githubusercontent.com/20027601/77099522-5cfa0200-6a14-11ea-92cc-68ee83b905fa.png)

As it can be seen, both `IvExtraMath` and `ZeroToOneReal` are in the same package, yet the warning shows up.

---

1: I have "Generate `@SuppressWarnings("all")`" toggled off.

**Comment by cdietrich** [comment]
we have discussed that and we currently dont see an option
to fix this with "dont generate an import"
thus we generalized it for suppresswarnings

if you want to provide a fix you are welcome.
i cannot tell what would need to be done and which problems might occurr

**Comment by nineninesevenfour** [comment]
The pull requests are a  base for discussion. I am not sure, if I catched all tests that have to be adapted, though.

**Comment by szarnekow** [comment]
Thank you for picking this up @nineninesevenfour 

The fix looks promising.

While testing this, I found that we do already have a broken incremental build behaviour.

Consider this contrived example:

```
package pack;
class MyXtendClass {
  val java.lang.String s = "";
}
```

When we create a type next to this class
```
package pack;
class String {}
```
we observe that the generated code is not updated and gets a compile error. Manually triggering a rebuild of `MyXtendClass` doesn't help either. 

I'll make this a new ticket.

**Comment by nineninesevenfour** [comment]
Hello @szarnekow , thank you very much for testing this, I will have a look on it later.

**Comment by cdietrich** [comment]
thxy for the fix @nineninesevenfour

**Comment by cdietrich** [comment]
this leads now to test fails in xtend maven plugin

https://github.com/cdietrich/xtend-nameclash-reproducer
shows the problem also in eclipse

https://ci.eclipse.org/xtext/job/xtext-xtend/job/master/1100/

**Comment by cdietrich** [comment]
![Bildschirmfoto 2020-12-10 um 10 03 45](https://user-images.githubusercontent.com/238736/101750272-1337d700-3acf-11eb-8125-245892407642.png)

**Comment by cdietrich** [comment]
its unfortune we dont have the same tests in the  normal gradle tests too

**Comment by nineninesevenfour** [comment]
I am very sorry to have caused this. I have a look on it.

**Comment by cdietrich** [comment]
i am sorry that our downstream tests are so complicated and contruíbutor unfriendly

**Comment by nineninesevenfour** [comment]
I don't have a solution yet, but I am on it.
