### ISSUE TITLE
Inheritance of static methods

### ISSUE THREAD

**Issue by DanySK** [eclipse/xtext-xtend#1035]
Hi,
I'm discussing an issue with @cdietrich. Consider:
```xtend
public interface IX {
	public static int getTheNumber() {
		return 42;
	}
}
public interface IY {
	public static int getTheNumber() {
		return 24;
	}
}
class Both implements IX, IY {  }
```
Currently, the compiler complains that `Both` inherits `getTheNumber` from different sources. My question is:
* does Xtend allow to call `Both.getTheNumber()`? Does it allow to call `getTheNumber()` from inside a method of `Both`?

If it does not, then I believe the error should not get thrown, as the static call gets disambiguated. However, if it does, as far as I understand it might a bug according to @cdietrich . See also xtext/xtext-gradle-plugin#170

**Comment by cdietrich** [comment]
@szarnekow move to 2.23?

**Comment by szarnekow** [comment]
Merge for 2.23
