### ISSUE TITLE
Xtend IDE: Bracket matching is messed up

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#1036]
Reproducbile with 2.22.0-SNAPSHOT. Could be a regression of the Xtend-Java migration, hence this works perfectly with 2.21.

![screenshot](https://user-images.githubusercontent.com/20393472/78975834-488dbe80-7b15-11ea-9e7e-b478900d2a2f.png)

@cdietrich Can you reproduce this on your computer?

**Comment by cdietrich** [comment]
yes

**Comment by cdietrich** [comment]
p.s: which target platform do you use to test?

**Comment by miklossy** [comment]
I installed `Xtext/Xtend 2.22.0.v20200409-0121` into `Eclipse 2020-03`.

**Comment by cdietrich** [comment]
Fixed

**Comment by miklossy** [comment]
I have just tested it with the latest Xtext version and can confirm that the bug has been fixed.
@cdietrich : Thank you very much for the fix!
