### ISSUE TITLE
Investigate test fails with latest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1038]
Investigate test fails with latest

https://ci.eclipse.org/xtext/job/xtext-xtend/job/master/700/

have no idea what breaks pluginProjectFactory.
nothing in the logs

**Comment by cdietrich** [comment]
```
09:14:58  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.81 s <<< FAILURE! - in org.eclipse.xtend.ide.tests.refactoring.XImportSectionUpdateOnRenameTest
09:14:58  org.eclipse.xtend.ide.tests.refactoring.XImportSectionUpdateOnRenameTest  Time elapsed: 0.81 s  <<< ERROR!
09:14:58  org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
09:14:58 
```

**Comment by cdietrich** [comment]
and of course locally everything is green (on mac and linux and linux from maven) :(

**Comment by cdietrich** [comment]
no even inside the docker container.... :(
lets see if rerun helps

**Comment by cdietrich** [comment]
after restart tests are green again. lets observe this

**Comment by miklossy** [comment]
The `XImportSectionUpdateOnRenameTest` test cases are also green locally on Windows.

**Comment by cdietrich** [comment]
will close for now as problem did not happen again
