### ISSUE TITLE
field visibility issue with "With Operator" syntax

### ISSUE THREAD

**Issue by jeanmichelpedrono** [eclipse/xtext-xtend#1059]
Hello,

I'm evaluating Xtend 2.21 and while playing with the example https://github.com/kthoms/xtend-codegen-examples, I'm facing the following issue. Looks like something is broken with "With Operator" syntax.

Eclipse reports me on line 11 (See screenshort below): "The field name is not visible"

And here is how "name" field is accessed:
![image](https://user-images.githubusercontent.com/3350475/83123518-4edff600-a0d5-11ea-9446-52a10d89ef0f.png)

But this field is a member of class "Library" declared like this:

![image](https://user-images.githubusercontent.com/3350475/83124197-2c9aa800-a0d6-11ea-8b04-4d52175c2d04.png)

Thanks,
Regards.

**Comment by cdietrich** [comment]
can you please provide a complete minimal example?

**Comment by jeanmichelpedrono** [comment]
The example I'm using is the one from Karsten Thoms :  https://github.com/kthoms/xtend-codegen-examples.

The accessor code is in
https://github.com/kthoms/xtend-codegen-examples/blob/master/xtend.codegen.example1/src/test/java/xtend/codegen/example1/Model2JSON.xtend

And the accessed class is declared in https://github.com/kthoms/xtend-codegen-examples/blob/master/xtend.codegen.example1/src/main/java/xtend/codegen/example1/model/Library.xtend

**Comment by cdietrich** [comment]
yes but that ones uses a 1000 year old xtext + gradle version

=> i assume the project is not configured correct in eclipse

**Comment by cdietrich** [comment]
=> maybe you should try newer versions

{code}
plugins {
  id "org.xtext.xtend" version "2.0.8"
}

repositories.jcenter()

dependencies {
  compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.21.0'
  compile group: 'com.google.code.gson', name: 'gson', version: '2.7'
  compile group: 'com.beust', name: 'jcommander', version: '1.58'
}

{code}

**Comment by jeanmichelpedrono** [comment]
For some reason, it seems that the @Accessors annotation keyword was not properly recognized by Eclipse. The syntax coloring now highlight @Accessors keyword, and this also resolved my issue...
However, I did not change anything in my project...

![image](https://user-images.githubusercontent.com/3350475/83126912-c9ab1000-a0d9-11ea-8217-58879f01ae02.png)
