### ISSUE TITLE
Rich string comments always consume the line break

### ISSUE THREAD

**Issue by ivaniesta14** [eclipse/xtext-xtend#1108]
Consider the following code:
![image](https://user-images.githubusercontent.com/20027601/92303952-0c527300-ef7a-11ea-949b-fbcdcc2800c4.png)
`line 3`'s indentation is not intended to be part of the string, yet it is marked as part of it (and is in the generated Java code)

Note that the indentation is considered part of the string, even if there is non-blank text before the comment:
![image](https://user-images.githubusercontent.com/20027601/92304320-3d807280-ef7d-11ea-9e80-965a8cfa82d9.png)

It should also be noted that the formatter indents fully commented out lines (see image below) to match surrounding indentation, which can cause this issue to appear: Formatting
![image](https://user-images.githubusercontent.com/20027601/92303915-bbdb1580-ef79-11ea-9070-90290e667eb2.png)
produces the first image above.

---
Images source text:
```xtend
	public static val TEST = '''
		line 1
		«««		commented out line 2
		line 3
	'''
```
```xtend
	public static val TEST = '''
		line 1
		pre-comment «««		commented out line 2
		line 3
	'''
```
```xtend
	public static val TEST = '''
		line 1
«««		commented out line 2
		line 3
	'''
```

**Comment by szarnekow** [comment]
This is on purpose and basically the only way to split template with otherwise very long lines.
The line comment "comments" all subsequent chars in that line which includes the new-line character at the end.
If you want to comment only a subsection of a line, you can use `«/* some comment */»`

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
