### ISSUE TITLE
Ability to generate output strings without any indentation while using template expressions

### ISSUE THREAD

**Issue by Wisdom199** [eclipse/xtext-xtend#1116]
Hi,

I have a use-case where I'm using xtend templates expressions to generate a long xml message string. 
```
def longXMLString(Content content)'''
<xml>
    <tag001 att=«content.t001»>
        <tag101>
              <tag111>
                     «content.t111»
              </tag111>
        <tag101>
    </tag001>
      ...
    <tag501 att=«content.5001»>
        <tag501>
              <tag511>
                     «content.t511»
              </tag511>
        <tag501>
    </tag501>
  </xml>
'''
```
This allows me to view the XML message with indentation and I can see all the tags, their hierarchy and set values in a much more readable way. However, when I get the output of the message it keeps all its indentation with it and the size of the message string gets considerably huge as compare to the one without any indentation. Doing String.replace() for spaces does not seems to be an efficient solution as it will create another huge string at runtime (a costly operation).

Hence, I'm looking for a built-in way to generate the output string without any indentation. I have not found any solution yet.

But since, the above template expression uses StringConcatenation class (by @szarnekow ) to build the output string. One way to solve would be have a method getUnIndentatedContent in org.eclipse.xtend2.lib.StringConcatenation which ignores all the indentation and returns the actual string content.

Is it possible to add such method? or if there is any other way to solve this issue? Please advise.

Many thanks,

**Comment by szarnekow** [comment]
Do I understand your question correctly? You want to write this template
```
def longXMLString(Content content)'''
<xml>
    <aTag ..>    
</xml>
'''
```
and want to get this output?
```
<xml>
<aTag ..>    
</xml>
```

**Comment by cdietrich** [comment]
this should work ootb if you do this

```
	static def StringConcatenationClient demo(String name) '''
		<a>
			<b>«name»</b>
		</a>
	'''

	static class MyTarget implements TargetStringConcatenation {

		@Delegate
		StringConcatenation delegate

		new(StringConcatenation delegate) {
			this.delegate = delegate
		}

		def Object fix(Object o) {
			if (o instanceof String)
				return o.replaceAll("\t", "")
			o
		}

		override append(Object object, String indentation) {
			delegate.append(fix(object), "")
		}

		override append(Object object) {
			delegate.append(fix(object))
		}

		override appendImmediate(Object object, String indentation) {
			delegate.appendImmediate(fix(object), "")
		}

		override newLine() {
			delegate.newLine
		}

		override newLineIfNotEmpty() {
			delegate.newLineIfNotEmpty
		}

	}

	def static void main(String[] args) {
		val StringConcatenation delegate = ''''''
		val t = new MyTarget(delegate)
		val StringConcatenationClient d = demo("Hello World")
		StringConcatenationClient.appendTo(d, t)
		println(delegate)
	}
```

**Comment by Wisdom199** [comment]
> Do I understand your question correctly? You want to write this template
> 
> ```
> def longXMLString(Content content)'''
> <xml>
>     <aTag ..>    
> </xml>
> '''
> ```
> 
> and want to get this output?
> 
> ```
> <xml>
> <aTag ..>    
> </xml>
> ```


@szarnekow Yes, I would like to get the output like;
<xml><aTag ..></xml>

**Comment by Wisdom199** [comment]
> this should work ootb if you do this
> 
> ```
> 	static def StringConcatenationClient demo(String name) '''
> 		<a>
> 			<b>«name»</b>
> 		</a>
> 	'''
> 
> 	static class MyTarget implements TargetStringConcatenation {
> 
> 		@Delegate
> 		StringConcatenation delegate
> 
> 		new(StringConcatenation delegate) {
> 			this.delegate = delegate
> 		}
> 
> 		def Object fix(Object o) {
> 			if (o instanceof String)
> 				return o.replaceAll("\t", "")
> 			o
> 		}
> 
> 		override append(Object object, String indentation) {
> 			delegate.append(fix(object), "")
> 		}
> 
> 		override append(Object object) {
> 			delegate.append(fix(object))
> 		}
> 
> 		override appendImmediate(Object object, String indentation) {
> 			delegate.appendImmediate(fix(object), "")
> 		}
> 
> 		override newLine() {
> 			delegate.newLine
> 		}
> 
> 		override newLineIfNotEmpty() {
> 			delegate.newLineIfNotEmpty
> 		}
> 
> 	}
> 
> 	def static void main(String[] args) {
> 		val StringConcatenation delegate = ''''''
> 		val t = new MyTarget(delegate)
> 		val StringConcatenationClient d = demo("Hello World")
> 		StringConcatenationClient.appendTo(d, t)
> 		println(delegate)
> 	}
> ```

@cdietrich thank you so much, I will try this today.

**Comment by Wisdom199** [comment]
Hi,

The solution suggested by @cdietrich works really well. 

I just changed it a little bit though;

```
                def Object fix(Object o) {
			if (o instanceof String && StringUtils.isBlank((String)o))
				return ""
			o
		}

                override newLine() {
		       // skip
		}

		override newLineIfNotEmpty() {
			// skip
		}

```

Thank you so much for the quick response!

**Comment by kthoms** [comment]
Closing, as the question looks answered. Feel free to reopen when you don't think so.
