### ISSUE TITLE
Compile error for null in rich string expressions

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#112]
The following code will produce a syntax error in the compiled code:
```
class Foo {
	def m() '''
		«null»
	'''
}
```
The resulting code is
```
public class Foo {
  public CharSequence m() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(null);
    _builder.newLineIfNotEmpty();
    return _builder;
  }
}
```
and the error 
```The method append(Object) is ambiguous for the type StringConcatenation```

**Comment by kthoms** [comment]
The previous compiled code was
```
_builder_1.append(null, "")
```

The situation was found in [FXDiagram: Debug.xtend#dumpBounds](https://github.com/JanKoehnlein/FXDiagram/blob/c04ce9cc94885af0d880119c8a7194bf80fa215b/de.fxdiagram.core/src/de/fxdiagram/core/debug/Debug.xtend)

**Comment by kthoms** [comment]
Seems to be caused by #69 , 696c292fdb5c55759af79505dc8920c5d098e49e

**Comment by holgerschill** [comment]
Is this fixed @kthoms ?

**Comment by kthoms** [comment]
Yes, it is fixed
