### ISSUE TITLE
private final serialVersionUID is flagged as unused

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1147]
private final serialVersionUID is flagged as unused

```
import java.io.Serializable

class Sample implements Serializable {
	static final long serialVersionUID = 1L
}
```

in jdt/java its not

```
import java.io.Serializable;

public class Sample implements Serializable {
  private static final long serialVersionUID = 1L;
}
```

**Comment by cdietrich** [comment]
```
	@Override
	protected boolean isLocallyUsed(EObject target, EObject containerToFindUsage) {
		boolean locallyUsed = super.isLocallyUsed(target, containerToFindUsage);
		if (!locallyUsed) {
			if (target instanceof JvmField) {
				JvmField field = (JvmField) target;
				JvmDeclaredType declaringType = ((JvmField) target).getDeclaringType();
				if ("serialVersionUID".equals(field.getSimpleName())) {
					if (Long.TYPE.getSimpleName().equals(field.getType().getIdentifier())) {
						if (rawSuperTypes.collect(declaringType).stream()
								.anyMatch(t -> Serializable.class.getName().equals(t.getIdentifier()))) {
							return true;
						}
					}
				}
			}
		}
		return locallyUsed;
	}
```

@szarnekow is there a better way to do this?

**Comment by szarnekow** [comment]
Hmm maybe we could do something in `LogicalContainerAwareReentrantTypeResolver._computeTypes(Map<JvmIdentifiableElement, ResolvedTypes>, ResolvedTypes, IFeatureScopeSession, JvmField)` along with `ReadAndWriteTracking.markReadAccess(..)`.
Basically the same logic but with the option to use a somewhat richer API:
```
if ("serialVersionUID".equals(field.getSimpleName()) && childResolvedTypes.getActualType(field).isType(Long.TYPE) && .. ) {
			if (childResolvedTypes.getActualType(field.getDeclaringType()).isSubtypeOf(Serializable.class)) {
				readWriteTracking.markReadAccess(field);
			} else {
				childResolvedTypes.addDiagnostic(.. bla bla type is not serializable but has a serialVersionUID );
			}
		}
```
(before merge(..) at the end)

**Comment by nineninesevenfour** [comment]
Hello @szarnekow, I have to admit your solution looks tempting, but I wonder, if it isn't better to keep the logic in the XtendValidator or XbaseValidator? I don't see any validation code in the LogicalContainerAwareReentrantTypeResolver yet.

**Comment by szarnekow** [comment]
Basically all the overload / type conformance validation happens in the type resolver control flow. You may want to look at `org.eclipse.xtext.xbase.typesystem.internal.DefaultReentrantTypeResolver.resolve(CancelIndicator)` which has this line `result.addDiagnostics(root.eResource());`. To be honest, some of the type-system related validation is only present in the XtendValidator / XbaseValidator for historical reasons. It was unfortunately never refactored towards the type resolution phase where most of the necessary information is already present.

**Comment by cdietrich** [comment]
thx for the fix @nineninesevenfour
