### ISSUE TITLE
Broken code generation if types conflict with java.lang types

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-xtend#1161]
Consider this contrived example:

```
package pack;
class MyXtendClass {
  val java.lang.String s = "";
}
```

When we create a type next to this class
```
package pack;
class String {}
```
we observe that the generated code is not updated and gets a compile error. Manually triggering a rebuild of `MyXtendClass` doesn't help either. 

_Originally posted by @szarnekow in https://github.com/eclipse/xtext-xtend/issues/1029#issuecomment-741606608_

**Comment by cdietrich** [comment]
same as https://github.com/eclipse/xtext/issues/2309 ?

**Comment by szarnekow** [comment]
Yes, it's a duplicate of eclipse/xtext#2309
