### ISSUE TITLE
Import statements added for same classes from same package

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#1166]
I am observing in my Xtext dev workspace that the Java classes generated from Xtend contain import statements for classes that are in the same package as the Xtend class.

Xtend version is 2.24.0. This did not happen before, so this looks like a regression.

<img width="2190" alt="screenshot 2021-01-06 um 11 11 13" src="https://user-images.githubusercontent.com/265597/103756772-1fe91580-5010-11eb-958e-592fea96090a.png">

**Comment by cdietrich** [comment]
NO

bootstrap M1 missing cause there is no M1
