### ISSUE TITLE
Create a test case for "none" fragment case to investigate the cause

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-xtend#1189]
Create a testcase to reproduce the bogus behavior where an EObject do not have an eResource.

Related code to test: `BatchLinkableResourceStorageWritable#getFragment(EObject)`

Happens probably in Active annotation `@Data` or `@FinalFieldConstructor`  context

See eclipse/xtext-extras#695

**Comment by cdietrich** [comment]
fixed in 2.26
