### ISSUE TITLE
Find clean solution for Memory Leak in ShowWhitespaceCharactersActionContributor

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#12]
Find a clean solution for the workaround in ShowWhitespaceCharactersActionContributor

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=402742

**Comment by stadlerb** [comment]
The actual leak occurs in Eclipse UI itself, not Xtext UI, so the clean solution must be implemented there. The problem has been known since Eclipse 4.1 and a draft patch has been contributed, but deferred to Eclipse 4.7: https://bugs.eclipse.org/bugs/show_bug.cgi?id=354538

**Comment by cdietrich** [comment]
i guess we should stick with the current workaround and wait for the eclipse platform bug to be fixed

**Comment by stadlerb** [comment]
Ok, but please vote for the Eclipse issue if you have votes left - it's been pretty long-standing and so far, I am the only one who voted.

**Comment by cdietrich** [comment]
Root Cause is fixed with https://git.eclipse.org/r/#/c/67267/ in Oxygen. Since Xtext will run on older Versions as well i'll close this issue and leave the workaround in place
