### ISSUE TITLE
BuildAffectionTest fails on latest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1210]
BuildAffectionTest fails on nightly, have no idea why.
https://ci.eclipse.org/xtext/job/xtext-xtend/job/master/1385/testReport/junit/org.eclipse.xtend.ide.tests.builder/BuildAffectionTest/testUnaffected_noReferences/

**Comment by cdietrich** [comment]
@szarnekow as you are watching platform/jdt
did you see any changes that could cause this.

**Comment by cdietrich** [comment]
ahh this is a side effect of @Bananeweizen s change

**Comment by Bananeweizen** [comment]
Sorry for that. I had even looked around if there is something depending on that string, but I didn't  check Xtend.
