### ISSUE TITLE
Single dispatch method generates invalid Java code

### ISSUE THREAD

**Issue by wurzlphi** [eclipse/xtext-xtend#1248]
The following Xtend code worked fine in Xtend 2.25, but generates invalid Java code (shown below) in Xtend 
2.26.0.v20211001-0541.
This seems to be an issue with dispatch methods using multiple arguments.
```
class Test {
	
	def dispatch void singleDispatchSingleArg(String arg) {
		// works
	}
	
	def dispatch void singleDispatchTwoArgs(String arg1, String arg2) {
		// doesn't work
	}
	
//	def dispatch void singleDispatchTwoArgs(Object arg1, Object arg2) {
//		// works again
//	}
	
}
```

Generated Java, note the `else`-clause after the `return` statement in `singleDispatchTwoArgs`:

```
import java.util.Arrays;

@SuppressWarnings("all")
public class Test {
  protected void _singleDispatchSingleArg(final String arg) {
  }
  
  protected void _singleDispatchTwoArgs(final String arg1, final String arg2) {
  }
  
  public void singleDispatchSingleArg(final String arg) {
    _singleDispatchSingleArg(arg);
    return;
  }
  
  public void singleDispatchTwoArgs(final String arg1, final String arg2) {
    _singleDispatchTwoArgs(arg1, arg2);
    return; else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(arg1, arg2).toString());
    }
  }
}
```

**Comment by cdietrich** [comment]
could be side effect of 
https://github.com/eclipse/xtext-xtend/commit/c0a0f49b1576c4c7b7c0c4c2de3e3fd3069c2e8e#diff-87e45c1ff4eed7e7530fc18e0967f5b5da4f413d591f31a39fe536851d147ce7
cc @szarnekow @ArneDeutsch

**Comment by cdietrich** [comment]
looks like this guard is not working as intended

`&& !(parameterCount == 1 && sortedDispatchOperations.size() == 1) `

**Comment by cdietrich** [comment]
what do you think about https://github.com/eclipse/xtext-xtend/compare/cd_issue1248
@ArneDeutsch @szarnekow
