### ISSUE TITLE
Active annotations interface default methods

### ISSUE THREAD

**Issue by mepeisen** [eclipse/xtext-xtend#1256]
Having a very simple active annotation to add a default method to an interface it does not work.

Sample code from processor:
`annotatedInterface.addMethod("getFoo", [ newMethod | {
	newMethod.returnType = Foo.newTypeReference
	newMethod.^default = true
	newMethod.body = '''return new Foo();'''
}])`

This will generate a method body but modifier "default" is missing. Expected result is generating a method body and including default modifier.

I am using a maven setup with java version 12 and with xtend 2.25.0 as well as xtend-maven-plugin 2.25.0.
Eclipse version is 2021-03 and installed xtext/xtend plugin version is 2.25.0. Jee plugin is version 4.19.0. M2e version is 1.17.2.

Looking at the sources it might not detect java version as greater of version 8? Within JvmModelGenerator in method "_generateModifier" it checks for java version 8. In eclipse preferences there is a hint at xtend compiler page. It says "take compatibility level from java settings. Seems it does not understand java 12. Setting this option to java 11 and recompiling works. So the main problem seems to be that xtend does not understand how to handle java 12 or greater from java settings/ maven pom settings.

**Comment by cdietrich** [comment]
xtend does not support Java 12 as runtime

**Comment by cdietrich** [comment]
ping @mepeisen

**Comment by cdietrich** [comment]
close as no further feedback from user
