### ISSUE TITLE
Fix XtendCompilerAntTaskTest

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-xtend#126]
Failing after move from xtend.core tests to xtend.ide.tests:
* org.eclipse.xtend.ide.tests.compiler.batch.XtendCompilerAntTaskTest.testSrcdirAsAttr
* org.eclipse.xtend.ide.tests.compiler.batch.XtendCompilerAntTaskTest.testSrcdirAsNestedPath

**Comment by cdietrich** [comment]
@spoenemann you did not copy https://github.com/eclipse/xtext-xtend/tree/master/org.eclipse.xtend.core.tests/testdata
