### ISSUE TITLE
[ux] Organize imports without change marks editor dirty

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#130]
To reproduce just invoke Organize Imports on an Xtend file that does not do any change.

![screenshot 50](https://cloud.githubusercontent.com/assets/265597/22013496/96a369a8-dc99-11e6-9f23-04da05fd3bc3.png)

**Comment by cdietrich** [comment]
in java it stays dirty as well

**Comment by kthoms** [comment]
It should be a noop.

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=488867 as well

**Comment by cdietrich** [comment]
@kthoms i can no longer reproduce this in eclipse oxygen/xtext 2.12.

**Comment by kthoms** [comment]
Sorry for reopening. I can reproduce this in my Oxygen/2.12 environment.

**Comment by cdietrich** [comment]
sure there is no whitespace change?

**Comment by cdietrich** [comment]
ill have a look again
