### ISSUE TITLE
name clash with lambda as anon inner class compilation

### ISSUE THREAD

**Issue by dpetroff** [eclipse/xtext-xtend#1301]
Today I upgraded from Xtend 2.21 to 2.26 and my code base broke the IDE generator targeting Java 11.

Consider the method

```
def getMyAdapter(extension EObject it) {
	eAdapters.filter(AdapterImpl).head ?: (new AdapterImpl() => [eAdapters += it])
}
```

In the most recent Eclipse package (2022-03), the IDE generator generates distinctly different code from gradle for this example. In particular, the gradle generator uses Java lambda notation, while the IDE does not. Additionally, the IDE generated code also results in broken Java because it does not disambiguate between the `EObject it` and the `Adapter it` inside the lambda. Notice that the `EObject it` is declared as an extension, so the `eAdapters` call inside the lambda should apply to it. This works as expected when building with gradle and previous versions of the IDE, but the current IDE generator does not appear to disambiguate between the two `it`s, which results in broken Java code.

[myGradleProject.zip](https://github.com/eclipse/xtext-xtend/files/8233878/myGradleProject.zip) is a minimal gradle project reproducing the issue. Note that building with gradle is successful, including the test phase, and as long as the IDE generator doesn't rebuild the source after refreshing the gradle project in the IDE, there are no errors in the editor. Once the IDE has rebuilt the source, it is necessary to rebuild again with gradle and refresh the gradle project in the IDE again to get rid of the error.

**Comment by cdietrich** [comment]
no no clue what change could have caused this. unfortunately not too many people seem to test milestones :(

**Comment by cdietrich** [comment]
workaround:
have a org.eclipse.xtend.core.Xtend.prefs
with
```
useJavaCompilerCompliance=true
```

having 

```
targetJavaVersion=Java11
useJavaCompilerCompliance=false
```
causes the problem

am not sure if this is a problem in the gradle plugin
downgrading the plugin to 2.1.0 helps
@szarnekow @oehme any idea?
<img width="1157" alt="Bildschirmfoto 2022-03-11 um 18 33 11" src="https://user-images.githubusercontent.com/238736/157918674-e91791a1-3165-44e3-bc9f-78c0fda2c2ed.png">

**Comment by cdietrich** [comment]
config.getJavaSourceVersion().isAtLeast(JAVA8) is false
this is cause there is no settings file
and the default is somewhere else.

the pref has
targetJavaVersion=Java11
and not
targetJavaVersion=JAVA11

**Comment by dpetroff** [comment]
I noticed the workaround you suggested shortly before you posted it. However, it seems the Refresh Gradle Project recreates the preference file and sets the option to `false` every time, which is not great as I frequently have to do it and have many subprojects that get reset. This is starting to look more like a gradle plugin issue.

**Comment by cdietrich** [comment]
yes this is a bug in xtext-gradle-plugin

**Comment by cdietrich** [comment]
can you build this branch locally and test it
https://github.com/xtext/xtext-gradle-plugin/compare/cd_xtendIssue1301
`./gradlew pTML -PreleaseVersion=3.0.2-SNAPSHOT -x test`
then add maven local and use classpath plugin application

(you may need to delete existing xtend and xtext.java prefs)

**Comment by dpetroff** [comment]
I still think there is also a Xtend generator component to it. Setting aside the failure to identify the correct Java compliance level, the correctly-generated code has a lambda with `it_1` as the variable, while the incorrect code generates a procedure with `it` as the variable, which shadows the original `it` from the containing scope.

I'm also seeing a lot of weirdness with the `useJavaCompilerCompliance` setting being stuck to `false` in my projects, while at the same time being stuck to `true` in the gradle project I attached before, regardless of what the actual preference file says.

**Comment by cdietrich** [comment]
if you want an opt out for useJavaCompilerCompliance or settings generation,
maybe you can disable 
xtextEclipseSettings task somehow.
if not file an enhancement request for the plugin

**Comment by cdietrich** [comment]
i have no clue why we dont get the settings configured in e.g. xtext-core codebase

**Comment by cdietrich** [comment]
@dpetroff any update?

**Comment by cdietrich** [comment]
@rubenporras the anonymous class has name class issue would be something for you to look at if you want to dive into xbase

**Comment by rubenporras** [comment]
Hi @cdietrich ,

why do you think it would be something for me? 

do you think a PR I merged in Xtext 2.25 could have broke something or do you think I could be interested in the topic?

Regards

**Comment by rubenporras** [comment]
Hi @cdietrich ,

thanks for asking. No, currently I am not interested. I am focused in migrating from xtext eclipse to xtext lsp, and that is enough of a challenge. In addition, we use Maven for our projects.

**Comment by cdietrich** [comment]
gradle plugin is fixed.
open: anonymous class compilation

**Comment by cdietrich** [comment]
![Bildschirmfoto vom 2022-04-01 07-01-53](https://user-images.githubusercontent.com/238736/161198120-a3c83479-69e7-499a-b9a5-59b88a5deb03.png)
![Bildschirmfoto vom 2022-04-01 07-02-23](https://user-images.githubusercontent.com/238736/161198123-75ec4260-a55d-4257-8e82-a5708c27ce6c.png)

```
	@Test
	def void testXtendIssue1301() {
		'''
		import org.eclipse.emf.ecore.EObject
		import org.eclipse.emf.common.notify.impl.AdapterImpl
		class Sample {
			def getMyAdapter(extension EObject it) {
				eAdapters.filter(AdapterImpl).head ?: (new AdapterImpl() => [eAdapters += it])
			}
		}
		'''.assertCompilesTo('''
		import com.google.common.collect.Iterables;
		import org.eclipse.emf.common.notify.Adapter;
		import org.eclipse.emf.common.notify.impl.AdapterImpl;
		import org.eclipse.emf.common.util.EList;
		import org.eclipse.emf.ecore.EObject;
		import org.eclipse.xtext.xbase.lib.Extension;
		import org.eclipse.xtext.xbase.lib.IterableExtensions;
		import org.eclipse.xtext.xbase.lib.ObjectExtensions;
		import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
		
		@SuppressWarnings("all")
		public class Sample {
		  public AdapterImpl getMyAdapter(@Extension final EObject it) {
		    AdapterImpl _elvis = null;
		    AdapterImpl _head = IterableExtensions.<AdapterImpl>head(Iterables.<AdapterImpl>filter(it.eAdapters(), AdapterImpl.class));
		    if (_head != null) {
		      _elvis = _head;
		    } else {
		      AdapterImpl _adapterImpl = new AdapterImpl();
		      final Procedure1<AdapterImpl> _function = new Procedure1<AdapterImpl>() {
		        public void apply(final AdapterImpl it) {
		          EList<Adapter> _eAdapters = it_1.eAdapters();
		          _eAdapters.add(it_1);
		        }
		      };
		      AdapterImpl _doubleArrow = ObjectExtensions.<AdapterImpl>operator_doubleArrow(_adapterImpl, _function);
		      _elvis = _doubleArrow;
		    }
		    return _elvis;
		  }
		}
		''')
	}
```

@szarnekow 
the
```
scopeClosed = scopeClosed || !scope.pseudoScope;
			// If we left the current scope (incl. pseudo scopes) and the variable is not synthetic or unique,
			// we can stop collecting names. Overriding names from outside is ok in that case. 
			if (scopeClosed && !(synthetic || withUniqueName))
			```
leads to an early exit here.

**Comment by cdietrich** [comment]
should 
org.eclipse.xtext.xbase.compiler.XbaseCompiler.appendClosureParameter(JvmFormalParameter, LightweightTypeReference, ITreeAppendable)
call declareUniqueVariableName?

**Comment by cdietrich** [comment]
alternatively: should the extension on out scope variable visible here?

**Comment by cdietrich** [comment]
side effects_ https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_xtend_issue_1301/2/

**Comment by cdietrich** [comment]
fixed
