### ISSUE TITLE
Investigate hang/timeout in JavaRefactoringIntegrationTest with latest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1310]
03:21:49  Running org.eclipse.xtend.ide.tests.refactoring.JavaRefactoringIntegrationTest
09:04:28  Cancelling nested steps due to timeout
09:04:28  Sending interrupt signal to process

https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_testTycho30/55/console
https://ci.eclipse.org/xtext/job/xtext-xtend/job/master/2146/console

**Comment by cdietrich** [comment]
somehow the logging for timeouts does not log any stacktraces :(

**Comment by cdietrich** [comment]
![Bildschirmfoto vom 2022-03-28 20-41-51](https://user-images.githubusercontent.com/238736/160465162-d08f2ce7-3826-418b-b0a5-9d792cc908d9.png)
@szarnekow do you have any platform changes in mind that could cause this?

**Comment by cdietrich** [comment]
org.eclipse.xtend.ide.tests.refactoring.JavaRefactoringIntegrationTest.testRenameJavaMethod()

**Comment by cdietrich** [comment]
possible candidates
https://git.eclipse.org/r/c/jdt/eclipse.jdt.ui/+/70037

**Comment by cdietrich** [comment]
```
RefactoringStatusEntry.<init>(int, String, RefactoringStatusContext) line: 87	
RefactoringStatus.addFatalError(String, RefactoringStatusContext) line: 551	
RenameVirtualMethodProcessor(RenameMethodProcessor).checkNewElementName(String) line: 231	
RenameVirtualMethodProcessor(RenameMethodProcessor).doCheckFinalConditions(IProgressMonitor, CheckConditionsContext) line: 346	
RenameVirtualMethodProcessor.doCheckFinalConditions(IProgressMonitor, CheckConditionsContext) line: 128	
RenameVirtualMethodProcessor(JavaRenameProcessor).checkFinalConditions(IProgressMonitor, CheckConditionsContext) line: 51	
RenameRefactoring(ProcessorBasedRefactoring).checkFinalConditions(IProgressMonitor) line: 226	
RenameRefactoring(Refactoring).checkAllConditions(IProgressMonitor) line: 165	
RefactoringExecutionHelper$Operation.run(IProgressMonitor) line: 84	
BatchOperation.executeOperation() line: 41	
BatchOperation(JavaModelOperation).run(IProgressMonitor) line: 740	
Workspace.run(ICoreRunnable, ISchedulingRule, int, IProgressMonitor) line: 2315	
Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) line: 2340	
JavaCore.run(IWorkspaceRunnable, ISchedulingRule, IProgressMonitor) line: 5929	
WorkbenchRunnableAdapter.run(IProgressMonitor) line: 108	
ModalContext$ModalContextThread.run() line: 122	

```

**Comment by cdietrich** [comment]
test does

```
createFile("JavaClass.java", "public class JavaClass { public void foo() {} }");
IMethod foo = findJavaType("JavaClass").getMethod("foo", new String[0]);
renameJavaElement(foo, "baz");
```
with
```
	protected void renameJavaElement(IMethod javaElement, String newName) throws CoreException, InterruptedException,
			InvocationTargetException {
		syncUtil.totalSync(false);
		RenameSupport renameSupport = RenameSupport.create(javaElement, newName, RenameSupport.UPDATE_REFERENCES);
		renameSupport.perform(workbench.getActiveWorkbenchWindow().getShell(), workbench.getActiveWorkbenchWindow());
		syncUtil.totalSync(false);
		assertTrue(compositeRefactoringProcessorAccess.isDisposed());
	}
```

**Comment by cdietrich** [comment]
RenameMethodProcessor.initialize
seems to set the method name to old method name

**Comment by cdietrich** [comment]
the initialize call seems to override the newelementname again
![Bildschirmfoto vom 2022-03-28 21-12-31](https://user-images.githubusercontent.com/238736/160469938-0fdbd395-a20c-4904-bce6-4ecc2c936dce.png)
![Bildschirmfoto vom 2022-03-28 21-13-05](https://user-images.githubusercontent.com/238736/160469950-c5b98fc7-6a3e-4c07-b281-6ac192d84fa9.png)

**Comment by cdietrich** [comment]
cc @jjohnstn

**Comment by jjohnstn** [comment]
Looking into it.

**Comment by jjohnstn** [comment]
I believe I have found the issue.  I was able to reproduce the problem.  I have created a follow-on patch:

https://git.eclipse.org/r/c/jdt/eclipse.jdt.ui/+/192294

Please recheck when the patch has been merged into a new build

**Comment by cdietrich** [comment]
with upstream fix, test is green again thx @jjohnstn
