### ISSUE TITLE
XtendClasspathContainer attempts to download JavaDocs but probably fails

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-xtend#1387]
The URLs produced by `org.eclipse.xtend.ide.buildpath.XtendClasspathContainer.calculateJavadocURL()` lead to a redirect or 404. We should probably drop the idea of having the JavaDoc download URL configured on the CP container or change it to the correct location (not sure whether we even publish JavaDoc anymore).

It makes URLs like http://download.eclipse.org/modeling/tmf/xtext/javadoc/2.9 or http://download.eclipse.org/modeling/tmf/xtext/javadoc/2.29

**Comment by cdietrich** [comment]
i am not aware of us publishing javadocs. we dont even produce an aggregated version. repo split ftw
