### ISSUE TITLE
Install proper debug information into our shipped Java Byte Code

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-xtend#141]
According to 
[org.eclipse.xtend.tycho.parent/pom.xml](https://github.com/eclipse/xtext-xtend/blob/master/releng/org.eclipse.xtend.tycho.parent/pom.xml) the SMAP debug information is never installed into the Java Byte Code. 

To make this happen, however, Xtend is getting a bootstrap dependency onto itself. Not sure if we want that.

If we want to keep the `xtend-gen` folder in git, we can try to invoke the `maven-xtend-plugin` with the `xtend-install-debug-info` goal only. However, this does introduce the bootstrap dependency non-the-less.

I think this issue is not as critical, since most people use Xtend as a tool and not as a library/framework.

see also: https://github.com/eclipse/xtext-eclipse/issues/172

**Comment by spoenemann** [comment]
Copied fix from xtext-eclipse.
