### ISSUE TITLE
Change to Flexers when regenerating with Java 11

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#1420]
`./gradlew -PuseJenkinsSnapshots=true generateXtend` will lead to changes in Flexers.
@szarnekow  can you please check if the changes are ok?

**Comment by szarnekow** [comment]
The change is correct and stems from the updated Unicode version in Java 11 compared to Java 8. Running the build with Java 17 will again change the run-length encoded packed string and its length.

**Comment by cdietrich** [comment]
done
