### ISSUE TITLE
Confusing usage of it

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-xtend#145]
```
class Edge {
    def Object getSource { null }
}

class Foo {
    def foo() {
        val source = null
        new ArrayList<Edge>.map[source]
    }
}
```

The above code caused me some confusion. I assumed that the `source` in the `map` would translate to `it.getSource()` but actually it refers to the variable `source` defined above that line. Is this a mistake in my reasoning or is it an actual bug?

**Comment by spoenemann** [comment]
Features that are accessible through standard Java visibility rules (e.g. local variables) have higher precedence than features that are accessed with the implicit receiver `it`. This should be clarified in the documentation:
https://github.com/eclipse/xtext/blob/website-published/xtend-website/documentation/203_xtend_expressions.md

**Comment by svenefftinge** [comment]
In Xtend any kind of sugar has lower precedence than the fully qualified syntax.
By that rule it is clear that`source` would first bind to a local variable `source` before being interpreted in a sugared way.

But we should also document the precedencies between the different sugared variants, like  `getSource` vs. `this.source` vs. `it.source` vs. `it.getSource` etc...

**Comment by tivervac** [comment]
Documenting this rule would indeed make questions like these unnecessary in the future. Thanks for the fast response.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
