### ISSUE TITLE
Xtend return type check bug, causes injection failure

### ISSUE THREAD

**Issue by SmerkyG** [eclipse/xtext-xtend#146]
The following code is accepted by Xtend and compiles without warning or error, despite not properly returning the Boolean return type. Not sure what code it generates exactly, but it's bad code. If you call the method from another class via @Inject, the injection itself is unavailable causing a NullException error at runtime. Maybe the bad generated code can't be loaded at all?

```
class BadCode {
	def Boolean badCode(Object c) {
		switch(c) {
			Integer: {
			}
		}
	}
}
```

And approximate calling code:

```
class Test {
	@Inject extension BadCode;
	def run() {
		badCode(null);
	}
}
```

Various other ways exist to accidentally fool the return type check - including hiding conditional returns inside a for loop for some switch cases.

**Comment by cdietrich** [comment]
which xtext version do you use?

**Comment by SmerkyG** [comment]
I just upgraded to xtext 2.11 a few hours ago

On Wed, Feb 1, 2017 at 3:27 PM, Christian Dietrich <notifications@github.com

**Comment by SmerkyG** [comment]
The following also causes the same kinds of problems, and doesn't have the nullable issue:

```
	def boolean badCode(XStruct c) {
		switch(c) {
			XFunction: {
				for(x:c.implements) {
					return true
				}
			}
		}
	}
```

In this code XFunction is a subclass of XStruct

**Comment by cdietrich** [comment]
so is this about general null analysis in xtend?

**Comment by SmerkyG** [comment]
I'm not sure exactly - it seems like some problem with the return type checker to me. I don't think the code I just posted could be confused about null, since it's boolean not Boolean.

**Comment by cdietrich** [comment]
well maybe we could introduce a warning for the implicit return of null/false.
but i cannot say how much effort that will make

**Comment by SmerkyG** [comment]
Well the generated code is

```
  public boolean badCode(final XStruct c) {
    Object _switchResult = null;
    boolean _matched = false;
    if (c instanceof XFunction) {
      _matched=true;
      EList<QualifiedParameterizedTypeName> _implements = c.getImplements();
      for (final QualifiedParameterizedTypeName x : _implements) {
        return true;
      }
    }
    return ((boolean)_switchResult);
  }
```

As you can see, it can return null which is converted to boolean, causing a runtime exception

The problem is that it shouldn't be able to return null if the return type is required to be boolean

**Comment by cdietrich** [comment]
yes thats definitvely bad

**Comment by cdietrich** [comment]
bugzilla gives

https://bugs.eclipse.org/bugs/show_bug.cgi?id=478486
https://bugs.eclipse.org/bugs/show_bug.cgi?id=444969

**Comment by SmerkyG** [comment]
Ah yes, looks like it's a known bug! (At least in some of its cases)

**Comment by SmerkyG** [comment]
By the way Christian, I found another somewhat simpler related problem in the Xtend switch codegen:

```
val XSymbol symbol = xexp.symbol
switch(symbol) {
 case XStruct: // do stuff
}
```

generates the following Java code:

```
if (Objects.equal(symbol, XStruct.class)) {
```

In this code XSymbol is not convertible to XStruct, so the test could have been known at compile time to never succeed. 

Since it's easy in Xtend to accidentally write ```case MyClass:``` instead of just ```MyClass:``` it would be nice if the checker could detect when you are doing an impossible comparison and generate at least a warning if not an error!

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
