### ISSUE TITLE
Inappropriate Copyright comment handling

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#163]
Given is the following Xtend file:
![copyright_comment_handling1](https://cloud.githubusercontent.com/assets/20393472/23330592/e0f94f8c-fb51-11e6-824a-801d5f45a66b.png)

Hitting Enter on the current cursor position leads to the following result:
![copyright_comment_handling2](https://cloud.githubusercontent.com/assets/20393472/23330605/172e3022-fb52-11e6-93ea-d838652a8a61.png)

Interestingly, the problem does not occur when the class A is empty (it does not contain any further comments).

**Comment by cdietrich** [comment]
the MultiLineTerminals Strategy is configured with
`"/*"," * ", " */"`

=> it cannot handle **/ properly

this affects all xtext languages not xtend only.

**Comment by cdietrich** [comment]
fixed in 2.12
