### ISSUE TITLE
Message "The value of the field xxx is not used" after removing the field from class

### ISSUE THREAD

**Issue by patm0le** [eclipse/xtext-xtend#167]
We are using an annotation to create an @Embeddable-Class for multiple @Id-fields.
The following input

```
@CompositeIdClass @Entity @Table(name="A")
class TestEntityA {
	@Id @Column(name="id_1") String id1
	@Id @Column(name="id_2") String id2
}
```

generates entity

```
@CompositeIdClass @Entity @Table(name = "A")
public class TestEntityA {
  @EmbeddedId private TestEntityAId id;
  
  public TestEntityAId getId() { return id; }
  public void setId(final TestEntityAId id) { this.id = id; }
}
```

and @Embeddable class

```
@Embeddable
public class TestEntityAId {
  @Column(name = "id_1") private String id1;
  @Column(name = "id_2") private String id2;
  
  public String getId1() { return id1; }
  public void setId1(final String id1) { this.id1 = id1; }
  public String getId2() { return id2; }
  public void setId2(final String id2) { this.id2 = id2; }
}
```

The fields id1 and id2 are removed from the entity but we still get warnings for the fields not being used.
We couldn't find a way so far to remove the fields without getting the warnings.
The example is attached.
[xtend-test-field-not-used.zip](https://github.com/eclipse/xtext-xtend/files/814317/xtend-test-field-not-used.zip)

**Comment by cdietrich** [comment]
hmm good question. what about not doing the remove but do a idField.markAsRead as xtend does for the @Accessors annotation

**Comment by cdietrich** [comment]
i assume we should use 

```
	@Inject
	private ReadAndWriteTracking readAndWriteTracking;
	
	@Check
	public void checkLocalUsageOfDeclaredFields(XtendField field){
		if (readAndWriteTracking.isRead(field)) {
			return;
		}
```

inside XtendValidator as well

**Comment by patm0le** [comment]
Thanks, markAsRead() solved my problem, I should have noticed this method before

**Comment by cdietrich** [comment]
yes the naming made it quite unclear that it was the field you inferred that was marked as unread and not the original one
