### ISSUE TITLE
Compiler Bug: The value for an annotation attribute must be a constant exprestion

### ISSUE THREAD

**Issue by rjv9645** [eclipse/xtext-xtend#168]
xtend v: 2.11.0

The following is a valid sprint annotation, but is not valid in an xtend class:

Pure java: 
`  @RequestMapping(value = "update", consumes = {MediaType.APPLICATION_JSON_VALUE}, 
                                   method =RequestMethod.POST)
   public String updateUser(@RequestBody final User user) {
    return user.toString();
}`

Xtend (doesn't compile):
`	@RequestMapping(value="update",
					consumes={MediaType.APPLICATION_JSON_VALUE}, 
					method=RequestMethod.POST)
	def updateUser(@RequestBody User user){
		user.toString()
	}`

Brackets in annotation values seem to be disallowed.

**Comment by cdietrich** [comment]
the array/list literal in xtend is `#[MediaType.APPLICATION_JSON_VALUE]`

**Comment by rjv9645** [comment]
New to xtend. My apologies. Thank you for the quick answer!
