### ISSUE TITLE
Problem with ActiveAnnotation and used annotation javax.validation.constraints.Size

### ISSUE THREAD

**Issue by afischer211** [eclipse/xtext-xtend#179]
We have implemented some own active annotations with Xtend2.11 (but the problem also occurs with Xtend2.10).
If the Xtend-code uses the annotation **javax.validation.constraints.Size** with two attributes (min=0, max=10), the Xtend-system crashes with an exception:
java.lang.RuntimeException: Cannot root twice
at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver$1.add(DefaultBatchTypeResolver.java:73)
at org.eclipse.xtext.xbase.typesystem.internal.DefaultBatchTypeResolver$1.add(DefaultBatchTypeResolver.java:1)
at org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareReentrantTypeResolver$1.add(LogicalContainerAwareReentrantTypeResolver.java:325)

If I only use one attribute (**only** min= or max=), all is working.
I think, the problem lies in the class **org.eclipse.xtext.xbase.typesystem.internal.LogicalContainerAwareReentrantTypeResolver** in method **`recordAnnotationExpressions(List<JvmAnnotationReference> annotations)`**:

```
	protected void recordAnnotationExpressions(List<JvmAnnotationReference> annotations) {
		for(JvmAnnotationReference annotation: annotations) {
			EObject sourceElement = getSourceElement(annotation);
			if (sourceElement != annotation) {
				rootedInstances.add(sourceElement);
			} else {
				for(JvmAnnotationValue value: annotation.getExplicitValues()) {
					if (value instanceof JvmCustomAnnotationValue) {
						JvmCustomAnnotationValue custom = (JvmCustomAnnotationValue) value;
						for(Object object: custom.getValues()) {
							if (object instanceof XExpression) {
								rootedInstances.add(sourceElement);
							}
						}
					} else if (value instanceof JvmAnnotationAnnotationValue) {
						recordAnnotationExpressions(((JvmAnnotationAnnotationValue) value).getValues());
					}
				}
			}
		}
	}

`````

For every attribute of the annotation the method goes through the loop and wants to add the **same** annotation ("sourceElement") to the rootedInstances. This fails for the second call.
How can I solve this problem, if I want to use an annotation with multiple parameters/attributes?

Kindly regards,
Alexander

**Comment by cdietrich** [comment]
Can you elaborate how this is related to active annotations?

**Comment by afischer211** [comment]
I have an active annotation (generation of a model-class from a simple DTO-definition as Xtend-file) and inside the DTO-definition I have some fields with the validation-annotation like:
`
import javax.validation.constraints.Size

@DTO
class MyDTO {
 
   @Size (min=0, max=100)
    private String name
   
   private boolean flag
}
`
My generation with active annotation works, if I have only one value (min or max) defined, with both values the generation throws the mentioned exception.

I wrote an unit-test, where I call the compile-Method directly with this code.
My own annotation-code (Processor, Transformer) is not detectable in the exception-stacktrace, so currently I dont see any possibility to catch this exception or to handle with it.

**Comment by cdietrich** [comment]
As I said I can't reproduce this this it would help to know step by step how to reproduce this

**Comment by cdietrich** [comment]
@afischer211 is is possible you try to copy the annotation around in your processor?

**Comment by cdietrich** [comment]
if so does it look like this

```
class NAnnoProcessor extends AbstractClassProcessor {
	
	override doTransform(MutableClassDeclaration annotatedClass, extension TransformationContext context) {
		super.doTransform(annotatedClass, context)
		for (m : annotatedClass.declaredFields) {
			annotatedClass.addField(m.simpleName+"2") [it|
				for (a : m.annotations) {
					it.addAnnotation(context.newAnnotationReference(a))
				}
			]
		}
	}
	
}
```

**Comment by afischer211** [comment]
Hello,

many thanks for your hints. After first tests with partially disabled code-parts it seems to be a problem in our code. I think, we produce an invalid model with may be multiple annotations of the same type... I will look further and give you a feedback.
How can I analyse the content of the created xtext-model before the generation of the resulting code (where I get the exception, the method doTransform is already finished then)?

**Comment by cdietrich** [comment]
if you start another eclipse from eclipse you should be able to debug this.
or you do it in a unit test

**Comment by afischer211** [comment]
Hello,
my unittest looks like '''<problematic xtend-code>'''.compile [...].
Inside the compile-call I receive the exception. On debugging the doTransform-method of my AnnotationProcessor is successfully finished, the exception occurs after this (in validation??).
I will try to find the position in code, where the problematic(?) annotation is created.

Thanks for your help, I will return later.

**Comment by cdietrich** [comment]
did you have a look at a place where you call org.eclipse.xtend.lib.macro.declaration.MutableAnnotationTarget.addAnnotation(AnnotationReference)

**Comment by afischer211** [comment]
Hello,

again many thanks for your hints. The code-line `it.addAnnotation(context.newAnnotationReference(a))` was the solution (adding new annotation-reference for an annotation instead of the existing annotation itself).
My problem is now solved.
