### ISSUE TITLE
Xtend Outline View Drag and Drop Support

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#187]
In the JDT Outline View (if the sorting is switched off) it is possible to change the order of the elements via DND.  The same functionality could be useful in the Xtend Outline View as well.

This issue is related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=383076

**Comment by cdietrich** [comment]
contributions are welcome

**Comment by ArneDeutsch** [comment]
I've investigated this a bit. At first it looks not to hard, but it really gets nasty if you go to the details. If you move a method you probably want to move a comment just before the method as well. Even if it is seperated by some whitespace. But not the whitespace before the comment. But you don't want to leave behind many blank lines. But want the moved emthod to be seperated from surrounding methods quite a bit. Getting this abstracted such that other languages can reuse a good part of the code makes it even more hard. Defnitly a task that will require many days to make it right.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
