### ISSUE TITLE
[formatter] Formatting a long line messes up the indentation for the rest of the document content

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-xtend#194]
When I format this:

```
class Foo {

	static val SOME_MULTI_LINE_THINGY = new StringBuilder('a').append('b').append('c').append('d').append('e').append('f').append('g').append('h').append('i').append('j').append('k').append('l').append('m').toString;

	var bar = new Object

}
```

I get this: (Please note the additional new line too.)

```
class Foo {

	static val SOME_MULTI_LINE_THINGY = new StringBuilder('a').append('b').append('c').append('d').append('e').
		append('f').append('g').append('h').append('i').append('j').append('k').append('l').append('m').toString;

		var bar = new Object

	}
	
```

Although I would expect something like this instead:

```
class Foo {

	static val SOME_MULTI_LINE_THINGY = new StringBuilder('a').append('b').append('c').append('d').append('e').
		append('f').append('g').append('h').append('i').append('j').append('k').append('l').append('m').toString;

	var bar = new Object

}
```

I am using 2.11.0.

**Comment by cdietrich** [comment]
problem is caused by the semikolon. issue similar to https://github.com/eclipse/xtext-xtend/issues/142 possibly duplicate

**Comment by kittaakos** [comment]
I can confirm; removing the semicolon fixes the formatting issue here. Thanks for the quick workaround!

**Comment by franzbecker** [comment]
I'd have a closer look at it tomorrow, just debugged it a bit and the problem seems that within `IndentOnceAutowrapFormatter` the `IHiddenRegion last` is set to the region before the semicolon. If `last` to the hidden region after the semicolon it seems to work.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-core/issues/301 as well

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479995

**Comment by cdietrich** [comment]
Problem is still open although eclipse/xtext-core#301  is fixed. needs to be investigated
