### ISSUE TITLE
Cannot install xtext sdk into Eclipse Neon.3 

### ISSUE THREAD

**Issue by kdvolder** [eclipse/xtext-xtend#195]
I tried to install XText SDK into Eclipse Neon.3 (after I just downloaded a 'fresh' copy of Eclipse for Java Developers package).

I tried a couple of times but wasn't able to get it installed. I tried it both from the Market Place and from the "RELEASES" update site linked here: https://eclipse.org/Xtext/download.html. when using the update site I only tried to install the 'complete SDK' package.

In each case the installation process seems to take seemingly forever and then eventually fails with an error. I can't give you the exact error as didn't take note of it, and it takes too long to try and repeat (+30 minutes). But it was something about certain plugins not being found on any available update site.

**Comment by cdietrich** [comment]
did you try xtend ide or xtext complete sdk? when did you try it (eclipse download servers seem to have severe hickups the recent weeks) 
It would be really helpful to have a complete error message (might still be contained in the error log view)

- install neon 3 java package
- add http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/ to update site

you can add the 2.11 update site directly as well http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0 or download the package from http://www.eclipse.org/modeling/tmf/downloads/

**Comment by kdvolder** [comment]
I tried installing the 'Complete Xtext SDK'. 

Unfortunately, on my final try I deleted my entire Eclipse install so the logs are gone.
But I might try later to install it again. 

Yeah, I also had the impression downloads were really slow. So maybe its just a download issue. 

Maybe I'll try again later and see how it goes. If I get a more precise error I'll let you know.

**Comment by cdietrich** [comment]
i just gave it a try and got

```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtend.ide_2.11.0.v20170130-1213.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtend.standalone.source_2.11.0.v20170130-1213.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.common.types.edit.source_2.11.0.v20170130-0818.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.common.types.shared.jdt38_2.11.0.v20170130-0818.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.common.types.shared.jdt38.source_2.11.0.v20170130-0818.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/features/org.eclipse.xtext.examples_2.11.0.v20170201-0242.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.junit4_2.11.0.v20170130-0818.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.junit4.source_2.11.0.v20170130-0818.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.source_2.11.0.v20170130-0808.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.util_2.11.0.v20170130-0808.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.xbase.testing.source_2.11.0.v20170131-1210.jar
HttpComponents connection error response code 503.
HTTP Server 'Service Unavailable': http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.11.0/plugins/org.eclipse.xtext.xtext.generator.source_2.11.0.v20170130-0808.jar
HttpComponents connection error response code 503.
```

**Comment by cdietrich** [comment]
i have created https://bugs.eclipse.org/bugs/show_bug.cgi?id=514556

**Comment by kdvolder** [comment]
Seems like whatever the problem was, its fixed now. I just installed it without a problem,
