### ISSUE TITLE
Intellij nightly url gives 404

### ISSUE THREAD

**Issue by igor-krawczuk** [eclipse/xtext-xtend#210]
Don't know if this is the correct place to report this, but the nightly URL on http://www.eclipse.org/Xtext/download.html points to the URL

https://hudson.eclipse.org/xtext/job/xtext-intellij/lastSuccessfulBuild/artifact/git-repo/intellij/build/ideaRepository/updatePlugins.xml

which right now gives error 404

**Comment by cdietrich** [comment]
well the state of the IDEA support is currently between life and death and there is nobody stepping up to revive it. (see http://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2017/02/01/version-2-11-0 / https://github.com/eclipse/xtext-idea/issues)

the current jenkins job is at http://services.typefox.io/open-source/jenkins/job/xtext-idea/job/master
