### ISSUE TITLE
Annotation of packages is not possible

### ISSUE THREAD

**Issue by Sandared** [eclipse/xtext-xtend#211]
```
import org.osgi.annotation.versioning.Version

@Version(value = "1.0.0")
package osgi.tests

class SomeClass{}
```

When I'm using autocomplete, then Eclipse tries to insert the import statement above the package statement, which leads to the following error messages:

* import statement: the import "org.osgi.annotation.versioning.Version" is never used / the declared package "null" does not match the expected package "osgi.tests" 
* package: no viable alternative at input "osgi"

When I'm moving the statement below the package statement the following error markers occur:

* @Version: Version cannto be resolved to an annotatin type / the declared package "null" does not match the expected package "osgi.tests"
* package: no viable alternative at input "osgi"
* import: no viable alternative at input "."

Kind regards,
Thomas Driessen

**Comment by cdietrich** [comment]
we currently dont have an option to declare a package-info.java in xtend.
adding the annotation to a package in an xtend file would require
to restricting to have only a total of one xtend files in a package with an annotation

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
