### ISSUE TITLE
Outdated repository in eclipse build

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-xtend#213]
Running `mvn -f tycho-pom.xml clean install` for Eclipse support as suggested in the README results in 

```[ERROR] Failed to resolve target definition /home/titouanvervack/git/xtext-xtend/releng/org.eclipse.xtend.target/org.eclipse.xtend.target.target: Failed to load p2 metadata repository from location http://download.eclipse.org/releases/luna/201502271000/: No repository found at http://download.eclipse.org/releases/luna/201502271000.```

**Comment by cdietrich** [comment]
it might be that the eclipse servers had some hickups the last 1-3 hours

**Comment by kthoms** [comment]
Repository URL can be accessed, tried with p2 director.

Anyway, for better performance and reliability consider to mirror the target platform features e.g. with b3 Aggregator. This makes you independent from Eclipse services.

**Comment by cdietrich** [comment]
@kthoms you = we ;)

**Comment by tivervac** [comment]
@cdietrich That might have been the issue, it seems to work fine now. Thanks for the quick response.
