### ISSUE TITLE
Default value declaration for annotation method with array type leads to compile error

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext-xtend#222]
This Xtend code 
```
annotation MyAnnotation {
	String[] strings = #[]
}
```
leads to this Java code
```
public @interface MyAnnotation {
  public String[] strings() default new String[] {};
}
```

Compiler error: `The value for annotation attribute MyAnnotation.strings must be an array initializer`

Seems to be a regression in Xtend 2.12.0.

**Comment by cdietrich** [comment]
hmmm getting

```
public @interface MyAnnotation {
  public String[] strings() default {};
}
```

**Comment by OLibutzki** [comment]
After restarting Eclipse it works as expected. That's strange.

Closing...
