### ISSUE TITLE
Hex long Literal

### ISSUE THREAD

**Issue by mabels** [eclipse/xtext-xtend#226]
Hello,

i just found this behaviour:
    BigInteger.valueOf(2147483648L).toString() = "2147483648"
    BigInteger.valueOf(0x80000000).toString() = "-2147483647"
    BigInteger.valueOf(0x80000000L).toString()  compiler extraneous input 'L' expecting ')'
    BigInteger.valueOf(0x80000000l).toString() compiler extraneous input 'l' expecting ')'

Is this intended?

There are a lot known ways around, but i'm wondering if this should be behave like this?

thx in advance

**Comment by cdietrich** [comment]
the intended format to be used is
`0x80000000#L` 

see https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#xtend-expressions-literals as well

@szarnekow what do you think?

**Comment by szarnekow** [comment]
Unfortunately I don't remember from the top of my hand why we introduced the # for hex numbers. Maybe because of #bd suffix, but I'm not really sure. We could certainly think about better error feedback for Java like literals that are not valid in Xbase / Xtend.

**Comment by mabels** [comment]
Hi,
thx for the answer, i did not found the related documentation while i'm tried to fix this problem.
And i had no clue that there could be # included. 
The hash feels odd in the mostly clean and tidy syntax of xtend and a reason why it is used is for me not understandable. 
If the reason why there is a hash gets obvious, i'm fine with this. 
In this case the error message should give a hint to the hash?
For me there is also another issue. I know that java is strange with hex literals two but i think
hex literals should be unsigned values and a literal like 0x80000000 should be warned that it is converted to a signed value. To suppress this warning i should be ok to at a #i for example.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
