### ISSUE TITLE
Reassignment of checked types is missing in template expression's 'ELSEIF'

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/xtext-xtend#230]
The reassignment of checked types doesn't work in the elseif branch for template expressions like
```
«val Object x = ... »
«IF x instanceof A1»«x.name /*works fine*/»
«ELSEIF x instanceof A2»«x.name /*broken*/»
«ENDIF»
```
The types `A1` and `A2` have the common super type `A`, and `A` defines a method `getName()`.

The [implementation](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.core/src/org/eclipse/xtend/core/typesystem/XtendTypeComputer.java#L140) looks like that has just been forgotten.

**Comment by cdietrich** [comment]
yes something like

```
ITypeComputationState elseState = reassignCheckedType(elseIf.getIf(), elseIf.getThen(), state);
elseState.withExpectation(charSequence).computeTypes(elseIf.getThen());
```

should fix the issue

**Comment by cdietrich** [comment]
Fixed in 2.13

**Comment by sailingKieler** [comment]
Hat es Dir keine Ruhe gelassen? ;-)

**Comment by cdietrich** [comment]
richtig ;
