### ISSUE TITLE
Xtend uses IShouldGenerate.Always in runtime but EclipseBasedShouldGenerate in ui

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#232]
is this intended? i think always should be bound in runtime and ui

**Comment by cdietrich** [comment]
i just saw that xtend overrides BuilderParticipant.shoudGenerate as well, which is inconsistent imho

**Comment by cdietrich** [comment]
@szarnekow do you know?

**Comment by szarnekow** [comment]
@cdietrich  I think this may be old code that wasn't refactored completely when migrating from BuilderParticipant.shouldGenerate to IShouldGenerate

**Comment by cdietrich** [comment]
fixed in 2.13
