### ISSUE TITLE
support for initialization blocks

### ISSUE THREAD

**Issue by braghome** [eclipse/xtext-xtend#236]
Xtend does not support initialization blocks

`class SomClass{
  {
    feature('some feature' [])
  }
}` 

so you see all Spectrum tests require that outer level of curly braces and Xtend does not know what to do with it!

discussed https://groups.google.com/d/msg/xtend-lang/NwecvJ3L_VY/SMKxwwCQAwAJ

**Comment by cdietrich** [comment]
see #300 as well

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
