### ISSUE TITLE
Javadoc with static inner classes

### ISSUE THREAD

**Issue by togliu** [eclipse/xtext-xtend#246]
If you use the organize imports functionality of Eclipse, the following Javadoc 

```
/**
  * @see MainClass$StaticInnerClass
  */
```

will be transformed to 

```
/**
   * @see StaticInnerClass
   */
```

Therefore the Javadoc task of Gradle fails and the build cannot complete.

Eclipse IDE Version: Oxygen Release (4.7.0) Build id: 20170620-1800
Xtend IDE: 2.12.0.v20170519
Gradle: 4.0.2
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OS: Arch Linux

**Comment by cdietrich** [comment]
fixed in 2.13
