### ISSUE TITLE
Typo on the website

### ISSUE THREAD

**Issue by DellCliff** [eclipse/xtext-xtend#247]
Page: http://www.eclipse.org/xtend/download.html
In the "Gradle Plugin" section:

plugins {
  id "org.xtend.xtend" version "1.0.18"         <---- will not be found by gradle
}

should be

plugins {
  id "org.xtext.xtend" version "1.0.19"     <---- will be found by gradle
}

**Comment by cdietrich** [comment]
It's actually not a typo. The website was not updated yet

**Comment by DellCliff** [comment]
It's not? Take a close look at the "org.xtend.xtend" and "org.xtext.xtend" part. They are not the same

**Comment by cdietrich** [comment]
hmmm @oehme did you change that one as well?

**Comment by cdietrich** [comment]
Fixed the website

**Comment by DellCliff** [comment]
My typo reference was not pointing to the version "1.0.18" vs "1.0.19".
I tried to communicate that "org.xtend.xtend" is not the same as "org.xtext.xtend".
"org.xtend.xtend" WILL NOT be found.
"org.xtext.xtend" will be found.
I didn't try to make you update the version, but the artifact/groud id string.

**Comment by cdietrich** [comment]
it will take a few seconds until both changes become visible

**Comment by cdietrich** [comment]
should be visible now
