### ISSUE TITLE
lambda small error

### ISSUE THREAD

**Issue by danykey** [eclipse/xtext-xtend#260]
Hi,

As I understand next chunks of code are the same
`val lambda = [] // without arguments`
and
`val lambda = [|] // without arguments`

but
```
val result = [
    true
].apply // Error: Invalid number of arguments. The method apply(Param) is not applicable without arguments
```
Code without error with **|**:
```
val result = [|
    true
].apply
```

**Comment by cdietrich** [comment]
```
[].apply
``` gives the same error

=> if you have no argument these seems to be a implicit first argument of type `Object`
=> if you have an empty parameter list you get a Function0<Object>, if you have no parameter list at all you get a Function<Object,Object>

This is aligned with the docs: "You do not need to speficy the argument names. If you leave them out, a single argument is named it."

if you have an idea how to make this more clear in the docs ...

**Comment by danykey** [comment]
Ok, not for holywar:
If we not declare args, we expects apply() without args.
I think it's intuitively clear and correct.
What is hidden profit to set single argument?

**Comment by cdietrich** [comment]
Don't know cause I did not design it but changing will be a breaking change

**Comment by cdietrich** [comment]
behaviour cannot be changed without breaking backwards compatibility
