### ISSUE TITLE
Migrate Xtend to new workflow

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#270]
How to deal with the new .ide project that would be introduced? There is already org.eclipse.xtend.ide which contains Eclipse UI code. Should the generic code be generated to org.eclipse.xtend.ide.common?

**Comment by cdietrich** [comment]
isnt this already done?

**Comment by cdietrich** [comment]
```
				genericIde = {
					enabled = true
					name = "org.eclipse.xtend.ide.common"
				}
```

**Comment by kthoms** [comment]
oh sorry, it is
