### ISSUE TITLE
Nested class invisible while active annotation processing

### ISSUE THREAD

**Issue by olga-kr** [eclipse/xtext-xtend#277]
Hi!

I have the following class structure
```
@SomeActiveAnnotation
class A{
   static class NestedA{
      public static final String constant = "constant";
  }
}

@SomeActiveAnnotation
class B{
  @CustomAnnotation(A.NestedA.constant)
   String field;
}

```

Now I need to create new annotation based on @CustomAnnotation(A.NestedA.constant) value while processing active annotation. The problem is to get value of CustomAnnotation and set this value to new annotation.
AnnotationReference.getValue gives null as if class A.NestedA is invisible
AnnotationReference.getExpression gives correct expression A.NestedA.constant but method AnnotationReferenceBuildContext.set failes when I pass expression.

Is there a way to produce @NewCustomAnnotation(A.NestedA.constant) ?

**Comment by cdietrich** [comment]
maybe similar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=487559
needs to be tested if still and issue with 2.13

**Comment by cdietrich** [comment]
@olga-kr can you provide a complete example

**Comment by olga-kr** [comment]
[ann_test.zip](https://github.com/eclipse/xtext-xtend/files/1372218/ann_test.zip)

**Comment by cdietrich** [comment]
the syntax to be used is `A$NestedA.constant`

**Comment by cdietrich** [comment]
@svenefftinge @szarnekow so i consider this works as designed correct?

**Comment by svenefftinge** [comment]
It would be desirable to allow the '.' syntax, too.

**Comment by olga-kr** [comment]
Thanks a lot. It works with 2.12 also

**Comment by olga-kr** [comment]
There's one more problem here. In generated java code I get @NewCustomAnnotation("nestedConstant")
Wich isn't exactly what i need. If classes A and B are defined in different modules the change of constant value in A will not be reflected in B until B is compiled.
Is there a way to put expression in new annotation attribute?

**Comment by cdietrich** [comment]
so you actually want to generate the same reference as in the original one. not copy the value? something like tthis issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=460798

**Comment by olga-kr** [comment]
Yes, exactly

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
