### ISSUE TITLE
Enable Xtend Editor Folding between the [ and ] symbols

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#279]
The Xtend Editor offers folding capability between the { and } symbols. It would be useful to extend this folding functionality on the [ and ] symbols as well.
![xtend_editor_folding](https://user-images.githubusercontent.com/20393472/31336752-94dab920-acf8-11e7-9a7c-51502d5fda55.png)

**Comment by kthoms** [comment]
Closure brackets are often in a single line. Also for the "simple" closures (description = "") with just one line content I doubt that code folding would be useful. I agree it makes sense when the closures become larger.

Could you try to provide a PR?

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=488160 as well

**Comment by cdietrich** [comment]
@kthoms the single line problem is handled by folding automatically you can fold only ml stuff

**Comment by cdietrich** [comment]
Fixed in 2.13
