### ISSUE TITLE
Setter code fails validation if it was processed  with active annotation processor

### ISSUE THREAD

**Issue by olga-kr** [eclipse/xtext-xtend#280]
I have the class annotated with active annotation.  And I need to do some code modifications if setters for class fields were provided. But this fails with message "The method or field this is undefined"

```
@SomeActiveAnnotation
class A {

	String field

	def void setField(String field) {
		this.field = field
	}
}

-----------------

@Target(ElementType.TYPE)
@Active(AnnProcessor)
annotation SomeActiveAnnotation {
}

----------------------

class AnnProcessor extends AbstractClassProcessor {

	override doTransform(MutableClassDeclaration classDeclr, extension TransformationContext context) {

		classDeclr.declaredFields.forEach [ field |
			val setter = classDeclr.getDeclaredMethods().findFirst [
				it.simpleName.equalsIgnoreCase("set" + field.simpleName)
			]
			if (setter !== null)
				setter.body = [
					setter.body + ";"
				]

		]

	}

}


```
Here's the example with almost none code modification. But it still fails.
[setter_test.zip](https://github.com/eclipse/xtext-xtend/files/1372460/setter_test.zip)

**Comment by cdietrich** [comment]
i have doubts that this is a legit usecase. @svenefftinge @szarnekow what do you think?

if i understand correct the body has to live in a definite method.
so you have to keep the body inside the thing it is in the xtend file
or you move it to a inferred thing and then replace the body of the original thing with code written by string concatenation

so you could do something like

``` 
class AnnProcessor extends AbstractClassProcessor {

	override doTransform(MutableClassDeclaration classDeclr, extension TransformationContext context) {

		classDeclr.declaredFields.forEach [ field |
			val setter = classDeclr.getDeclaredMethods().findFirst [
				it.simpleName.equalsIgnoreCase("set" + field.simpleName)
			]
			
			if (setter !== null) {
				classDeclr.addMethod(setter.simpleName+"Internal") [
					body = setter.body
					for (p : setter.parameters) {
            			addParameter(p.simpleName, p.type)
          			}
				]
				setter.body = '''«setter.simpleName»Internal(«setter.parameters.head.simpleName»);'''
			}

		]

	}

}

```

**Comment by svenefftinge** [comment]
It is exactly as Christian said.
The issue here is that the expression doesn't live in a context anymore, so it cannot be properly scoped. Every expression needs to be assigned to some context in the JvmModel, i.e. body of constructor, method or initializer of fields. Also 'toString' on expressions doesn't produce valid java code.

**Comment by olga-kr** [comment]
I cann't find the way to remove expression from context. It fails if I just do the following in doTransform:

`classDeclr.declaredMethods.forEach[ it.remove]`

**Comment by cdietrich** [comment]
what is your actual usecase. can you be more explicit about that

**Comment by olga-kr** [comment]
Well It seems there no case when the expression has to be removed completely.
As far as I understand I just have to keep the expression somewhere in context. It may be some private unused method.
