### ISSUE TITLE
[Intelij IDEA]Autocomplete

### ISSUE THREAD

**Issue by FunnyDevs** [eclipse/xtext-xtend#289]
Hi! I 'm trying xtend with android studio but i am not able to use autocomplete on overriding fuctions inside class. When i click with mouse on the suggestion the IDE deletes the First letteras i wrote instead of generate the fuctions. Is it normal? Thanks

This is the problem

https://streamable.com/g0yg8

**Comment by cdietrich** [comment]
From your comment at the gradle plugin bug

https://github.com/eclipse/xtext-idea/issues/26

Maybe you can have at look at the preferences or however idea calls that and enter something different there (I remember something but did not find another issue)

**Comment by cdietrich** [comment]
Found https://bugs.eclipse.org/bugs/show_bug.cgi?id=490190

**Comment by FunnyDevs** [comment]
it seems to me that there is no solution...

**Comment by cdietrich** [comment]
Did you try the workaround

**Comment by FunnyDevs** [comment]
Android Studio has a different Project Structure Dialog where there is noone facet options. I tried with gradle to force che xtend-gen folder

> sourceSets {
>     main {
>         xtendOutputDir = "xtend-gen"
>     }
> }

but with no luck

**Comment by FunnyDevs** [comment]
I have tried even importing the project in IntelliJ Idea and using the workaround: no result. Will there be a chance to use xtend with IntelliJ / Android Studio?

**Comment by cdietrich** [comment]
as i have said in the gitter: if there is somebody who steps up and repairs the code yes. but the code uses many idea internals and no tests run. otherwise i would have fixed this and some other small issues long ago.

**Comment by FunnyDevs** [comment]
ok, thank you for your time
