### ISSUE TITLE
Remove duplicate line delimiter utilities

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-xtend#297]
Delete https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/util/LineDelimiters.java

and instead use 
https://github.com/eclipse/xtext-core/blob/b43934a0efdde29a492cbba7713f1b19715b3327/org.eclipse.xtext.util/src/org/eclipse/xtext/util/Strings.java#L105-L107

instead. Also, https://github.com/eclipse/xtext-core/pull/529 is merging a `toUnix()` there.

**Comment by cdietrich** [comment]
Fixed in 2.14
