### ISSUE TITLE
Future of Xbase/Xtend (Java 6/7/8/9/10)+

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#298]
I'd like to discuss if we want to make Xbase/Xtend feature-par with Java 6/7/8 and Possible new Java 18.3 features or if we want to let it as is and move away from Xtend in the Xtext Projects/API

**Comment by kthoms** [comment]
I would tend to assure compatibility with newer Java versions. We should drop Java 6 support. If this is considered a breaking change it would be another reason to consider a major increment finally.

**Comment by MarkRx** [comment]
Just throwing this in - we use xtend a lot here because of the syntactic sugar it adds to java 6. We are stuck supporting legacy java 6 applications and need to be able to compile into java 6 compatible byte code with java 6 libraries. If java 6 is dropped at least bump up a major version

**Comment by cdietrich** [comment]
we did some discussions on this here are some points we want to investiagte and pot. address in xtext 2.14 and xtext 2.15

- try with resources
- try multicatch
- ?: operator
- method refs

**Comment by szarnekow** [comment]
We did also discuss bitwise operators, binary literals and octal literals

**Comment by sigiesec** [comment]
I am not sure what "move away from Xtend" would mean. Move to what? Would there be an automated migration?

**Comment by cdietrich** [comment]
Move away would mean back to Java.

 But as it looks we will keep xtend for a while and will even add some new features (most of them in the 215 release in fall )

**Comment by cdietrich** [comment]
clear milestone

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
