### ISSUE TITLE
Reorganize Xtend tests

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-xtend#3]
The Gradle tests in org.eclipse.xtend.core.tests are currently disabled because they need to be executed as plug-in tests. We should either
 * split the test project so the plug-in tests are run by the Tycho build and the standalone tests are run by the Gradle build, or
 * remove the test project from the Gradle build and build it completely in Tycho.

**Comment by cdietrich** [comment]
i activated the tests in tycho. there are some "red ones" as well that need to be fixed.

**Comment by spoenemann** [comment]
The test project is still needed in the Gradle build because the Xtend IDEA tests depend on it. I disabled the tests so the project is only compiled. A possible optimization could be that the Tycho build picks up the built artifacts from the local repository in `build/maven-repository/` instead of building xtend.core, xtend.core.tests, and xtend.ide.common a second time.

**Comment by spoenemann** [comment]
I think the current solution is ok. Compiling the test project twice is probably not the reason for the long build time (~50 min.)
