### ISSUE TITLE
Xtend Problem at instance initialization blocks

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#300]
Currently, Xtend does not accepts instance initialization blocks in combination with inheritance and anonymous classes (B.xtend):
![xtend_problem](https://user-images.githubusercontent.com/20393472/32789327-d88a87d4-c95b-11e7-8cd4-9204428c4fff.png)

Hovewer, the same implementation in Java works (C.java). Would it be possible to adapt the Xtend language to accept such constructs?

**Comment by szarnekow** [comment]
Hi Tamas, in general I wouldn't consider the double brace idiom to be good practice. Thus it is not yet supported and there are no plans to work on it. What's wrong with making the code more explicit and use a named class instead of an anonymous class?

**Comment by miklossy** [comment]
Hi Sebastian! I encountered the problem as I wanted to implement JUnit test cases in Xtend using the JMockit http://jmockit.org/tutorial/Mocking.html framework. Such a "double brace idiom" occurs quite frequently in such JMockit snippest. 

Of course, as you suggested, one can make the code more explicit, but I think it would be nice to be able to use those code snippets directly in Xtend. Anyway, at least the Xtend error message in such cases could be improved for sure.

**Comment by cdietrich** [comment]
duplicates #236

**Comment by miklossy** [comment]
JMockit uses the "double brace idiom" for the definition of custom [Expectations](http://jmockit.github.io/tutorial/Mocking.html#expectation) and [Verifications](http://jmockit.github.io/tutorial/Mocking.html#verification) classes. To make the code very readable, they prefer to use anonym classes (where the usage of an instance initialization block is a must thanks to the absence of the constructor). 

As an alternative (as @szarnekow mentioned), one can use named classes, where the possibility to inline the instance initialization blocks into the constructors is given. But this approach would heavily downgrad the readability of the code and the user would not recognize the widespreaded "double brace idiom" pattern of JMockit any more. 

Apart from that, such derived and explicitly named Expectations and Verifications classes must be explicitly declared as final (anonymous classes are implicitly final) to be properly recognized/processed by JMockit (https://groups.google.com/forum/#!topic/jmockit-users/AIexMIbLTNM). That would make the code even more vulnerable.

**Comment by ArneDeutsch** [comment]
I have tried to modify the parser to support instance initializers. Because of some pecularities in the grammer this leads to ambiguousness grammar that is even hard to fix using syntactic predicates. Main issue: "annotation" is a keyword but could also be an identifier ... "annotation myId {}" could then be parsed as FIELD (with type "annotation" and name "myId") followed by an instance initializer ... or as ANNOTATION (with name "myId") and emty block. I have found no way to resolve this without heavy left factoring.
But probably the JMockit API call from this in Java:
```
new Expectations() {{
      mockInstance.someMethod(1, "test"); result = "mocked";
   }};
```
can be written in Xtend similar simple like this:
```
new Expectations => [
      mockInstance.someMethod(1, "test"); result = "mocked";
   ]
```
?

**Comment by miklossy** [comment]
Hi Arne!
I analysed your suggestion and it is unfortunately not feasible in our case, since the JMockit Verifications/Expectations classes are abstract. Anyway, thanks a lot for your effort!

**Comment by ArneDeutsch** [comment]
I guess you have to implement an annonymous subclass Try the following:

```
new Expectations {} => [
      mockInstance.someMethod(1, "test"); result = "mocked";
   ]
```

**Comment by miklossy** [comment]
Hi Arne! 
Unfortunately, I get the following error message when trying out your suggestion, since the result field of the Expectations class is protected.
![screenshot](https://user-images.githubusercontent.com/20393472/36480605-3711e528-170d-11e8-9012-d945987c9dc2.png)

**Comment by ArneDeutsch** [comment]
I would classify this as a bug. If I create a java class with a protected field I can reproduce the error. But if I create an xtend class with a protected field I get no error. But the generated java code is not different from the java class I created manually. @szarnekow ... do you agree this is a bug?

**Comment by szarnekow** [comment]
Yes, that would be a bug.

**Comment by cdietrich** [comment]
i have a dejavu. see ....

**Comment by cdietrich** [comment]
could be https://github.com/eclipse/xtext-extras/issues/229
@ArneDeutsch can you test with workspace 2.14

**Comment by ArneDeutsch** [comment]
Yes, works will in Xtext 2.14. @miklossy your case will work with upcoming version.

**Comment by miklossy** [comment]
Thanks guys! When is Xtext 2.14 expected to be released? I found no information to that on the [Eclipse Xtext Governance ](https://projects.eclipse.org/projects/modeling.tmf.xtext/governance) website.

**Comment by cdietrich** [comment]
i assume it will be in may and then bundles with eclipse photon in june

**Comment by cdietrich** [comment]
@miklossy if you want to evaluate please have a look at the nightlies

**Comment by miklossy** [comment]
I have just updated to Xtend 2.14.0.v20180214 and the problem still exists on my computer:
![screenshot](https://user-images.githubusercontent.com/20393472/36491995-61d71ce6-172c-11e8-91b8-bfb730ae20a7.png)

However, the bug regarding the use case @cdietrich described [here](https://github.com/eclipse/xtext-extras/issues/229) is fixed. Could you please check it once again?

**Comment by cdietrich** [comment]
i am not sure if this is already in the nightly from eclipse
can you have a look at https://github.com/eclipse/xtext-extras/pull/231/files

**Comment by cdietrich** [comment]
and .v20180214 looks close to my merge day

@kthoms is there something broken on infrastructure?

**Comment by miklossy** [comment]
The fix you described above is definitely included on my platform, that's why your use case has been fixed and works perfectly on my computer. But considering my use case, that slightly different from yours, the error is still reported.

**Comment by cdietrich** [comment]
could you please provide a reproducing example that does not require me to install tons of dependencies etc.

**Comment by miklossy** [comment]
@Test def void testExtrasIssue229_03() {
		'''
		class Sample {
			def doSomething() {
				new testdata.ClazzWithProtectedMember() => [
					member = "Hello"
				]
			}
		}
		'''.assertCompilesTo('''
		
		''')
		
	}

**Comment by miklossy** [comment]
Executing this test case fails with:
java.lang.AssertionError: Resource contained errors : [ERROR:The field member is not visible (Sample.xtend line : 4 column : 4)]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.xtend.core.tests.AbstractXtendTestCase.file(AbstractXtendTestCase.java:88)
	at org.eclipse.xtend.core.tests.AbstractXtendTestCase.file(AbstractXtendTestCase.java:69)
	at org.eclipse.xtend.core.tests.compiler.AbstractXtendCompilerTest.doAssertCompilesTo(AbstractXtendCompilerTest.java:61)
	at org.eclipse.xtend.core.tests.compiler.AbstractXtendCompilerTest.assertCompilesTo(AbstractXtendCompilerTest.java:56)
	at org.eclipse.xtend.core.tests.compiler.CompilerBugProtectedVisibilityTest.testExtrasIssue229_03(CompilerBugProtectedVisibilityTest.java:590)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by cdietrich** [comment]
problem is 

```
org.eclipse.xtext.xbase.typesystem.util.ContextualVisibilityHelper.isVisible(JvmMember)
```

which sorts this already out

@szarnekow do you have any hints?

**Comment by cdietrich** [comment]
the same code wont work in java so it is ok to fail in xtend

**Comment by miklossy** [comment]
What exactly do you mean with same java code?

**Comment by cdietrich** [comment]
```
public class Sample {
  public ClazzWithProtectedMember doSomething() {
    ClazzWithProtectedMember _clazzWithProtectedMember = new ClazzWithProtectedMember();
    final Procedure1<ClazzWithProtectedMember> _function = new Procedure1<ClazzWithProtectedMember>() {
      public void apply(final ClazzWithProtectedMember it) {
    	  it.member = "";
      }
    };
    return ObjectExtensions.<ClazzWithProtectedMember>operator_doubleArrow(_clazzWithProtectedMember, _function);
  }
}
```

**Comment by szarnekow** [comment]
You must create an anonymous subtype of Base in to make the protected fields of Base visible in the initializer
What you tried:
```
def doSomething() {
	new testdata.ClazzWithProtectedMember() => [
		member = "Hello"
	]
}
```

What you wanted to try:
```
def doSomething() {
	new testdata.ClazzWithProtectedMember { /* look ma, curly braces */ }  => [
		member = "Hello"
	]
}
```

**Comment by miklossy** [comment]
Hi Sebastian,
unfortunately your suggestion (introducing the curly braces) still reports the error. Executing the test case:
```
@Test def void testExtrasIssue229_03() {
	'''
	class Sample {
		def doSomething() {
			new testdata.ClazzWithProtectedMember{} => [
				member = "Hello"
			]
		}
	}
	'''.assertCompilesTo('''
	
	''')
	}
```
 yields in
```
java.lang.AssertionError: Resource contained errors : [ERROR:The field member is not visible (Sample.xtend line : 4 column : 4)]
```
Could you please try it on your computer?

**Comment by ArneDeutsch** [comment]
I can reproduce locally with your test case. The issue arises if the java class is not in the same package as the xtend class. Should we reopen https://github.com/eclipse/xtext-extras/issues/229 or create a new bug ticket?

**Comment by cdietrich** [comment]
do you get a java construct done that works? if we have nothing to compile to in java this wont help.

**Comment by ArneDeutsch** [comment]
Ok, after reading a bit more about xtend I understand. `=>` is the "with" operator and in that case the protected variables are not visible. And should not even be visible. Sorry Tamas, my suggestion was wrong. This can not work if protected functionality is accessed and hence will not work for your use case.

**Comment by miklossy** [comment]
I agree with @cdietrich. First of all we should define the corresponding java construct that the java compiler is able to compile: 
```
@Test def void testExtrasIssue229_03() {
	'''
	class Sample {
		def doSomething() {
			new testdata.ClazzWithProtectedMember{} => [
				member = "Hello"
			]
		}
	}
	'''.assertCompilesTo('''
	««« to be defined
	''')
	}
```

**Comment by miklossy** [comment]
I have just found the [JMockit-Xtend](https://github.com/borisbrodski/jmockit-xtend) library that enables to combine JMockit with Xtend.
