### ISSUE TITLE
Xtend feature request: Add generic parameters that accept generic parameters

### ISSUE THREAD

**Issue by plneappl** [eclipse/xtext-xtend#310]
Hi,

it would be nice to be able to define functions like this:

```xtend

interface Functor<F<?>> {
  def <A, B> F<B> fmap(Function<A, B> f, F<A> functor);
}

class ListFunctor extends Functor<List> { 
  override def <A, B>List<B> fmap(Function<A, B> f, List<A> list) {
    return list.map(f);
  }
}
```

This allows a function to tell callers that it returns the same structure it passed in - for example `fmap(Optional<A>)` would return an `Optional<B>`, whereas `fmap(List<A>)` would return a `List<B>`.
Right now you can only define the following, very verbose code:

```xtend
interface TypeCons1<A> { }
interface Functor<A, B, FA extends TypeCons1<A>, FB extends TypeCons1<B>> {
  def FB fmap(Function<A, B> f, FA functor);
}

class ListFunctor<A, B> extends Functor<A, B, List<A>, List<B> { 
  override def List<B> fmap(Function<A, B> f, List<A> list) {
    return list.map(f);
  }
}
```

This code also has the disadvantage that one could instantiate it with incompatible types, such as 
```xtend 
class BadFunctor extends Functor<A, B, MyList<A>, MyOptional<B>>
```

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
