### ISSUE TITLE
Don't create Deprecation issues on imports if the top-level type is deprecated.

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-xtend#314]
See behaviour of the JDT.

**Comment by cdietrich** [comment]
@szarnekow which type do you look at if there are multiple

**Comment by szarnekow** [comment]
To be discussed. We could either use the first type, consider all types (at least one is `@Deprecated` or check for the usages of the imports and look at the containing types.

**Comment by cdietrich** [comment]
We Decided to use the "any top level type is deprecated" implementation for this issue

**Comment by cdietrich** [comment]
Fixed in 2.14
