### ISSUE TITLE
Regenerate Docs before Release

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#324]

**Comment by kthoms** [comment]
Generating docs and publishing is done with the [website-deploy job](https://ci.eclipse.org/xtext/job/website-deploy/). This runs automatically on changes to branch `website-published`.

I think we can close this issue.

**Comment by cdietrich** [comment]
no

i am talking about the help plugins

**Comment by kthoms** [comment]
ah, sorry for the confusion

**Comment by cdietrich** [comment]
done
