### ISSUE TITLE
Fix Compile Issues in XtendUiModule

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#353]
maybe missing merge of https://github.com/eclipse/xtext-eclipse/pull/524/files

**Comment by cdietrich** [comment]
cc @ArneDeutsch cc @kthoms

**Comment by cdietrich** [comment]
i propose to simply use the new interface and not care about the old one....
and to write a note to the release notes.
@szarnekow what do you think

**Comment by ArneDeutsch** [comment]
Isn't that done with this merge: https://github.com/eclipse/xtext-xtend/commit/ba0ef951697911e86386b17102e45b1cfd57b00d !? There XtendUIModule was updated ...

**Comment by cdietrich** [comment]
No I think the problem is that the eclipse pr was not merged

**Comment by ArneDeutsch** [comment]
That one: https://github.com/ArneDeutsch/xtext-eclipse/commit/f56a3cadf1cc7de2cfbdcb75846c26aadcd4d18b !? Then ... just merge it!?

**Comment by cdietrich** [comment]
Yes that was it
