### ISSUE TITLE
Implement Xtend Validation rule "Redundant modifiers"

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#361]
In Xtend, the usage of the 'final' keyword in combination with the 'val' keyword is unnecessary. 

```Xtend
class A {
	final val a = 1
}
```
A Warning could be raised on the 'final' keyword in such cases.

**Comment by cdietrich** [comment]
could be added to `org.eclipse.xtend.core.validation.ModifierValidator.checkModifiers(XtendMember, String)`

**Comment by kthoms** [comment]
@miklossy Could you also provide a PR for a quickfix? I have opened #370 for that.

**Comment by kthoms** [comment]
How about making it more generic? The general issue is an unnecessary modifier. This is also true for public on classes or private on fields.

**Comment by miklossy** [comment]
@cdietrich I think this issue could be closed, since the PR has already been merged.

**Comment by miklossy** [comment]
The following cases have not been considered yet and should also be marked as 'Redundant modifier':

- public modifier on interfaces
- public modifier on constructors
