### ISSUE TITLE
SuppressWarnings not considered

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#371]
The following Xtend class raises the warning `Class is a raw type. References to generic type Class<T> should be parameterized`

```
class FooAdapter implements IAdaptable {
	override getAdapter(Class adapter) {}
}
```

It is expected that the warning is resolved by changing to:

```
class FooAdapter implements IAdaptable {
	override getAdapter(@SuppressWarnings("rawtypes") Class adapter) {}
}
```

The transpiled Java code contains also that annotation, besides a generic suppress-all-annotation
```
@SuppressWarnings("all")
public class FooAdapter implements IAdaptable {
  @Override
  public Object getAdapter(@SuppressWarnings("rawtypes") final Class adapter) {
    return null;
  }
}
```

**Comment by cdietrich** [comment]
does this dupe https://bugs.eclipse.org/bugs/show_bug.cgi?id=363685 ?

**Comment by kthoms** [comment]
Seems so. Could be worth to pick up again.
