### ISSUE TITLE
Xtend IDE: Hovering/Hyperlinking on links in Javadoc

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#372]
Currently, the Xtend IDE lacks the functionality of hovering/hyperlinking on Javadoc links. It would be useful to implement these features similar to JDT.
![screenshot](https://user-images.githubusercontent.com/20393472/36476207-79d48c40-16fd-11e8-9190-70926e19a173.png)

**Comment by miklossy** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=431101

**Comment by miklossy** [comment]
- hyperlink functionality has been implemented
- hovering still needs to be implemented

**Comment by miklossy** [comment]
Hovering/Hyperlinking functionality in Javadoc comments has been implemented, ticket can be closed.

**Comment by cdietrich** [comment]
Thanks again for the patches @miklossy
