### ISSUE TITLE
Find a way to get all tests result and not only the first failed project

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#38]

**Comment by spoenemann** [comment]
Doesn't the Maven option `-fae` do the thing?

**Comment by cdietrich** [comment]
yes, but only if test projects dont depend on each other

**Comment by spoenemann** [comment]
So is there anything we can do about it?

**Comment by cdietrich** [comment]
yes. make core.tests fail and you will see core.tests.java8 wont run.
so we could look why we need this dependency.

same for ide.tests

**Comment by dhuebner** [comment]
Fixed
