### ISSUE TITLE
It should be possible to configure a severity for "Redundant modifiers" check

### ISSUE THREAD

**Issue by akosyakov** [eclipse/xtext-xtend#384]
This PR introduces a new check as a warning: https://github.com/eclipse/xtext-xtend/pull/362. It could be quite noisy for big projects. It would be nice to be able to configure for building with grade as well as in Eclipse. Right now they don't appear in Eclipse at all.

Also having a multi quick fix for it would be good.

**Comment by cdietrich** [comment]
quickfix see #370

**Comment by cdietrich** [comment]
@akosyakov 
which xtext version do you use in eclipse?

**Comment by akosyakov** [comment]
I've tried from the nightly update site and https://ci.eclipse.org/xtext/job/xtext-snapshots/566/artifact/build-result/p2.repository/.

**Comment by cdietrich** [comment]
Fixed in 2.14. For Quickfix see  #370
