### ISSUE TITLE
Add support for Try-With-Resources

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#395]
we should add support for Try-With-Resources to Xtend and possibly to xbase too.

- implement grammar and metamodel
- implement typesystem 
- implement compiler
- implement J2X
- investigate what we can reuse from @LorenzoBettini s Jbase
- investigate how this can be ported down to xbase https://github.com/eclipse/xtext-extras/issues/244

https://bugs.eclipse.org/bugs/show_bug.cgi?id=366020

**Comment by LorenzoBettini** [comment]
Just a note, for Jbase, I preferred to impose a strict grammar rule(s) for the statements of a try-with-resource, https://github.com/LorenzoBettini/jbase/pull/60/files#diff-6b02d2d0e9eb77b59e2a6f9e8d50318eR276 ; that made a few things easier then; I think that's the same choice of Java itself? @szarnekow is already working on this, isn't he?

**Comment by cdietrich** [comment]
TODO consider to switch source level to java 8 everywhere

**Comment by epoell** [comment]
I implemented support for the try with resources statement this week (see commits above). :)

On Monday I will add support for try with resources within the XbaseInterpreter and corresponding tests.
However I thought I could already issue the pull requests, to parallelize the correction of the existent code and the interpreter work...

Have a nice weekend!

**Comment by epoell** [comment]
Hello!
I've a question which implementation is preferred: 
In most AutoClosable-implementing types, the close() method throws an Exception, thus in Java one has to handle this exception (by adding a catch phrase or a throw declaration).

In Xtend one now has two options:
**1)** one could let the generator handle the exception and add a catch clause per default.
( 1b) However users are free to add a catch clause, so one should probably inform them that close throws an exception as a warning or info)

**2)** one implements it as in Java and forces users to add an exception handling

**Comment by szarnekow** [comment]
As discussed offline: the validation should follow the same rules as the other Xtend expressions. If unhandled exceptions are set to be flagged, this should be done, otherwise sneaky throw should be generated.

**Comment by epoell** [comment]
Sebastian and I implemented solution 1b, so usually the compiler cares about the exception, with a sneakyThrow. If unhandled exceptions are configured to be handled by the user, an error is shown, similar to `throw new ...` expressions.

**Comment by szarnekow** [comment]
Thank you @epoell !
