### ISSUE TITLE
Add support for method references

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#396]
Xtend should support method references.

- implement grammar, typesystem, compiler
- implement j2x
- evaluate if this can be ported down to xbase https://github.com/eclipse/xtext-extras/issues/244

**Comment by lievenlemiengre** [comment]
I'm not sure that Xtend needs this, it's another feature to learn & lambdas are so flexible that they are less verbose than method references.

I would be nice if the compiler could optimize certain xtend lambdas to java method references, because they have (minor) performance advantages.

**Comment by cdietrich** [comment]
i was more thinking of existing java api

**Comment by szarnekow** [comment]
> I would be nice if the compiler could optimize certain xtend lambdas to java method references, 

Yes, that would also be a valid outcome of this ticket. In any case, we should certainly improve the user feedback when one types a Java style method reference.

**Comment by NetzwergX** [comment]
Method references in Java are quite powerful and increase readability compared to normal lambdas by a lot.

It would be prudent to have support for this in Xtend.

**Comment by szarnekow** [comment]
Absolutely true, but unfortunately it's a lot of effort to implement those and currently there are - as for other open source projects, too - only limited resources available and those have to be balanced well. I'm afraid without driving force (aka sponsor), this is not going to happen.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
