### ISSUE TITLE
Add Support for Bitwise Operators

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#398]
Xtend should support the java bytewise operators e.g `|` and `&`
- implement grammar, typesystem, compiler
- implement j2x
- evaluate if this can be ported down to xbase eclipse/xtext-extras#244

**Comment by LorenzoBettini** [comment]
I've implemented that in the context of Jbase, https://github.com/LorenzoBettini/jbase/pull/47/files , note that this requires also to add the corresponding grammar rule up in the grammar. Can I help with that?

**Comment by cdietrich** [comment]
help is welcome. we plan to come up with a zoo of enhancements with xtext 2.15 (after photon)
we are also thinking about how we can bring this to xbase without breaking existing clients. e.g. by introducing a Xbase Subgrammar

**Comment by Hanksha** [comment]
I don't know if it's a viable solution but in my case I created a class to support bitwise **and** and **or** operators.

```java
class Bitwise {

    @Pure
    @Inline('$1 | $2')
    static def int ||(int n1, int n2) { throw new UnsupportedOperationException('inlined method') }

    @Pure
    @Inline('$1 & $2')
    static def &&(int n1, int n2) { throw new UnsupportedOperationException('inlined method') }

}
```

So something like `val bitwise = 1 || 2 || 3` generates the code:

```java
int _or = 1 | 2;
final int bitwise = _or | 3;
```

Only annoying thing is that I have to think of importing the extension methods every time.

**Comment by LorenzoBettini** [comment]
not to mention that `||` you use in the DSL source are not the bitwise operators ;)

**Comment by Hanksha** [comment]
@LorenzoBettini Yes off course, from the point of view of Java language. It's still better than to have to type `1.bitwiseOr(2).bitwiseOr(3)` which quickly becomes annoying while using frameworks relaying heavily on bitwise operators like SWT.

**Comment by LorenzoBettini** [comment]
@Hanksha this might be OK for integers, but bitwise operators `|` and `&` are used in Java also for boolean expressions to denote eager evaluation as opposed to the lazy evaluation of `||` and `&&`... something that, to be honest, I discovered only when working on this feature. I think it's also one of the most unknown and unused Java features by the way ;)

**Comment by Hanksha** [comment]
@LorenzoBettini Indeed, I didn't know about it either (neither encountered a case where I needed it)

**Comment by miklossy** [comment]
Recently I also encountered the missing support of `|` especially working wit SWT.
@LorenzoBettini May I ask for the state of this issue?

**Comment by LorenzoBettini** [comment]
I thought @szarnekow was working on this?

If I recall correctly adding this to Xbase is impossible without breaking existing clients?
So this should be added only to Xtend?

**Comment by miklossy** [comment]
Adding the support to only Xtend would be a good enough solution for me.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
