### ISSUE TITLE
Improve Number Literals

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#400]
Xtend (and xbase) should have support for number literals as in java. currently e.g. binary and octal literals are missing

- implement grammar, typesystem, compiler
- implement j2x
- evaluate if this can be ported down to xbase eclipse/xtext-extras#244

**Comment by lievenlemiengre** [comment]
Octal literals are the source of a number of Java puzzlers because O and 0 are hard to distinguish and almost no-one uses them.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
