### ISSUE TITLE
Added @Override has broken photon compatibility

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext-xtend#412]
A recent comit has added @Override to a method of org.eclipse.xtend.ide.formatting.preferences.FormatterModifyDialog. This has broken compatibilty with eclipse photon (for more details see: https://github.com/eclipse/xtext-eclipse/issues/539).

To restore compatibility we have to remove the @Override again.

**Comment by cdietrich** [comment]
@ArneDeutsch can you please provide a pr

**Comment by cdietrich** [comment]
Fixed in 2.14
