### ISSUE TITLE
Rename refactoring should not replace attribute name by accessor name

### ISSUE THREAD

**Issue by sigiesec** [eclipse/xtext-xtend#432]
When using a rename refactoring on a field encapsulated with accessors, existing accesses that use the attribute/bean name should be preserved.

For example:

```
@Accessors(PUBLIC_GETTER) class Foo {
	val String x
}

class Bar {
	def doit(Foo foo) { foo.x }
}
```

When renaming x to y, foo.x is currently replaced by foo.getY

I would expect it to be replaced by foo.y instead.

**Comment by cdietrich** [comment]
element is filtered.
org.eclipse.xtext.xbase.ui.jvmmodel.refactoring.JvmModelReferenceUpdater.getRefTextEvaluator(...).new RefTextEvaluator() {...}.isValid(IEObjectDescription)

**Comment by cdietrich** [comment]
@szarnekow any ideas?

**Comment by szarnekow** [comment]
Likely a problem in the interaction / the logic of `SerializerScopeProvider.getExecutableScope(XAbstractFeatureCall, JvmIdentifiableElement)` and `ReferenceUpdater.updateReference(ITextRegionDiffBuilder, IUpdatableReference)`

**Comment by cdietrich** [comment]
@tivervac is this related to the fix you are currently working on?

**Comment by tivervac** [comment]
@cdietrich It's definitely in the same area, but I don't think my fix will change anything

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
