### ISSUE TITLE
IDE: Highlight references to selected variable/attribute

### ISSUE THREAD

**Issue by sigiesec** [eclipse/xtext-xtend#436]
It would be very nice if the Xtend Eclipse editor highlighted references to the currently selected variable/attribute, just as the Java editor does.

**Comment by cdietrich** [comment]
what does you exactly mean. xtend has support for mark occurrences if you enable the button in the top button bar

**Comment by sigiesec** [comment]
Oops, sorry... I turned this on for the Java editor, and assumed this was also applied for the Xtend editor, but the settings are independent of each other. It works now as I expected :)

**Comment by cdietrich** [comment]
<img width="410" alt="bildschirmfoto 2018-04-25 um 12 36 32" src="https://user-images.githubusercontent.com/238736/39240951-9bd3ff2e-4885-11e8-89a5-1f1d1a2b543c.png">
