### ISSUE TITLE
JUnit5: Run As action not available in run menu

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#440]
The context menu does not offer the action "Run As / JUnit Test" on Xtend classes that are written for JUnit 5.

![screenshot 44](https://user-images.githubusercontent.com/265597/39368225-53e7ff20-4a39-11e8-8048-b273954edf89.png)

**Comment by cdietrich** [comment]
@kthoms is this fixed now?

**Comment by kthoms** [comment]
Yes
