### ISSUE TITLE
`instanceof` on a raw type generates a validation warning

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext-xtend#447]
Xtend version: `Xtend IDE - 2.14.0.v20180509-0601` and/or `Xtend IDE - 2.13.0.v20170912-1954`

`Foo.java`:
```java
import java.util.Map;

public class Foo {

  static void foo(Object o) {
    if (o instanceof Map) {
    }
  }

}
```

`Bar.xtend`:
```java
import java.util.Map

class Bar {

  static def void bar(Object o) {
    // Unexpected warning: Map is a raw type. References to generic type Map<K, V> should be parameterized
    if (o instanceof Map) {
    }
  }

}
```

It works as I would expect for Java. The generated Java source looks correct too even if I remove the `@SuppressWarnings("all")` annotation from the class.

Workaround:
```java
import java.util.Map

class Bar {

  static def void bar(Object o) {
    if (o instanceof Map<?, ?>) {
    }
  }

}
```

PS: Feel free closing it if there is already a ticket I have overlooked. If it belongs to another project, let me know and I move it. Thanks!

**Comment by cdietrich** [comment]
Fixed in 2.15
