### ISSUE TITLE
No documentation for the diamond and the spaceships operator

### ISSUE THREAD

**Issue by Lexanius** [eclipse/xtext-xtend#452]
There are 2 operators in the documentation: 
```
e1 <> e2 | e1.operator_diamond(e2)
e1 <=> e2 | e1.operator_spaceship(e2)
```
But there are no explanation for the common using. 

It seems that `<>` is for `new ArrayList<>()` but is it than really a operator.

**Comment by cdietrich** [comment]
afaik `operator_diamond` is currently unused.
`operator_spaceship` does a comparison does a compareTo on comparables.

you can use them in your own code by defining the methods
