### ISSUE TITLE
StackOverflowError in DeclaratorTypeArgumentCollector

### ISSUE THREAD

**Issue by vorburger** [eclipse/xtext-xtend#461]
We're seeing StackOverflowError (in both the xtend-maven-plugin and in-IDE) around here:

```
Exception in thread "main" java.lang.StackOverflowError
	at org.eclipse.xtext.xbase.typesystem.references.LightweightTypeReferenceFactory.doVisitParameterizedTypeReference(LightweightTypeReferenceFactory.java:173)
	at org.eclipse.xtext.xbase.typesystem.references.LightweightTypeReferenceFactory.doVisitParameterizedTypeReference(LightweightTypeReferenceFactory.java:52)
	at org.eclipse.xtext.common.types.impl.JvmParameterizedTypeReferenceImplCustom.accept(JvmParameterizedTypeReferenceImplCustom.java:53)
	at org.eclipse.xtext.common.types.util.AbstractTypeReferenceVisitor.visit(AbstractTypeReferenceVisitor.java:34)
	at org.eclipse.xtext.xbase.typesystem.references.LightweightTypeReferenceFactory.toLightweightReference(LightweightTypeReferenceFactory.java:83)
	at org.eclipse.xtext.xbase.typesystem.references.StandardTypeReferenceOwner.toLightweightTypeReference(StandardTypeReferenceOwner.java:117)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:158)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:77)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:39)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.accept(ParameterizedTypeReference.java:840)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:159)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:77)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:39)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.accept(ParameterizedTypeReference.java:840)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:159)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:77)
	at org.eclipse.xtext.xbase.typesystem.util.DeclaratorTypeArgumentCollector.doVisitParameterizedTypeReference(DeclaratorTypeArgumentCollector.java:39)
```

@kthoms @cdietrich hallo! :smile: any thoughts / inputs / suggested next steps? Attach a debugger, and figure it out, I guess? @svenefftinge @akosyakov and other old friends, I understand you've long sailed on to new shores to still be interested in this? :smile: 

More background in https://jira.opendaylight.org/browse/NETVIRT-1290 ... I don't want to come accross as alarmist or pushy or anything, but this has just brought down most (master) builds of the fairly large https://www.opendaylight.org community... so is a Blocker for us over there. I'll debug it to see if I can figure out how to work around it ASAP. If not, it would mean that we would have to remove our usage of Xtend in extremis... time to switch to Kotlin, may be? :smiling_imp:

**Comment by kthoms** [comment]
Since it seems reproducible for you, you may give us some insights on the state when hitting the StackOverflowError? You could add remote debugging options, set an exception breakpoint for StackOverflowError and attach to the debugged VM then.
We would like to solve that issue, but since it is 3rd party we need more input.
Another option would be a small description how to set up the situation for ourselves.

**Comment by cdietrich** [comment]
Which Xtext version?

**Comment by cdietrich** [comment]
Cc @szarnekow

**Comment by cdietrich** [comment]
Besides this we would need a minimal reproducing example

**Comment by vorburger** [comment]
I've searched for `StackOverflowError` and there [was this](https://github.com/eclipse/xtext-xtend/issues/158) and a [this on on bugs.eclipse.org](https://bugs.eclipse.org/bugs/show_bug.cgi?id=491929) - notably this looks the same as https://bugs.eclipse.org/bugs/show_bug.cgi?id=414767.

@cdietrich @kthoms thanks for engaging SO fast!

> Which Xtext version?

originally 2.13.0 but [just tested bumping to 2.14.0](https://git.opendaylight.org/gerrit/#/c/72550/) but still there.

> Another option would be a small description how to set up the situation for ourselves.

I don't have a simple standalone reproducer. Creating that requires me finding the cause... ;-)

But if you don't mind downloading half the universe then it should actually be very easy for you to reproduce if you d the following (I hope I'm not forgetting any steps, but try and shout if NOK):

It will need to grab loads of stuff from https://nexus.opendaylight.org, so [as documented here](http://docs.opendaylight.org/en/latest/developer-guide/developing-apps-on-the-opendaylight-controller.html), do:

    cp -n ~/.m2/settings.xml{,.orig} ; wget -q -O - https://raw.githubusercontent.com/opendaylight/odlparent/master/settings.xml > ~/.m2/settings.xml

And now doing this should hit it:

    git clone https://git.opendaylight.org/gerrit/netvirt
    cd netvirt/aclservice/impl
    mvn -Pq clean package

> give us some insights on the state when hitting the StackOverflowError? You could add remote debugging options, set an exception breakpoint for StackOverflowError and attach to the debugged VM then.

OK I'll try that and report back if I find anything... but don't let that stop you from trying to repro is as above! ;)

BTW: I suspect that his is caused by some recent code change on our side which added a new library or introduced a new generics thing (but it's nearly impossible to pinpoint; this is in a huge community with lots of spinning parts changing all the time). What could help as well to at least pinpoint what is causing this, if not solving it, would be to catch the `StackOverflowError` and provide context on which type it happened?

**Comment by cdietrich** [comment]
The main point is. Debugging this with a huge ton of unrelated code is pita.
So I won’t come to doing this that soon

**Comment by cdietrich** [comment]
Just out of curiosity. Is this a real stackoverflow (recursive infinite loop) or does increasing the stacksize for the vom (-Xss) help

**Comment by vorburger** [comment]
> does increasing the stacksize for the vom (-Xss) help

still happens even with:

    export MAVEN_OPTS="-Xss1024m -Xmx4096m -Xverify:none"

**Comment by cdietrich** [comment]
Hmm ok. Unfortunately reproducing this will mess up my whole system (custom settings xml etc) so i will see when I find the time to reproduce that. Unfortunately i know way to few about the xbase internals to have any idea or solution here . Thus understanding what causes this is crucial

**Comment by thSoft** [comment]
Isn't this reproducible with the Scala example described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=414767#c0?

**Comment by cdietrich** [comment]
yes and no:

- again if have to set up a environment with scala and xtend.
- scala is untested togther with xtend.
- the error is not 100% the same

**Comment by vorburger** [comment]
>> Which Xtext version?
> originally 2.13.0 but just tested bumping to 2.14.0 but still there.

also still reproduced with locally self built 2.15.0-SNAPSHOT


> reproducible with the Scala example described in [eclipse.org Bug 414767](https://bugs.eclipse.org/bugs/show_bug.cgi?id=414767#c0)?

@thSoft that's a great point - @cdietrich there is your minimal reproducing example... :smiley:

**Comment by cdietrich** [comment]
well 2.15 and 2.14 differ in about 3 commits

**Comment by vorburger** [comment]
@thSoft can you make https://github.com/vorburger/xtend-StackOverflowError-issue461 reproduce the StackOverflowError ? I tried to do what you described in [eclipse.org Bug 414767](https://bugs.eclipse.org/bugs/show_bug.cgi?id=414767), but it's giving me an `IllegalStateException` not this `StackOverflowError`, but also _"Ambiguous feature call. The methods
<A> empty() in List and <A> empty() in List both match."_ so maybe I'm just not getting some Scala thing which you could fix up in a PR to make that project a minimal reproducing example... I'll ignore that for now and instead focus on debugging it in the context where we hit it.

**Comment by cdietrich** [comment]
Involved Types (random accurrences on stacktrace):

Class<PortSubnet>
Class<Unbound[N]>
Identifiable<Unbound[K]>
PortSubnet
PortSubnetKey
Unbound[K]
JvmGenericType: org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.aclservice.rev160608.port.subnets.PortSubnetKey (visibility: PUBLIC, simpleName: PortSubnetKey, identifier: org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.aclservice.rev160608.port.subnets.PortSubnetKey, deprecated: false) (abstract: false, static: false, final: false, packageName: org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.aclservice.rev160608.port.subnets) (interface: false, strictFloatingPoint: false, anonymous: false)
JvmGenericType: org.opendaylight.yangtools.concepts.Identifier (visibility: PUBLIC, simpleName: Identifier, identifier: org.opendaylight.yangtools.concepts.Identifier, deprecated: false) (abstract: true, static: false, final: false, packageName: org.opendaylight.yangtools.concepts) (interface: true, strictFloatingPoint: false, anonymous: false)

**Comment by cdietrich** [comment]
unfortunately my xbase knowledge will not be sufficient to come further on this.
hope from @szarnekow to give some insights

**Comment by cdietrich** [comment]
will try to analyze with a bigger stacksize

**Comment by cdietrich** [comment]
bad file is IdentifiedPortSubnetBuilder.xtend

**Comment by cdietrich** [comment]
debugging stackoverflows takes forever :(

**Comment by cdietrich** [comment]
hmm debugging is still running. but i can see what you are not a fan of explicit method return types @vorburger

**Comment by cdietrich** [comment]
```
left Identifier<Unbound[N]> => InterfaceKey 0
left Identifiable<Unbound[K]> => Interface 0
left Identifier<Unbound[N]> => InterfaceKey 0
left Identifiable<Unbound[K]> => Interface 0
left Identifier<Unbound[N]> => InterfaceKey 0
left Identifiable<Unbound[K]> => Interface 0
left Identifier<Unbound[N]> => InterfaceKey 0
```

**Comment by cdietrich** [comment]
bad classes IdentifiedAceBuilder IdentifiedInterfaceWithAclBuilder StateInterfaceBuilderHelper

**Comment by cdietrich** [comment]
problematic are the return InstanceIdentifier.builder(Interface) calls

**Comment by vorburger** [comment]
Yup - confirming it's definitely something generics related in one of those three *Builder (or that `StateInterfaceBuilderHelper.xtend`) [you can see here](https://github.com/opendaylight/netvirt/tree/cbe43c366abf098554a230c975e7750ed1ffa707/aclservice/impl/src/test/java/org/opendaylight/netvirt/aclservice/tests), but not anything in those (huge!) `FlowEntryObjectsBase.xtend`, `FlowEntryObjectsStateful.xtend` or `FlowEntryObjectsStatefulIPv6.xtend` classes... 

I'm saying this because [removing those *Builder[Helper] classes in Xtend "fixes" this for us](https://git.opendaylight.org/gerrit/#/c/72573/) - rewrote them in Java, so worked around, not really fixed in Xtend obviously - but unblocks our project's broken build! :smile_cat: 

PS: Amended the instructions above for how to reproduce this with Git rev from before our workaround.

**Comment by vorburger** [comment]
> BTW: I suspect that his is caused by some recent code change on our side which added a new library or introduced a new generics thing (but it's nearly impossible to pinpoint; this is in a huge community with lots of spinning parts changing all the time).

> confirming it's definitely something generics related 

we (credits to my colleauge @skitt) have strong reason to suspect that [this recent change in our community caused this for us](https://git.opendaylight.org/gerrit/#/c/72211/22/binding/yang-binding/src/main/java/org/opendaylight/yangtools/yang/binding/InstanceIdentifier.java) - does that look like enough generics foo black magic to trip over Xtend? :smiling_imp: 

> What could help as well to at least pinpoint what is causing this, if not solving it, would be to catch the StackOverflowError and provide context on which type it happened?

This still seems like a good idea to me in general, for future problem like this.

**Comment by skitt** [comment]
It’s not just strong reason to suspect, I’ve verified that that is the change which broke Xtend for us.

**Comment by cdietrich** [comment]
[issue461.zip](https://github.com/eclipse/xtext-xtend/files/2063230/issue461.zip)
reproducible example (with no deps)

**Comment by cdietrich** [comment]
[issue461b.zip](https://github.com/eclipse/xtext-xtend/files/2063315/issue461b.zip)
more stripped down version
@szarnekow i definitively need your help for that

**Comment by szarnekow** [comment]
@cdietrich sure thing. I can take a look.

**Comment by szarnekow** [comment]
Thank you for the repro. If I put everything into one file, it looks like this:

```
package com.acme;

class IdentifiedInterfaceWithAclBuilder {

	def void identifier(InstanceIdentifierBuilder<Object> b) {
		b.child(Interface, null)
	}
	interface ChildOf<P> {}
	interface ChoiceIn<P> {}
	interface Identifiable<T> {}
	interface Identifier<T extends Identifiable<?>> {}
	interface InterfaceKey extends Identifier<Interface> {}
	interface Interface extends ChildOf<Object>, Identifiable<InterfaceKey> {}
	interface InstanceIdentifier<T> {}
	interface InstanceIdentifierBuilder<T> {
		def <C extends ChoiceIn<? super T>, N extends ChildOf<? super C>> InstanceIdentifierBuilder<N> child(
			Class<C> caze, Class<N> container);
		def <N extends Identifiable<K> & ChildOf<? super T>, K extends Identifier<N>> InstanceIdentifierBuilder<N> child(
			Class<N> listItem, K listKey);
	}
}
```

**Comment by szarnekow** [comment]
PR [eclipse/xtext-extras#257]

**Comment by szarnekow** [comment]
Fixed

**Comment by cdietrich** [comment]
thx @szarnekow
