### ISSUE TITLE
Custom AA throw exception if eclipse is a lower java version than the code

### ISSUE THREAD

**Issue by Lexanius** [eclipse/xtext-xtend#465]
Hi team,

i play again with the java-versions and xtend and get this error messages:

`Problem while loading annotation processor: generator/annotation/ExceptionProcessor has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

I found out, that my eclipse load with java8 (JAVA_HOME) but the project compile against java10.

## Problem
The customs AA will not compile and can not used in eclipse. The jdk is ignored by the processor.

## Workaround 
* Use same versions for eclipse and the project.

## Additional:

The projects (one for AA and one for the rest) are both part of a maven application. Compiling with java10 with maven works perfectly.

I'm sorry,

Lexanius

**Comment by cdietrich** [comment]
@Lexanius  that is your expectation about this issue?

**Comment by Lexanius** [comment]
I think that the xtend Processor should use the jdk of the project, instead the use the jre the eclipse is running.

**Comment by cdietrich** [comment]
i think think this is possible right now with the ways active annotations run. they are executed in the context of the host eclipse, not in the context of any project

@szarnekow any comments?

**Comment by szarnekow** [comment]
True. It is not possible. The Xtend compiler of course runs in the host eclipse and AA are effectively compiler plugins. It would not be reasonable or even possible, to run these in the context of the project JRE.

**Comment by cdietrich** [comment]
thus i will close this as wontfix
