### ISSUE TITLE
[Maven]  Consider to Switch to annotations instead of doclet

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#469]

**Comment by cdietrich** [comment]
In the early days of java there were no annotations. but javadoc processors (xdoclet). so maven used special javadoc annotations to describe the api of plugins. we use these in our maven plugins.
since java has annotations maven plugins api is described with real annotations (https://maven.apache.org/guides/plugin/guide-java-plugin-development.html) so we should use these in our plugins as well

Tasks:

- replace javadoc annotations with real annotations
- tests of plugins should still be green
- content assist e.g. on m2e should work

**Comment by kthoms** [comment]
Done.
