### ISSUE TITLE
What would be cool in Xtend

### ISSUE THREAD

**Issue by Lexanius** [eclipse/xtext-xtend#473]
I work a lot with Xtend last time an and i found out that little improvements can make the language much cooler:

Problem: often in  Templates there are:

```
«IF packageName !== null»«packageName».«ENDIF»
«IF bar !== null»«bar».«ENDIF»
«IF baz !== null»«baz».«ENDIF»
```

You must write a lot of `!== null` or `=== null`

Maybe there can be a little improvement:
`«IF? packageName»«packageName».«ENDIF»`

A `IF?` thats mean the if is true, if the next expression is not null. The ? like the elvis operator. I know there are no solution for the `=== null` maybe `IFn`

Lexanius

**Comment by Lexanius** [comment]
I update the text. Yes my compute somehow press enter^^

**Comment by Lexanius** [comment]
A second idea was the concept of `extensions class`:
You can mark a class that in a multi-class file that this class is a extension for all other classes in this file.
It replace the `import static extension clazz.*`

Example a File:

```
class A {
  val a = "bar".baz()
}

extension class B {
   static def baz(String it) {
     it + "extension"
   }
}

class V {
  val v = "baz".baz()
}
```

The problem is, that I don't know the plans for the `extension` keyword. Maybe it will be used in the better.

**Comment by szarnekow** [comment]
Regarding the local extension class: Looks like a static extension import does the same for your usecase. Did I miss a detail about your idea?

**Comment by Lexanius** [comment]
Hrsg I leave it out the detail: auto extension imports are bad supported by eclipse, first the autoimport of extension, secound: auto organise imports with extensions . I think it save work, not to scroll to the top of the file it make that import
