### ISSUE TITLE
Outdated XtendGrammarAccess class in 2.14.

### ISSUE THREAD

**Issue by gallandarakhneorg** [eclipse/xtext-xtend#474]
There is an inconsistency between the definition of the Xtend Grammar and the `XtendGrammarAccess` class.

The Xtend grammar contains the rule `MultiTypeReference`.
But, the `XtendGrammarAccess` does not contain the `getMultiTypeReferenceAccess` function.

It seems that the `XtendGrammarAccess` is outdated.

Source: https://www.eclipse.org/forums/index.php/t/1093737/

**Comment by cdietrich** [comment]
@szarnekow could you please do a pr for this?

**Comment by gallandarakhneorg** [comment]
I think I have detected another issue related to the outdated XtendGrammarAccess.

An instance of `XtendGrammarAccess.MultiCatchTypeElements` is declared. But, the attribute `rule` is initialized to `null`.
It causes a `NullPointerException` when initializing the field `cGroup` within the same type.

I have check the Xtend grammar and did not find any rule with the name `MultiCatchType`.

**Comment by cdietrich** [comment]
in xtext 2.14 the xtext file and all java files dont match.
you can have a look at xtext 2.15 snapshots if it is still a problem.

@szarnekow am i correct this ticket should be closed now?

**Comment by szarnekow** [comment]
Yes
