### ISSUE TITLE
Quickfix for removing redundant modifiers deletes class comments

### ISSUE THREAD

**Issue by Boereck** [eclipse/xtext-xtend#495]
Hi,

I was just using the quickfix for removing redundant modifiers (see #370) on a bunch of Xtend files and I realized that when visibility modifiers on classes and interfaces are removed, the class documentation goes out the windows as well. Interestingly the comment is preserved if an annotation is applied to a class. It seems not to affect method comments.

**Comment by cdietrich** [comment]
Duplicates https://github.com/eclipse/xtext/issues/2306

**Comment by Boereck** [comment]
Ha, the GuiHub issue search does not seem to be great. I did search for an existing issue, before opening this one. My apologies for creating this duplicate.
