### ISSUE TITLE
XtendReferenceFinder is not part of the public API.

### ISSUE THREAD

**Issue by gallandarakhneorg** [eclipse/xtext-xtend#498]
Within my [DSL](https://github.com/sarl/sarl), I would like to inject an instance of `XtendReferenceFinder`.

Because the package `org.eclipse.xtend.core.findReferences` is not expected as part of the public API, I cannot have a reference to `XtendReferenceFinder` within my injector.

Is it possible to put the package within the public API?

**Comment by cdietrich** [comment]
we would need to export it as xinternal/xfriends

**Comment by gallandarakhneorg** [comment]
I means that you will have a specification like "io.sarl.xxxx" within your project MANIFEST.
Is it a problem according to your Xtend policies?

**Comment by cdietrich** [comment]
no i'd add xtend.ide/ide.common as frieds.
no but you will get a warning that you use internal api

(as you already get it at all other places)

**Comment by szarnekow** [comment]
To be explicit about this: Xtend does not offer any kind of API when it comes to language inheritance. So no promises about breaking changes or backwards compatibility. But yes, we can export all packages as internal.

**Comment by cdietrich** [comment]
Fixed in 2.15
