### ISSUE TITLE
Switch statement fall through functionality limited/missing

### ISSUE THREAD

**Issue by dknopp** [eclipse/xtext-xtend#510]
I'm new to xtend so perhaps I missed it in the documentation but how do you do fall through with code, example:

switch(value) {
case ONE:
   // some logic goes here
case TWO:
   // some other logic goes here
default:
   // some other logic goes here
}

Expecting case one and two to execute when the value passed into the switch statement is ONE. This would be consistent with Java, C, C++, Java Script, and many other languages.

How is this supposed to work / how are you supposed to control this behavior without the break statement?

JavaScript example if you want to run it in your browser.
t = 1
switch(t) { case 1: t = 1; console.log('1'); case 2: console.log('2'); break; default: console.log('3'); }

**Comment by tivervac** [comment]
The switch expression is explained [here](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#switch-expression). TL;DR: only the matching block is executed, the others are never entered. If your want multiple conditions to trigger the same code you can just use a comma instead of a colon:
```
switch(value) {
case ONE,
case TWO:
// some other logic goes here
default:
// some other logic goes here
}
```

**Comment by cdietrich** [comment]
i think this is done by intention. correct @szarnekow ?

**Comment by dknopp** [comment]
Thank you @tivervac much appreciated. I did see that, I'm interested in a more complicated fall through instead of multiple conditions, a feature of Java and other languages i.e.

case ONE,
 // do some logic, then fall through
case TWO:
 // do some more logic

Now as @cdietrich ask, if this was done by intention that's fine, I'm curious on the reasoning but it's only a point of curiosity at that point :)

**Comment by szarnekow** [comment]
Indeed this is intentional behavior since we estimated that the fall-through feature does not carry its own weight, e.g. it causes more bugs in practice than it helps to solve problems. It's unlikely to be changed.
