### ISSUE TITLE
Improvements to 'Validation rule to ensure void return type in JUnit method'.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#516]
The [Pull Request](https://github.com/eclipse/xtext-xtend/pull/488) introduced a new Xtend validation rule to ensure the void return type on methods having JUnit annotations. 

I observed that such validation issues are also reported as follow up issues of other issues:
![screenshot](https://user-images.githubusercontent.com/20393472/43255437-1bedc3c0-90ca-11e8-84da-b85c561c861e.png)

I think it would be useful not to report such follow up validation issues, since the actual cause is somewhere else. What do you think? Would it be possible? / Does it makes sense at all?

**Comment by szarnekow** [comment]
The validation should not issue errors if the method body does already contain errors I suppose.

**Comment by szarnekow** [comment]
There is no infrastructure yet available to make `@Check` based validation dependent on each other or on dependent on the presence or absence of linking or syntax problems. I'd rather postpone this one.

**Comment by cdietrich** [comment]
TODO:

- debug if the method is typed as "unknown"
- if yes change the check to not flag unknow types as non void

**Comment by miklossy** [comment]
Thx for the nice suggession @cdietrich! I created the corresponding PR.

**Comment by cdietrich** [comment]
Fixed in 2.15 thx for the patch @miklossy

**Comment by dhuebner** [comment]
@miklossy @cdietrich 
Is the validation severity configurable? If so, in which errors/warnings section. 
Also, the validation should check the Test class `RunWith` annotation. A custom test runner can work with test method return types, in fact the validation prevents using such kinds of custom test runners in Xtend.

**Comment by cdietrich** [comment]
Please open a new issue and fix it

**Comment by dhuebner** [comment]
Well, it doesn't seem to be an issue for you.

**Comment by cdietrich** [comment]
well you did no care the last 12 months so what

**Comment by dhuebner** [comment]
Nice support, thanks!

**Comment by cdietrich** [comment]
@dhuebner you provide more committers to Xtext than itemis does. so if you find something improvable so report it and provide a patch instead of reopening random old tickets and just complaining

**Comment by miklossy** [comment]
I am absolutely agree with @cdietrich
