### ISSUE TITLE
Xtend Outline Misses "Run as" (e.g. Junit (Plugin) Test) Context Menu entries

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#522]
Xtend Outline Misses "Run as" (e.g. Junit (Plugin) Test) Context Menu entries. would be nice to have the same features as jdt here.

**Comment by miklossy** [comment]
The `Run As` -> `Java Application` context menu is also missing from the Outline View of a 
`def static void main(String[] args])` method.
![screenshot](https://user-images.githubusercontent.com/20393472/47146407-3ccc8d80-d2cc-11e8-9c1f-1ad51e418b2c.png)

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
