### ISSUE TITLE
Changing Xtend>Compiler>Output settings asks for rebuild

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-xtend#528]
When you change a setting in Xtend>Compiler>Output... it asks to rebuild the project. However, this is only needed if the directory changed.

**Comment by tivervac** [comment]
@cdietrich If the options didn't change, then no rebuild is requested.  However, if you change options in the second part of the preference page, a rebuild is required even though this is not necessary. e.g. when you change the "Create directory if it doesn't exist" shouldn't request for a rebuild as it doesn't need one.

My implementation allows for fine grained control of which options should request a rebuild and which ones shouldn't.

**Comment by tivervac** [comment]
@cdietrich do "Ignore generated Java source when debugging (Use for Android)"
and "Hide synthetic local variables in the debugger" require a rebuild?

**Comment by cdietrich** [comment]
yes

**Comment by tivervac** [comment]
Fixed in eclipse/xtext-eclipse
