### ISSUE TITLE
Wrong warning for fields with annotations

### ISSUE THREAD

**Issue by Lexanius** [eclipse/xtext-xtend#548]
Hi,

I working in xtend 2.14 with google guice 4, junit5 and mockito to setup a test. 
So i setup a test with annotations:

![wrong_warning_xtend](https://user-images.githubusercontent.com/1294835/44842169-74607700-ac45-11e8-900d-6a59a5d04cb0.PNG)

I get the warning: `The value of the field GeneratorTest.projectFileSystemAccess is not used`, that is wrong.

The java file has no warning for:
```
    @Mock
    @Bind
    ProjectFileSystemAccess projectFileSystemAccess
```
See:
![wrong_warning_java](https://user-images.githubusercontent.com/1294835/44842237-99ed8080-ac45-11e8-8eae-abfb1229afea.PNG)

The workaround is to public the fields, but it feels false.

Lexanius

**Comment by cdietrich** [comment]
TODO investigate if JDT offers a black/whitelist of annotations to consider
