### ISSUE TITLE
Using if as ternary expression replacement includes following code into else branch

### ISSUE THREAD

**Issue by enikao** [eclipse/xtext-xtend#549]
Consider this Xtend class:

````xtend
class InvalidConcat {
	var Object target
	var String targetName
	var String version
	
	override toString() {
		if (target !== null) {
			target.toString
		} else {
			targetName
		} + ' @ ' + version
	}
}
````

I'd assume that `' @ ' + version` is attached to both branches. However, it is moved into the else branch:

````java
public class InvalidConcat {
  private Object target;
  
  private String targetName;
  
  private String version;
  
  public String toString() {
    String _xifexpression = null;
    if ((this.target != null)) {
      _xifexpression = this.target.toString();
    } else {
      String _plus = (this.targetName + " @ ");
      _xifexpression = (_plus + this.version);
    }
    return _xifexpression;
  }
}
````

Version info:
Eclipse 4.8.0 (Photon) Build id: 20180619-1200
org.eclipse.xtend (2.2.0.v201605260315) "Xtend Core" [Resolved]
org.eclipse.xtend.core (2.14.0.v20180523-0530) "Xtend Core" [Active]
org.eclipse.xtend.doc (2.14.0.v20180523-0530) "Xtend Documentation" [Starting]
org.eclipse.xtend.examples (2.14.0.v20180523-0530) "Xtend Examples" [Starting]
org.eclipse.xtend.ide (2.14.0.v20180523-0530) "Xtend IDE" [Active]
org.eclipse.xtend.ide.common (2.14.0.v20180523-0530) "Xtend IDE Common" [Active]
org.eclipse.xtend.lib (2.14.0.v20180522-1629) "Xtend Runtime Library" [Resolved]
org.eclipse.xtend.lib.macro (2.14.0.v20180522-1629) "Xtend Macro Interfaces" [Resolved]
org.eclipse.xtend.m2e (2.14.0.v20180523-0530) "Xtend m2e Integration" [Resolved]
org.eclipse.xtend.standalone (2.14.0.v20180523-0530) "Xtend Standalone Bundle" [Resolved]
org.eclipse.xtend.typesystem.emf (2.2.0.v201605260315) "Xtend EMF Typesystem" [Resolved]

**Comment by cdietrich** [comment]
precedence issue/feature. + has a higher precedence than else

**Comment by cdietrich** [comment]
we already have a issue on that somewhere but i cannot find it right now

**Comment by enikao** [comment]
Ok thanks. For reference, I guess enclosing in parenthesis is the proper workaround/solution:

````xtend
class InvalidConcat {
	var Object target
	var String targetName
	var String version
	
	override toString() {
		(if (target !== null) {
			target.toString
		} else {
			targetName
		}) + ' @ ' + version
	}
}
````
