### ISSUE TITLE
Fix Xtend code completion proposal when hovering on '<<', '<<<', '>>', and '>>>'

### ISSUE THREAD

**Issue by psuzzi** [eclipse/xtext-xtend#561]
When I type : 
```
REPORT >>> 'A string'
```
And I hover the mouse on the '>>>' operator, I get the code completion suggestion to generate a method named ```operator_greaterThan```.

I expect to be suggested to generate a method named ```operator_tripleGreaterThan ```

![image](https://user-images.githubusercontent.com/352831/45107375-b142d700-b139-11e8-843d-ff20365bf4e0.png)

A similar issue happens for the code completion proposal when hovering on all the following operators: `<<`, `<<<`, `>>`, and `>>>`.

**Comment by szarnekow** [comment]
See org.eclipse.xtend.ide.quickfix.CreateMemberQuickfixes.getOperatorMethodName(XAbstractFeatureCall). Here we use only the first leaf node, but the operator is a data type rule thus we should use all non-hidden leafs to compose the entire operator name.

**Comment by cdietrich** [comment]
Fixed in 2.16
