### ISSUE TITLE
Xtend JavaDocContentAssistTest test cases are failing on Windows

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#571]
![screenshot](https://user-images.githubusercontent.com/20393472/45585219-3cae2c00-b8e1-11e8-8926-a9267fbe2e22.png)

The usage of the ContentAssistProcessorTestBuilder.assertTextAtCursorPosition(int cursorPosition, String... expectations) method with an absolute cursor position in combination with Xtend multiline Strings leads to different actual cursor positions in Windows and in Linux due to the different line delimiters.That's why the Xtend JavaDocContentAssistTest test cases are currently failing on Windows, since the absolute cursor positions are tailored to Linux style line endings.

To make the tests pass on both platforms, I suggest the usage of explicit cursor position markers similar to the [StatemachineContentAssistTest](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineContentAssistTest.xtend) and [RuleEngineContentAssistTest](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/src/org/eclipse/xtext/example/homeautomation/ui/tests/RuleEngineContentAssistTest.xtend) test cases.

**Comment by miklossy** [comment]
Since the PR has already been merged, this issue can be closed. Thx @kthoms

**Comment by kthoms** [comment]
Thank YOU, @miklossy !
