### ISSUE TITLE
[build] Eliminate snapshots repository

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-xtend#58]
The snapshots repository should be eliminated from Gradle builds on Jenkins

**Comment by spoenemann** [comment]
What we need to do here: Replace usage of xtext.juni4 classes by the new xtext.testing

**Comment by cdietrich** [comment]
what about the stuff that is not in testing?

**Comment by spoenemann** [comment]
I would duplicate it (copy from xtext.junit4 to xtend.core.tests)

**Comment by cdietrich** [comment]
ok so more duplicate instead of less

**Comment by spoenemann** [comment]
I see the following possible solutions:

 * Keep the dependency to xtext.junit4. That would require us to deploy that bundle into the local Maven repo of the xtext-eclipse build, which I would like to avoid, since all other artifacts of xtext-eclipse are consumed via its p2 repo.
 * Drop support for IntelliJ IDEA for Xtend. Then we wouldn't need the Gradle build anymore, and all dependencies can be resolved via p2.
 * Duplicate the required classes from xtext.junit4. We regard that bundle as deprecated, so it's good if we can reduce its usage in our own code base. I don't see any problems with the duplication, since we are not going to change that code anyway.

**Comment by cdietrich** [comment]
what about moving parts of the tests to ide.tests?

**Comment by spoenemann** [comment]
What's left do do: eliminate dependencies to `org.eclipse.xtext.xbase.junit`

**Comment by cdietrich** [comment]
@spoenemann i will have a look
