### ISSUE TITLE
XtendBatchCompiler: -bootclasspath arg invalid on Java 9+

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#582]
The XtendBatchCompiler does not consider the compliance level when adding `bootclasspath` to command line args. The argument is only allowed for Java 8 and older.

https://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html

**Comment by cdietrich** [comment]
@kthoms is this fixed ?

**Comment by kthoms** [comment]
Yes.
