### ISSUE TITLE
Xtend Standalone

### ISSUE THREAD

**Issue by sirolf2009** [eclipse/xtext-xtend#591]
I want to use xtend in a project of mine and I've been looking for a compiler. I've found this standalone xtend library, but it's only for version 2.4.1, while the current xtend version is 2.16.0. Is this library no longer active? Can I find a compiler somewhere else?

http://build.eclipse.org/common/xtend/maven/org/eclipse/xtend/org.eclipse.xtend.standalone/

**Comment by cdietrich** [comment]
You should find all you need in xtend.core 

Is there any reason not to use gradle maven or ant

**Comment by sirolf2009** [comment]
Mostly for hackability, but I also found that xtend compiles a lot faster in eclipse than in maven. I figured it had something to do with caching so I wanted to go rooting in the compiler code to see if I can trace what causes difference.

Cheers
