### ISSUE TITLE
Xtend Lambdas casted to a functional interface should generate the appropriate Java 8 Lambda

### ISSUE THREAD

**Issue by dcardin** [eclipse/xtext-xtend#60]
As discussed on the forum:  [https://groups.google.com/forum/#!topic/xtend-lang/aGcEg92XzjA](url)

I use introspection to get a method to

`addPropertyChangeListener(String name, PropertyChangeListener listener)`

When I do the invocation, I thought I could do 

`method.invoke(object, name, [ // some code ])`

As is stands, because the type for the parameters are all Object, there is no conversion and it's a Procedure1 that is passed. I can understand that logic of course.

So I decide to do :

`method.invoke(object, name, [ // some code ] as PropertyChangeListener)`

That works. But looking at the generated code, I was disappointed. There is an anonymous class instantiated there instead of simply using a java 8 (yes, it's java 8) lambda.

I would have expected to see

```
method.invoke(object, name, (PropertyChangeEvent it) -> {
          // some code
        });

```

Well, a simple declaration like

`val listener = [ .. ] as PropertyChangeListener` results in the old java<8 style of lambda.

However, a method call expecting a PropertyChangeListener does the conversion appropriately.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
