### ISSUE TITLE
Xtend no longer works with java 6 / 7 (dependency issue)

### ISSUE THREAD

**Issue by MarkRx** [eclipse/xtext-xtend#601]
It seems xtend no longer natively supports java 6 & 7 due to a transitive dependency issue. Out of the blue all of our builds have started failing.

Stacktrace:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':generateXtext'.
. . .
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/compiler/batch/CompilationUnit : Unsupported major.minor version 52.0
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
. . .
```

I have tracked it down to a transitive dependency being pulled in that was compiled with a target of Java 8.

org.eclipse.xtext:*:2.9.1
depends on org.eclipse.emf:org.eclipse.emf.ecore:(2.8,3.0). This resolves to version 2.15.0.
depends on org.eclipse.platform:org.eclipse.core.runtime:[3.6.0,4.0.0). This resolves to 3.15.0.
org.eclipse.platform:org.eclipse.core.runtime:3.15.0 was built with Java 8. It was published in September 2018 - [Eclipse EMF Ecore](https://mvnrepository.com/artifact/org.eclipse.emf/org.eclipse.emf.ecore/2.15.0)

Annoyingly our only options are to pin versions or upgrade Java. Probably not much that can be done here but I figured I would report it in case someone else ran into it.

**Comment by cdietrich** [comment]
https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2018/05/23/version-2-14-0

Unfortunately Xtext versions prior to 2.15 had these death ranges that auto pull ne platform emf etc.

**Comment by MarkRx** [comment]
Here is a workaround that works with the xtext-gradle-plugin version 1.0.14. It inserts the java 6 versions of the libraries at the front of the classpath for the generateXtext task. This causes java to load the java 6 versions of the eclipse jdt classes since they come first.

```
configurations {
    hotfix
}

dependencies {
    hotfix 'org.eclipse.jdt:org.eclipse.jdt.core:3.7.1'
}

xtext.version = '2.9.1'
generateXtext.xtextClasspath = configurations.hotfix.plus(generateXtext.xtextClasspath)
```

**Comment by MarkRx** [comment]
The issue is actually with the compiler - I do not believe the runtime libraries themselves suffer from the death ranges. While we were able to work around this by setting the JDK to java 7 and pinning our java version to java 6 (we don't know why) that workaround broke last week (perhaps due to the release of JDT core 3.16.0)

Here is a workaround that works with the xtext-gradle-plugin version 1.0.14. It inserts the java 6 versions of the libraries at the front of the classpath for the xtext generator tasks. This causes java to load the java 6 versions of the eclipse jdt classes since they come first.

```
configurations {
    hotfix
}

dependencies {
    hotfix 'org.eclipse.jdt:org.eclipse.jdt.core:3.10.0'
}

generateXtext.xtextClasspath = configurations.xtexthotfix.plus(generateXtext.xtextClasspath)
generateTestXtext.xtextClasspath = configurations.xtexthotfix.plus(generateTestXtext.xtextClasspath)
```

Edit: This is not working as expected... we are still investigating other approaches...
