### ISSUE TITLE
Lambas are validated twice

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext-xtend#614]
Ok:
<img width="528" alt="screen shot 2018-10-18 at 12 16 05" src="https://user-images.githubusercontent.com/375492/47147999-c29e0800-d2cf-11e8-965c-6f6e99068ccd.png">

Not Ok:

<img width="606" alt="screen shot 2018-10-18 at 12 16 12" src="https://user-images.githubusercontent.com/375492/47147991-bdd95400-d2cf-11e8-88c2-37963a5ab7b1.png">

Same with the `!=` operator but not shown twice for broken method references

**Comment by cdietrich** [comment]
This is not a quickfix problem. it's a validator problem.

**Comment by cdietrich** [comment]
org.eclipse.emf.ecore.util.Diagnostician.validate(EObject, DiagnosticChain, Map<Object, Object>) end beeing circular

**Comment by cdietrich** [comment]
here the validator object call chain

```
XClosure
XBlockExpression
XBinaryOperation
XFeatureCall
XNullLiteral
JvmFormalParameter
JvmParameterizedTypeReference
XBlockExpression
XBinaryOperation
```

**Comment by cdietrich** [comment]
@szarnekow is it possible the implicitFormalParameters is traversed and goes to the body again?

**Comment by cdietrich** [comment]
i think we had changed this code during our hamburg workshop

**Comment by szarnekow** [comment]
Yes, but apparently we missed an important detail in https://github.com/eclipse/xtext-extras/commit/f621cb5ed6a27320f619c4dc0185fadcaa3dc00c#diff-d03af8b70bcedad15e6b5b70e578de47.

I assume the super call should have gone into the doValidateLambdaContents.

**Comment by szarnekow** [comment]
Even better: If we constrain the used EMF version to be more up to date, than we can safely assume that the implicit derived containment object is either always automatically visited, or always skipped. The code can be simplified a lot, I suppose.

**Comment by cdietrich** [comment]
@szarnekow lets have a look

**Comment by szarnekow** [comment]
Fixed
