### ISSUE TITLE
Fix Idea tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#62]
http://services.typefox.io/open-source/jenkins/job/xtext-xtend/job/master/107/

**Comment by cdietrich** [comment]
@akosyakov do you have an idea what happens here?
how shall the facet be registered with the tests?

**Comment by spoenemann** [comment]
See also #11.

**Comment by cdietrich** [comment]
TODO:

reenable tests, reenable test collection in Jenkinsfile
