### ISSUE TITLE
Quickfix for triple-equals should be a multifix

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#620]
At the moment warnings of type "The operator '!=' should be replaced by '!==' when null is one of the arguments." can be only fixed one by one. It should be possible to select many of them and fix all.

**Comment by fabtagon** [comment]
Same for "private modifier is unnecessary"

**Comment by miklossy** [comment]
@fabtagon The unnecessary modifiers validation should be already fixed by multi quickixes, see https://blogs.itemis.com/en/xtend-2-14-unnecessary-modifiers-validation

Do you have a conrete example where it does not work?

**Comment by kthoms** [comment]
The „unnecessary modifier“ quick fix works well as multifix. And otherwise it should be another issue reported anyway.

**Comment by cdietrich** [comment]
Fixed in 2.16
