### ISSUE TITLE
xtendc compiler (feature request)

### ISSUE THREAD

**Issue by shumy** [eclipse/xtext-xtend#63]
This is a ticket from a follow google groups post: https://groups.google.com/forum/#!topic/xtend-lang/OMSN_IKHqbY

Propose to have xtend compiler and compiler options, and also a file for compiler options like e.g in TypeScript. This will be useful for other compile dependency features.

**Comment by chrswk** [comment]
What's the use case and how would this add value to Xtend? I would guess 99% of Xtend developers use the official Maven or Gradle plugins for their automated builds. I also don't understand why your other issues depend on having a "xtendc" compiler. The existing Maven/Gradle plugins already support various parameters.

**Comment by gallandarakhneorg** [comment]
Within the [SARL](http://www.sarl.io) project, which is inspired by and extends a part of the Xtend features, we have created a command-line compiler for helping our users to do compilation on specific environments without Maven or Graddle, and without network connection. Installing by hand all the Maven plugins on the computer is annoying, even if possible. Having a standalone command line compiler (only one file to download) is easier for the developers.

My point is: the add value is not to the language, but to the potential increasing of the Xtend compiler uses on heterogeneous compilation environments.

If it may help someone to write the code of this xtendc compiler, I have the following running example.
* I have created a [batch compiler dedicated to SARL](https://github.com/sarl/sarl/blob/master/main/coreplugins/io.sarl.lang/src/io/sarl/lang/compiler/batch/SarlBatchCompiler.java) by copy/pasting and adapting the Xtend batch compiler.
* I have created a [Main class](https://github.com/sarl/sarl/blob/master/main/coreplugins/io.sarl.lang/src/io/sarl/lang/compiler/batch/Main.java) that exhibit the main function and managing the command-line options, and
* I have written a maven module for [generating the binaries](https://github.com/sarl/sarl/tree/master/products/sarlc) for the major OS (sarlc, sarlc.exe, sarl.app).

**Comment by cdietrich** [comment]
close as wont fix. feel free to recreate at github.com/eclipse/xtext
