### ISSUE TITLE
Remove redundant modifier quickfix removes also comments

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#631]
Consider this class
```
package test

class Foo {
    // Please keep me!
    private String bar 
    def static void main(String[] args) {
    	
    }
}
```

When the `private` keyword is removed by applying the quickfix, also the comment above is removed.

**Comment by kthoms** [comment]
@miklossy Could you take this?

**Comment by cdietrich** [comment]
dupes https://github.com/eclipse/xtext/issues/2306
