### ISSUE TITLE
Fix Build Issues with Scheduling rules

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#639]
```
Fehlermeldung

Attempted to beginRule: MultiRule[P/first.p384008,P/.org.eclipse.jdt.core.external.folders], does not match outer scope rule: MultiRule[P/first.p384008,P/second.p384008,P/test.project] - See error log for details, The type A is already defined in B.xtend., Attempted to beginRule: MultiRule[P/first.p384008,P/.org.eclipse.jdt.core.external.folders], does not match outer scope rule: MultiRule[P/first.p384008,P/second.p384008,P/test.project] - See error log for details expected:<1> but was:<3>

Stacktrace

java.lang.AssertionError: Attempted to beginRule: MultiRule[P/first.p384008,P/.org.eclipse.jdt.core.external.folders], does not match outer scope rule: MultiRule[P/first.p384008,P/second.p384008,P/test.project] - See error log for details, The type A is already defined in B.xtend., Attempted to beginRule: MultiRule[P/first.p384008,P/.org.eclipse.jdt.core.external.folders], does not match outer scope rule: MultiRule[P/first.p384008,P/second.p384008,P/test.project] - See error log for details expected:<1> but was:<3>
	at org.eclipse.xtend.ide.tests.validation.UniqueClassNameValidatorUITest.testTwoXtendFilesSameProject(UniqueClassNameValidatorUITest.java:65)

```

**Comment by cdietrich** [comment]
c @kthoms

**Comment by cdietrich** [comment]
can be reproduce locally when adding

`-pluginCustomization /data/xtext-master/git/xtext-xtend/releng/org.eclipse.xtend.tycho.tests.parent/pluginCustomization.ini` to launch config

**Comment by cdietrich** [comment]
```
	@Override
	public ISchedulingRule getRule(int kind, Map<String, String> args) {

		switch (preferences.schedulingOption) {
			case NULL:
				return null;
			case WORKSPACE:
				return getProject().getWorkspace().getRoot();
			case PROJECT:
				return getProject();
			case ALL_XTEXT_PROJECTS: {
				IProject implicitProject = getProject().getWorkspace().getRoot().getProject(".org.eclipse.jdt.core.external.folders");
				Stream<IProject> implicit = Stream.of();
				if (implicitProject != null) {
					implicit = Stream.of(implicitProject);
				}
				return new MultiRule(Stream.concat(Arrays.stream(getProject().getWorkspace().getRoot().getProjects()).filter(p -> {
					return XtextProjectHelper.hasNature(p) || ".org.eclipse.jdt.core.external.folders".equals(p.getName());
				}), implicit).toArray(ISchedulingRule[]::new));
			}
			default:
				throw new IllegalArgumentException();
		}
	}
```
is there more implicit dependencies?
what is there are explicit deps from Xtext projects to non Xtext Projects?

**Comment by kthoms** [comment]
Java Builder relaxed rule:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=531554

Open bug with similar error:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=477827

**Comment by kthoms** [comment]
The exception is produced here:
org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ISchedulingRule, ISchedulingRule)

There is also a test case:
org.eclipse.core.tests.runtime.jobs.BeginEndRuleTest.testFailedNestRuleInJob()

**Comment by cdietrich** [comment]
investigation result so far:

- xtend generation changes classpath and want to add a source folder for xtend-gen to classpath (SetClasspathOperation)
- the test directly calls project.build => baserule in org.eclipse.core.internal.jobs.ThreadJob.push(ISchedulingRule) is the first non null = the one of the project => it misses the external folder one that is added by org.eclipse.jdt.internal.core.SetClasspathOperation.getSchedulingRule()
- in a normal clean build baserule seems to be the workspace rule of the auto build job
- adding the .external project to the xtext scheduling group seems to help.
- same for changing the test and wrap the build into a workspace operation 
```
ResourcesPlugin.workspace.run(new IWorkspaceRunnable() {
				
				override run(IProgressMonitor monitor) throws CoreException {
					first.build(IncrementalProjectBuilder.INCREMENTAL_BUILD, XtextBuilder.BUILDER_ID, emptyStringMap, null)
				}
				
			}, new NullProgressMonitor)
```
we need your expertise with this problem

**Comment by szarnekow** [comment]
Does the XtextProjectHelper.hasNature(p) also ignore closed projects?

**Comment by iloveeclipse** [comment]
> same for changing the test and wrap the build into a workspace operation

Sounds good.

**Comment by kthoms** [comment]
> same for changing the test and wrap the build into a workspace operation

Would this mean that the XtextBuilder would run with Workspace Root rule always? That is actually what we want to relax.

> adding the .external project to the xtext scheduling group seems to help.
Sounds like the better option to me.

**Comment by cdietrich** [comment]
no the autobuild job does (its the baserule in what i have debugged). => needs deeper understanding (and maybe run against 2018-12

**Comment by cdietrich** [comment]
@kthoms is there anything left?

**Comment by kthoms** [comment]
I think we are done here.
