### ISSUE TITLE
[Maven] Solve Deprecation in Xtend-Maven-Plugin

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#646]
there are deprecation warnings on the codebase of the xtend-maven-plugin. these should be addressed

**Comment by cdietrich** [comment]
with the drop of Java 8 support i guess we can also drop the deprecated code

**Comment by cdietrich** [comment]
as we are now at defact minimal java 11, we might simply remove the boot classpath treatment
@szarnekow what do you think?

**Comment by szarnekow** [comment]
Yes, we should do that.

**Comment by cdietrich** [comment]
done
