### ISSUE TITLE
map files for base lib configuration

### ISSUE THREAD

**Issue by shumy** [eclipse/xtext-xtend#65]
This is a ticket from a follow google groups post: https://groups.google.com/forum/#!topic/xtend-lang/OMSN_IKHqbY

Dependent on [#63](https://github.com/eclipse/xtext-xtend/issues/63) and [#64](https://github.com/eclipse/xtext-xtend/issues/64) resolution.
If possible, build map files for optional base libraries, defining the generation mapping, so that we can tell the compiler what to do with:

``` java
val list = #[1, 2, 3]
//can generate in javaslang:
List<Integer> list = List.of(1, 2, 3);
```

Other features in this config can be:
1. implicit imports
2. additional maven/gradle dependencies

**Comment by cdietrich** [comment]
close as wont fix. feel free to recreate at github.com/eclipse/xtext
