### ISSUE TITLE
Xtend IDE: Implement Quickfix to the 'unused private member' validation issue

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#671]
The Xtend IDE should provide a Quickfix that removes the `unused private member`:
![screenshot](https://user-images.githubusercontent.com/20393472/49875934-8811a100-fe22-11e8-9f5c-6bc88dbea5ea.png)

**Comment by szarnekow** [comment]
Also for local vars

**Comment by miklossy** [comment]
Fixed in 2.17.
