### ISSUE TITLE
Semicolon after 'return' not optional for void functions

### ISSUE THREAD

**Issue by fabtagon** [eclipse/xtext-xtend#678]
In Xtend, semicolon after statement (if followed by line break) is generally optional.

```Xtend
def int test(int a) {
	if (a == 1)
		return 1
	System.out.println("foo")
	return 42
}
```
=> works

This does not work for the `return` statement with functions returning void.

```Xtend
def void test(int a) {
	if (a == 1)
		return // notice there is no semicolon here
	System.out.println("foo")
}
```
=> gives error "Void functions cannot return a value."

```Xtend
def void test(int a) {
	if (a == 1)
		return; // notice the semicolon at the end of the line
	System.out.println("foo")
}
```
=> works

This issue is more language cosmetics and not a big deal.

**Comment by cdietrich** [comment]
i dont see how this can be solved.

how does that code syntactially differ from

```
def void test(int a) {
	if (a == 1)
		return 
	System.out.append('c')
}

which returns a printstream
```
