### ISSUE TITLE
Unexpected "Invalid return inside throw."

### ISSUE THREAD

**Issue by heeckhau** [eclipse/xtext-xtend#68]
Unexpected Xtend compilation error with the Xtend 2.11.0.v20161021-1107 beta for this class:
```
class Bug {
	private static final class MyException
	 extends Exception {
		protected static final long serialVersionUID = -2525515069696151557L;

		override synchronized Throwable fillInStackTrace() {
			return this; // Unexpected error here "Invalid return inside throw."
		}
	}
}
```

**Comment by cdietrich** [comment]
@LorenzoBettini is this connected to your change?

**Comment by LorenzoBettini** [comment]
I'm afraid so (https://github.com/eclipse/xtext-extras/pull/25): I was checking whether there was a Throwable expectation and I did not consider that such an expectation could come from a return type (https://github.com/eclipse/xtext-extras/pull/25/commits/ced8f3f2c62ac81df52be33448918783501c125b#diff-b6005bcf142bb45a1aa34ebbf02404d7R1005).
Actually my PR was applied to Xbase where I could not write a test using a return type in a method.
I think this could be fixed by also checking whether the expression is contained in a throw expression, besides checking for a Throwable expectation.

**Comment by LorenzoBettini** [comment]
I'll try to fix it now...
in the meantime, removing "return" should solve the issue, right @heeckhau ?

**Comment by svenefftinge** [comment]
@LorenzoBettini we should have tests for that case.
I currently don't have the time to look at this in more depth, but the quality of containment is not the same. E.g. your check would also be passed by this I think:

```
throw {
     val Provider<String> foo = [ return "dfg" ]
     new Exception(foo.get)
}
```

Not really idiomatic code, but still ... :)

**Comment by heeckhau** [comment]
Removing the `return` keyword indeed solves the issue,

**Comment by LorenzoBettini** [comment]
@svenefftinge you're right!

But then it should be enough to walk up the containment hierarchy manually and stop either when the container is a lambda (and that would be OK) or when it is a throw (and that would be an ERROR).

I don't know if it was also worthwhile to let developers define their concept of "return consumer": by default it would be a lambda, but, e.g., in Xtend, you could even stop as soon as the container is an Xtend method.

Walking up the containment hierarchy might also be expensive, but in the check we do that only if the expectation is a Throwable.

**Comment by LorenzoBettini** [comment]
@svenefftinge actually the code you mentioned is considered valid; did you mean that it should not be considered valid? The code is compiled fine and also in Java it is compiled fine.

Indeed the check for the containment is done ONLY if there's a throwable expectation (https://github.com/eclipse/xtext-extras/pull/69/commits/7eebabc811e83ce55dab0edc847f53860de1eb16#diff-b6005bcf142bb45a1aa34ebbf02404d7R996), while in the code you mentioned the return expression has no Throwable expectation in the type computation state, thus the containment is not checked at all.

Also this code is still valid:

```
throw {
	val ()=>Exception foo = [|return new Exception]
	foo.apply
}
```

I also added a few test cases in the PR https://github.com/eclipse/xtext-extras/pull/69 (https://github.com/eclipse/xtext-extras/pull/69/commits/4de97993cc102456e5cf453885e1cf801963f2c2)

Did I miss something or misunderstand your comment?

**Comment by LorenzoBettini** [comment]
@svenefftinge can you please have a look at my comments?
