### ISSUE TITLE
Xtend 2.13 stopped working

### ISSUE THREAD

**Issue by naraesk** [eclipse/xtext-xtend#680]
We use Xtend 2.13. Until 2018-11-16 our project has been build successfully, on multiple local machines as well as on the build server (Codeship). However, since then all builds are failing without any change in the codebase. Plus, we cannot reproduce the old builds, neither locally nor with Codeship. The code is managed by the build server, so it is definitely the same code that worked fine some weeks ago. As far as I can tell the only thing changed is the version of maven from 3.3.x to 3.5.x. However, downgrading maven to the old version didn't change anything.

I've attched a [minimale example](https://github.com/eclipse/xtext-xtend/files/2733583/example.zip) and the corresponding [maven output](https://github.com/eclipse/xtext-xtend/files/2733626/example.log). 

With version 2.16.0 the minimal example works fine again. But I cannot simple do this for our project since there are other runtime errors for this version. But this is another issue.

**Comment by cdietrich** [comment]
likely duplicates https://github.com/eclipse/xtext/issues/1373

**Comment by naraesk** [comment]
Thanks for the hint. The proposed workaroud didn't work but using xtend 2.15 seems to work.

How can we prevent such a problem in the future? One of the main goals for using a build system as maven is to have reproducible builds. That a build is succussful but fails some weeks later should not happen at all. Xtend 2.13 is exactly the same as it was 5 weeks ago, isn't it? So is this problem really caused by the maven version? Or is our pom.xml not explicit enough so another version of a dependency has been used somehow?

**Comment by cdietrich** [comment]
i tried it and it worked for me with the workaround.
so can you provide your example **with** the workaround inplace

**Comment by cdietrich** [comment]
[example_withworkaround.zip](https://github.com/eclipse/xtext-xtend/files/2737244/example_withworkaround.zip)

**Comment by naraesk** [comment]
Indeed, this works. Sorry, must have mixed something up. So this can be closed. Thanks for your help. :)
Still, would be nice and helpful if you could explain what's going on and why it was working before.
