### ISSUE TITLE
Typos in the Xtend IssueCodes

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#684]
There are some typos in the Xtend validation issue code declarations:

- [public static final String ORPHAN_ELMENT](https://github.com/eclipse/xtext-xtend/blob/08a9557e94dbaf63bdc53748a40173edcc946412/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java#L100)
- [public static final String ACTIVE_ANNOTAION_IN_SAME_CONTAINER](https://github.com/eclipse/xtext-xtend/blob/08a9557e94dbaf63bdc53748a40173edcc946412/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java#L102)

I wonder if we are allowed to rename the fields directly or if we should introduce new variables with the right names and make the other ones deprecated.

**Comment by cdietrich** [comment]
Xtend is no API so change
cc @gallandarakhneorg

**Comment by miklossy** [comment]
Ok, I see. I merged your PR. Thx @gallandarakhneorg !

**Comment by miklossy** [comment]
Fixed in 2.17
