### ISSUE TITLE
XtendCompilerMojoIT tests failing: Unresolvable Guava version

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#688]
Tests [failing](https://ci.eclipse.org/xtext/job/xtext-xtend/job/bootstrap_2.17.0.M1/1/testReport/) on changing bootstrap Xtext version:
- `org.eclipse.xtend.maven.XtendCompilerMojoIT.macro`
- `org.eclipse.xtend.maven.XtendCompilerMojoIT.aggregation`

Similar issue was observed when building 2.17.0.M1.

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.google.guava:guava:jar:22.0-rc1-android in central-real (file:///home/hudson/genie.xtext/.jenkins/jobs/xtext-xtend/branches/bootstrap-2-17-0-M1.2jh1pb/workspace/.m2/repository)```

The local maven repository contains a range of Guava versions from 14.0 to mentioned 22.0-rc1-android, but only metadata is contained in the local repository. The only version which contains a jar is 21.0

**Comment by kthoms** [comment]
We decided to restrict Guava to version 21.0 for Maven/Gradle builds in the BOM. This will avoid pulling the version range.

**Comment by cdietrich** [comment]
lets see if build on master is green too now

**Comment by kthoms** [comment]
fixed
