### ISSUE TITLE
Issue with a enum default attribute in java annotation

### ISSUE THREAD

**Issue by alexanzer** [eclipse/xtext-xtend#690]
Hi,
I have following code:

TestAnnotation.java
```
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface TestAnnotation {
	TestEnum testEnum() default TestEnum.ONE;
}
```

And xtend files

```
enum TestEnum {
	ONE, TWO;
}
```

```
@TestAnnotation
class HelloWorld {
	def static void main(String[] args) {
		println('Hello World!')
	}
}
```

When I use the annotation in xtend class, I get the error: _The annotation must define the attribute 'testEnum'_. But this parameter have default value.

**Comment by cdietrich** [comment]
we dont support type annotations yet https://github.com/eclipse/xtext/issues/2360
