### ISSUE TITLE
[xtend-maven-plugin][java11] Maven plugin fails to compile Xtend files when present in same folder as Java files

### ISSUE THREAD

**Issue by ghillairet** [eclipse/xtext-xtend#697]
Xtend maven plugin version: 2.16.0
Java version: OpenJDK 11.0.2

Steps to reproduce:
- Create a maven project with xtend and maven plugin dependencies
- Create a Java class in `src/main/java`
- Create an Xtend class in `src/main/java` that references the Java class
- Run `mvn clean install`

This results in a compilation error saying that a method from the Java class refers to the missing type Object.

This can be fixed if the Xtend class is moved to `src/main/xtend`. This seems to be an issue only with Java 11 and not prior Java versions.

**Comment by kthoms** [comment]
Xtend 2.16 does and will not support Java 11. This is planned for 2.17.

**Comment by ghillairet** [comment]
@kthoms Is that even if the source and target are set to 1.8 but maven is running on Java 11? That's actually the case in this issue that I forgot to mention.

**Comment by cdietrich** [comment]
well yes and no.on non mac it will accidentally work

**Comment by ghillairet** [comment]
Ok thanks.

**Comment by cdietrich** [comment]
can you share a minimal example @ghillairet 
so that i can test with our java 11 branch

**Comment by kthoms** [comment]
Then let's reopen it.

**Comment by ghillairet** [comment]
@cdietrich Here is my example https://github.com/ghillairet/xtend-java11

**Comment by cdietrich** [comment]
can you test with 
```
<repositories>
		<repository>
			<id>codehaus-snapshots</id>
			<name>disable dead 'Codehaus Snapshots' repository, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=481478</name>
			<url>http://nexus.codehaus.org/snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>x211</id>
			<url>https://projects.itemis.de/nexus/content/groups/xtext_java11/</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>codehaus-snapshots</id>
			<name>disable dead 'Codehaus Snapshots' repository, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=481478</name>
			<url>http://nexus.codehaus.org/snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>x211</id>
			<url>https://projects.itemis.de/nexus/content/groups/xtext_java11/</url>
		</pluginRepository>
	</pluginRepositories>

```

and `<version>2.17.0-SNAPSHOT</version>`

**Comment by ghillairet** [comment]
@cdietrich It's working as expected with `2.17.0-SNAPSHOT`.

**Comment by cdietrich** [comment]
Fixed in Xtext/Xtend 2.17

**Comment by georgschmidtdumont** [comment]
Good morning @cdietrich,

I upgraded from Java 8 to Java 11 yesterday and unfortunately ran into this problem as well. I am using Xtext/Xtend 1.19.
I did check out the example from @ghillairet, but unfortunately when I build that project using Java 11 it fails to compile as well.

Can you please look into this again? If required I can provide a small sample of my own.

Thanks!

**Comment by cdietrich** [comment]
@georgschmidtdumont i currently have no time to create and debug an example.
please provide yours

**Comment by cdietrich** [comment]
p.s.:

https://github.com/ghillairet/xtend-java11

works perfectly fine with Xtext/Xtend 2.19

**Comment by georgschmidtdumont** [comment]
Hi @cdietrich,
building my own sample revealed the error of my ways. We still had the workaround for the xText issue [1231](https://github.com/eclipse/xtext/issues/1231) in the project where I am updating Java. This caused the compilation problems.

Thanks for your quick response!
