### ISSUE TITLE
Refactor Xtend Mojos to use annotations

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#704]
Mojos in module org.eclipse.xtend.maven.plugin are using old style javadoc annotations for configuration of the Mojo. This should be changed to use Maven Annotations, like it was [done for xtext-maven-plugin](https://github.com/eclipse/xtext-maven/pull/69).

**Comment by cdietrich** [comment]
@kthoms is this a duplicate of https://github.com/eclipse/xtext-xtend/issues/469
