### ISSUE TITLE
[xtend-maven-plugin] The feature 'feature' ... contains a dangling reference ... 

### ISSUE THREAD

**Issue by matthiashanns** [eclipse/xtext-xtend#708]
I have a small xtend class with an JTree and an event handler. The xtend code compiles fine in Eclipse (Eclipse-2018-12, Xtend 2.16) but fails when building by the xtend-maven-plugin:2.16.0. Java is version 1.8.

The error message is:

ERROR:  WindowExample.xtend - D:\Work\example\src\main\java\example\WindowExample.xtend
78: The feature 'feature' of 'org.eclipse.xtext.xbase.impl.XFeatureCallImplCustom@738a39cc{file:/D:/Work/example/src/main/java/example/WindowExample.xtend#/0/@xtendTypes.0/@members.1/@expression/@expressions.1/@featureCallArguments.0/@arguments.0/@rightOperand/@expression/@expressions.1/@featureCallArguments.0/@members.0/@expression/@expressions.0/@right/@implicitReceiver}' contains a dangling reference 'org.eclipse.xtext.common.types.impl.JvmFormalParameterImplCustom@342723a3{#//}'

Please, see attached mini project to reproduce the issue.

Steps to reproduce:
1) Extract the zip.
2) Run "mvn install eclipse:eclipse". The build should be fine, the code line which triggers the issue is still commented out.
3) Import the project in Eclipse, clean, compile, run. The Swing frame shows a simple JTree.
4) Uncomment the lines 78 (and 79), line 78 triggers the build issue.
5) Clean and compile in Eclipse should still be fine.
6) Rebuild with maven "mvn clean install" now fails with the mentioned error.
[example.zip](https://github.com/eclipse/xtext-xtend/files/2833257/example.zip)

**Comment by matthiashanns** [comment]
Thanks, Christian. I already realized that using an explicit variable name instead of the implicit "it" compiles fine. Though this works as a workaround, I assume the issue itself is supposed not to exist. Additionally, I couldn't find a pattern when or why this issue came up. The class which I wrote first was more complex due to the Swing components, and I suspected the problem was because of its complexity which in the end turned out to be not the reason.

**Comment by szarnekow** [comment]
Is it the same EMF Version in Eclipse and with Maven?

**Comment by cdietrich** [comment]
@szarnekow yes the problem happens with latest greatest eclipse/xtext as well.
i dont see how this could be related to the emf version.

**Comment by szarnekow** [comment]
Maybe related to behavior of eAllContents with derived containment

**Comment by cdietrich** [comment]
at least back to emf 2.13 in oxygen 3a its working in eclipse
@szarnekow do you know when the behaviour in emf changed?

**Comment by matthiashanns** [comment]
Though the example to reproduce this issue has no direct requirement for EMF, the dependency management in the project sets the EMF version to 2.15.0.

```
            <dependency>
                <groupId>org.eclipse.emf</groupId>
                <artifactId>org.eclipse.emf.common</artifactId>
                <version>2.15.0</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.emf</groupId>
                <artifactId>org.eclipse.emf.ecore</artifactId>
                <version>2.15.0</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.emf</groupId>
                <artifactId>org.eclipse.emf.ecore.xmi</artifactId>
                <version>2.15.0</version>
            </dependency>
```

**Comment by cdietrich** [comment]
@matthiashanns not in the pom you shared

**Comment by matthiashanns** [comment]
@cdietrich I put this as a side note only. The project dependencies/dependency management doesn't matter. The plugin's dependencies weren't changed.

**Comment by cdietrich** [comment]
cannot be reproduce with latest greatest Xtext
