### ISSUE TITLE
Update Maven Archetypes

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#712]
The Maven archetypes need an update. They still use Java 1.5 and do not use the BOM. Also plugin management can be improved.

**Comment by cdietrich** [comment]
should we discontinue the android archetype?

**Comment by kthoms** [comment]
I doubt it is really in use. It would be no prob to do a bit maintenance, but I could also imagine that we can drop it. But should be decided in common sense.

**Comment by cdietrich** [comment]
the question: does it make sense to have an archetype for a gazillion years old android version
=> needs to be completely reset-up

**Comment by kthoms** [comment]
=> discuss in team

**Comment by szarnekow** [comment]
I think it is a sane choice to drop this archetype.

**Comment by kthoms** [comment]
drop = remove code also? if someone is interested, old versions are tagged.

**Comment by szarnekow** [comment]
> drop

yes

**Comment by kthoms** [comment]
+1; will include removal in my PR

**Comment by cdietrich** [comment]
@kthoms is this fixed now?

**Comment by cdietrich** [comment]
@kthoms what is the state of this issue?

**Comment by kthoms** [comment]
Done for 2.17
