### ISSUE TITLE
Optionally raise issue if class is named Abstract... but not declared abstract

### ISSUE THREAD

**Issue by epoell** [eclipse/xtext-xtend#719]
If a class is named Abstract.. there should be a warning to add the abstract keyword if missing

**Comment by kthoms** [comment]
Not sure if I like such name based heuristic. Sounds reasonable, though. What do orhers think?

**Comment by szarnekow** [comment]
I'd say classes names `AbstractZonk` should follow the principle of least surprise and be ... abstract. Don't you think so?

**Comment by cdietrich** [comment]
would be interesting at how many places we violate this.
and if we make this configurable and if yes with warning or ignore as default

**Comment by miklossy** [comment]
I would suggest to orient this to the corresponding [SonarQube rule](https://rules.sonarsource.com/java/tag/convention/RSPEC-118) and warning as default.

**Comment by szarnekow** [comment]
Thank you @epoell

**Comment by miklossy** [comment]
It seems there are some spaces missing from the validation issue message:
![screenshot](https://user-images.githubusercontent.com/20393472/53287237-9c0a4500-3779-11e9-934f-33407c042a1d.png)
I also encountered some typo in the ValidationIssue719QuickFixTest [add_abstract_annotation](https://github.com/eclipse/xtext-xtend/blob/7ee9933216f514387167646610bd2b451d4c914c/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/ValidationIssue719QuickFixTest.xtend#L136) test case: `@Depreciated` should be `@Deprecated`.
@epoell Could you please take care of these two points?

**Comment by miklossy** [comment]
Thx @epoell !

**Comment by epoell** [comment]
Thank you for the hint! :)
