### ISSUE TITLE
[xtend-maven-plugin]: External jar - cannot be resolved to a type

### ISSUE THREAD

**Issue by timeraider4u** [eclipse/xtext-xtend#72]
Dear all,
we are using the maven-dependency plug-in to download external libraries to a sub-directory called lib and we run `mvn clean test` for an Eclipse plug-in build with Eclipse Tycho. Xtend-maven fails to compile a .xtend file. xtend-maven-plugin:2.10.0:compile (default) complains with ... cannot be resolved to a type. However, when afterwards the same command is run again it runs through without problems. I have created an example project (see steps below).

Reproducable: Always

Steps to reproduce:
1.) `git clone https://github.com/timeraider4u/external_jar_download.git`
2.) `cd external_jar_download`
3.) `mvn clean test`

Results:
`[ERROR]
ERROR:  XtendExternal.xtend - /home/harry/workspace/external_jar_download/src/main/java/test/XtendExternal.xtend
3: org.apache.log4j.Logger cannot be resolved to a type.
[ERROR]
ERROR:  XtendExternal.xtend - /home/harry/workspace/external_jar_download/src/main/java/test/XtendExternal.xtend
7: Logger cannot be resolved to a type.
[ERROR]
ERROR:  XtendExternal.xtend - /home/harry/workspace/external_jar_download/src/main/java/test/XtendExternal.xtend
8: The method or field Logger is undefined
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE`

Expected results: build runs through successfully in the first run.

**Comment by cdietrich** [comment]
when running for the first time i get following in the log

```
[DEBUG] Dependency from /Users/dietrich/tmp/external_jar_download to nested classpath entry /Users/dietrich/tmp/external_jar_download/lib/log4j-1.2.16.jar can not be represented in Maven model and will not be visible to non-OSGi aware Maven plugins
```
when running for the second time i dont get this entry.

since the xtend maven plugin does not know anything about osgi but simply takes the maven classpath provided by tycho it cannot see this dependencies. 

thus i am not sure if we can fix this at all in xtend @spoenemann @svenefftinge @dhuebner what do you think.

i think the proper way is to tell tycho to consider pom dependencies

```
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho-version}</version>
				<configuration>
				<environments>
					<environment>
						<os>linux</os>
						<ws>gtk</ws>
						<arch>x86</arch>
						</environment>
						<environment>
						<os>linux</os>
						<ws>gtk</ws>
						<arch>x86_64</arch>
						</environment>
						<environment>
						<os>win32</os>
						<ws>win32</ws>
						<arch>x86</arch>
						</environment>
						<environment>
						<os>win32</os>
						<ws>win32</ws>
						<arch>x86_64</arch>
						</environment>
						<environment>
						<os>macosx</os>
						<ws>cocoa</ws>
						<arch>x86_64</arch>
						</environment>
					</environments>
					<pomDependencies>consider</pomDependencies>
				</configuration>
			</plugin>
```

and add a dependency to log4j

```
	<dependencies>
		<dependency>
			<groupId>org.eclipse.xtend</groupId>
			<artifactId>org.eclipse.xtend.lib</artifactId>
			<version>[2.4.9,)</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.16</version>
			<type>jar</type>
		</dependency>
	</dependencies>
```

**Comment by timeraider4u** [comment]
Well, thank you for your answer. Unfortunately, I am not getting this issue at all when simply using the Tycho compiler. E.g., try the following:
1.) git clone https://github.com/timeraider4u/external_jar_download.git
2.) cd external_jar_download
3.) cp pom-other.xml pom.xml 
(this will comment-out the xtend-maven plugin)
3.) mvn clean test
Now it will compile fine on the first run.

This way only src/main/java/test/JavaExternal.java is compiled (which uses Log4J the same way as the Xtend file does).

**Comment by cdietrich** [comment]
well the tycho compiler is NOT a "non-OSGi aware Maven plugin" and thus sees the real classpath but the xtend maven plugin does not

**Comment by cdietrich** [comment]
i called on tycho-user if they have a solution

**Comment by timeraider4u** [comment]
@cdietrich: Thank you very much!

**Comment by cdietrich** [comment]
from the tycho mailing list:

```

Hello,

if your dependency is copied during build process to the final location, the problem could be that tycho resolves these classpath entries only during initial computation of the target platform dependencies. 
So, if your jar is not checked out , it is not present physically but only be added as external dependency if nestedJarOrDir.isFile() is true in org.eclipse.tycho.core.maven.MavenDependencyInjector.newExternalDependencies(ArtifactDescriptor). 

So, to test this, just copy the dependency jar to the final location before maven starts and see if it works then. 

We had a similar problem with scala-compiler not picking up any nested jars which will be created during maven build runtime and therefore had to prefix maven builds with ANT/Groovy step to create 0 byte nested jars.
```

=> imho nothing we can do on xtend side

**Comment by kthoms** [comment]
I tested the issue as described. When the library is copied to lib _before_ Maven is executed, then the code is compiled successfully.
```
rm -rf target && rm lib/* && cp ~/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar lib && mvn -o test
```
So also from my perspective this is not an issue of Xtend, but rather from Tycho if at all. 

You could split your build into two Maven executions
```
mvn clean initialize
mvn test
```
This would succeed, but would take additional time for the target platform calculation.

**Comment by cdietrich** [comment]
since we cant do anything ill close it

**Comment by timeraider4u** [comment]
okay, thank you for asking on the Tycho mailing list.
