### ISSUE TITLE
XtendIDEInjectorProvider: Reset global state properly

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#734]
XtendIDEInjectorProvider must follow the same pattern for restoring registries like the generated IInjectorProviders do.

During 2.17.0.M3 we observed problems with Xtend tests that were traced down in xtext-eclipse to a similar problem.

**Comment by szarnekow** [comment]
In fact this applies to all generated UI injector providers. I'll provide a test case that illustrates the pattern.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-eclipse/issues/1020 too

**Comment by szarnekow** [comment]
Fixed
