### ISSUE TITLE
Overload elvis and safe navigation operators for Optional

### ISSUE THREAD

**Issue by ivaniesta14** [eclipse/xtext-xtend#743]
As `Optional`s are not meant to be used with `null`, it makes sense to overload the elvis operator `?:` to mean `orElse` (or potentially `orElseThrow` and `orElseGet` given the right arguments) and the safe navigation operator `?.` to relay the current chain of methods to the underlying object (roughly equivalent to `ifPresentOrElse`).
This behaviour should also be added to the `OptionalDouble`, `OptionalInt` and `OptionalLong`.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
