### ISSUE TITLE
Xtend Quickfix "Rename class" should be offered if the class name does not match the file name. 

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#744]
Currently, the Xtend IDE recognizes if the class name does not match the file name and reports a corresponding warning with a Quickfix to rename the file.
![screenshot](https://user-images.githubusercontent.com/20393472/53965223-111e3880-40f1-11e9-9f4d-63235e19096c.png)
 An additional Quickfix should also be offered to rename the class.

**Comment by Hanksha** [comment]
Hi, I worked on this (my first issue). I just need to figure out where to put the unit test for it.

![rename_class](https://user-images.githubusercontent.com/6960133/54168386-37552700-44a9-11e9-84ab-28912d476536.gif)

**Comment by cdietrich** [comment]
Fixed in 2.18
Thx @Hanksha

**Comment by miklossy** [comment]
I have just tested this feature with the latest Xtend and really like it.

@Hanksha @cdietrich Thank you again for your contributions!
