### ISSUE TITLE
Decide of the future of Caliper Tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-xtend#748]
From https://github.com/eclipse/xtext-core/issues/1077#issuecomment-473056013

> Caliper allows to serialize the performance test results as json and upload it to some server. We should drop the caliper tests and (if necessary) replace them by jmh tests.

**Comment by szarnekow** [comment]
These should be deleted.

**Comment by cdietrich** [comment]
Fixed in 2.18.
thx @szarnekow
