### ISSUE TITLE
Import static and static extension refactoring

### ISSUE THREAD

**Issue by Hanksha** [eclipse/xtext-xtend#751]
There is a feature in JDT `Source > Add Import (MOD1+SHIFT+M)` which adds as static import the static field or method that is selected. I use it quite often for constants or util methods etc. I think it could be nice to have in Xtend but in an improved way.

In addition to adding the static import for the selected element it will also refactor the whole file where necessary as well (and remove the unused import, which JDT doesn't do). The behavior would be extended for Xtend's extension methods.

This is a little preview of how I see it work:
![import_static](https://user-images.githubusercontent.com/6960133/54430702-55e44800-475f-11e9-8315-a5c7434d5ecf.gif)

Could be nice as a quick assist too.

If you guys think it would be a useful new feature I can continue working on it.

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/issues/2379

**Comment by Hanksha** [comment]
Is there an existing API to rewrite a `XMemberFeatureCall` to a `XFeatureCall`?

From what I understand `Stuff.doSomething('test')` is a `XMemberFeatureCall` expression and after adding the static import and changing it to `doSomething('test')` it becomes a `XFeatureCall`. I could not find a way to do that by manipulating the model itself so I tried with textual modification instead.

What I did is:
- Find the static `XMemberFeatureCall` expression from the selection
- Compute the necessary import
- Compute the region of the `memberTargetCall` + `.` or `::` to remove (get the corresponding INode and find the next sibling for `.` or `::` using the `grammarElement`)
- Apply the changes using `DocumentRewriter` within a rewrite session

Am I on the right track?

**Comment by szarnekow** [comment]
Yes, that sounds about right to me

**Comment by Hanksha** [comment]
By the way I'm having a little issue with `org.eclipse.xtext.xbase.ui.document.DocumentRewriter`. I can't access its `RewritableImportSection importSection` to add an import. I can only access the import section if I call `documentRewriter.newSection(...).importSection` and since I'm updating all occurrences of the static method in the document it is duplicating the imports.

If I create my own `RewritableImportSection` and apply it to the document it complains about overlapping changes.

**Comment by szarnekow** [comment]
When you are working on a patch, please feel free to adjust that according to your needs. The API is still provisional and we are open to recommendations.

**Comment by Hanksha** [comment]
I'm almost done with this, just need to add more tests. I'll try to PR during the week.

**Comment by cdietrich** [comment]
FIxed in 2.20

@Hanksha would you like to write a section about this in the release notes
https://github.com/eclipse/xtext/blob/website-master/xtend-website/_posts/releasenotes/2019-12-03-version-2-20-0.md (pull request against website-master branch in eclipse/xtext)

**Comment by cdietrich** [comment]
@Hanksha any news on this?

**Comment by Hanksha** [comment]
@cdietrich Yes sorry, I will find time to do it today.

**Comment by cdietrich** [comment]
Fixed in 2.20. thx again @Hanksha
