### ISSUE TITLE
Xtend class editor allows pasting text

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-xtend#753]
* Copy some random text
* Open a random class file for an xtend file such that it opens in the XtendEditor (e.g. org.eclipse.xtext.ide.server.LanguageServerImpl)
* Click somewhere in the editor
* Press Ctrl+Shift+V
* Your changes will be pasted into the read-only editor and you will end up with a dirty file

You can now save the file to get rid of the dirty state. Luckily however, it doesn't actually save the file, closing and reopening the editor brings back the original class file

**Comment by cdietrich** [comment]
@tivervac could this be related to https://github.com/eclipse/xtext/issues/2479

**Comment by tivervac** [comment]
Possibly, it could also be the implementation of Ctrl+Shift+V (Java -> Xtend) Haven't looked at the cause yet

**Comment by cdietrich** [comment]
hmmm i tried to reproduce this and could not.

**Comment by cdietrich** [comment]
can reproduce this with paste java code only

**Comment by cdietrich** [comment]
Fixed in 2.18
