### ISSUE TITLE
Importing syntax Coloring preferences is broken

### ISSUE THREAD

**Issue by tomvdbussche** [eclipse/xtext-xtend#754]
Importing xtend syntax coloring preferences does not seem to work. They can be exported, however any preferences prefixed with `/instance/org.eclipse.xtend.core.Xtend/org.eclipse.xtend.core.Xtend.syntaxColorer.tokenStyles` are not applied on import.

To reproduce the problem I do the following:

1. Set a custom color in **Preferences** > **Xtend** > **Syntax Coloring** (eg. static fields) and apply
2. Export preferences using **Export** icon in the bottom left
3. Change the modified color to another color
4. **Apply and close**, (restart eclipse), the color should be visible
5. Open preferences and **Import** the exported preference file using the icon in the bottom left
6. **Apply and close**, (restart eclipse), the color remains unchanged.

It might be worth noting I'm using the Eclipse dark theme.

**Comment by cdietrich** [comment]
@tomvdbussche how is the import and export done?

**Comment by tomvdbussche** [comment]
Using the icons on the lower left of the eclipse Preferences window. The settings are correctly exported to an *epf* file, but seems to fail on import as the settings are unchanged. When exporting again these preferences are missing. Other xtext preferences however are imported correctly.

**Comment by cdietrich** [comment]
hmmm i tried this and could not reproduce.
did you change a specific pref?
which os do you use?
did you already have a xtend file created/openend when importing
(could be that preference initializers "overrule" existing stuff https://bugs.eclipse.org/bugs/show_bug.cgi?id=449010)

**Comment by tomvdbussche** [comment]
I'm using Linux (Fedora+GTK), and this was on a clean eclipse install, however the workspace is preconfigured using oomph. Then I exporting the preferences from my previous workspace and everything was imported except those settings. After trying several times the only thing that worked was manually editing the settings in the preferences UI.

**Comment by tomvdbussche** [comment]
It might be worth noting I'm using the Eclipse dark theme.

To reproduce the problem I do the following:

1. Set a custom color in **Preferences** > **Xtend** > **Syntax Coloring** (eg. static fields) and apply
2. Export preferences using **Export** icon in the bottom left
3. Change the modified color to another color
4. **Apply and close**, (restart eclipse), the color should be visible
5. Open preferences and **Import** the exported preference file using the icon in the bottom left
6. **Apply and close**, (restart eclipse), the color remains unchanged.

**Comment by tomvdbussche** [comment]
Okay I'm stupid, I found out the preference file I was trying to include was missing some lines. Most importantly the `file_export_version=3.0` at the end of the file. Adding it fixed the issue, so I'm closing this ticket.
