### ISSUE TITLE
Make Xtend tests independent from platform encoding

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#758]
Some Xtend UI tests are failing on CJE with encoding issues:
- Subclasses of  org.eclipse.xtend.ide.tests.autoedit.AutoEditInFirstMethodTest
- org.eclipse.xtend.ide.tests.contentassist.ContentAssistTest and subclasses
- org.eclipse.xtend.ide.tests.macros.ActiveAnnotationsProcessingInIDETest
- org.eclipse.xtend.ide.tests.quickfix.QuickfixTest
- org.eclipse.xtend.ide.tests.refactoring.ExtractMethodIntegrationTest

Test failures can be raised when adding `-Dfile.encoding=US-ASCII` as JVM arg for test execution.

**Comment by kthoms** [comment]
Problem can be solved by setting the encoding with `projectFactory.setProjectDefaultCharset(StandardCharsets.ISO_8859_1.name());`

**Comment by cdietrich** [comment]
am not sure if doing this in appargline would be better ` <appArgLine>-Dfile.encoding=ISO-8859-1</appArgLine>`

**Comment by kthoms** [comment]
The test code is in ISO encoding, so the tested file content should be the same. Passing encoding for test execution would solve the issue, too, but requires to set the encoding from outside. Maybe just a matter of taste where to solve that.

**Comment by szarnekow** [comment]
I'd prefer the tests to be independent from the machines / processes default encoding. The logic should be self contained, e.g. using `projectFactory.setProjectDefaultCharset` sounds about right to me.

**Comment by kthoms** [comment]
This one is solved on branch kth_issue1309_cbi. The issue can be closed once the branch was merged.

**Comment by kthoms** [comment]
Also related #617

**Comment by kthoms** [comment]
Finally all working on CJE
