### ISSUE TITLE
NPE in ShowHierarchyTest.testOpenTypeHierarchyOnCollectionsLiterals

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#780]
Xtend build fails with a failing test on target Oxygen:

```
java.lang.NullPointerException
	at org.eclipse.xtend.ide.tests.hierarchy.ShowHierarchyTest.testOpenTypeHierarchyOnCollectionsLiterals(ShowHierarchyTest.java:80)

```

**Comment by cdietrich** [comment]
the open handler returns null.

`mvn clean install -Dtest=ShowHierarchyTest`

```
method : testOpenTypeHierarchyOnCollectionsLiterals
the jvm identifyable:
 JvmVoid:  (eProxyURI: platform:/resource/test.project/src/foo/Foo.xtend#|0)
```

**Comment by cdietrich** [comment]
JDT Type Provider cannot find 
org.eclipse.xtext.xbase.lib.CollectionLiterals

**Comment by cdietrich** [comment]
answer seems to be null for everything.
@szarnekow do you have any idea on how to analyze this?

**Comment by cdietrich** [comment]
IPackageFragment[] packages= elementRequestor.getPackageFragments();
in namelookup gives length zero

**Comment by cdietrich** [comment]
seems to happen if 
ShowHierarchyTest runs first

=> whats wrong with the project setup/builds there

**Comment by cdietrich** [comment]
![Bildschirmfoto vom 2019-04-15 18-33-56](https://user-images.githubusercontent.com/238736/56149543-16eb2180-5fad-11e9-849e-0e473285861f.png)

**Comment by cdietrich** [comment]
Fixed
