### ISSUE TITLE
Applying quick fixes from the problems view is bogus

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-xtend#79]
Applying qfs one by one breaks the source code. It seems like it does't respect dirty state so the offset is wrong.

**Comment by cdietrich** [comment]
@dhuebner problems view shows resource annotations. these are updated on build. thus i assume we should prevent applying them on dirty editors

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
