### ISSUE TITLE
Provide a way to change newline characters for template expressions

### ISSUE THREAD

**Issue by enikao** [eclipse/xtext-xtend#811]
By default, Xtend uses `System.getProperty("line.separator")` _at run-time_ to choose the newline character(s) for template expressions. This is implemented through:

* Field `String  org.eclipse.xtend2.lib.StringConcatenation.lineDelimiter`
* Set in constructor `org.eclipse.xtend2.lib.StringConcatenation.StringConcatenation(String)`
* Called by constructor `org.eclipse.xtend2.lib.StringConcatenation.StringConcatenation()`
* Using constant `String org.eclipse.xtend2.lib.StringConcatenation.DEFAULT_LINE_DELIMITER`
* Getting its s value from `org.eclipse.xtend2.lib.DefaultLineDelimiter.get()`

Even though this sophisticated structure suggests flexibility, I didn't find any way to change the newline characters besides re-setting the system property, which may have other effects (e.g. in parallel threads).

Our use-case: Generate makefiles for old Unix make versions (which do not understand CRLF) on a Windows system.

As a workaround, we're post-processing the result with  `org.eclipse.xtext.generator.LineSeparatorHarmonizer` using a custom implementation of `org.eclipse.xtext.formatting.IWhitespaceInformationProvider` to provide a custom implementation of `org.eclipse.xtext.formatting.ILineSeparatorInformation`.

**Comment by szarnekow** [comment]
The outermost StringConcatenation drives the line delimiter that is used. You can create a `new StringConcatenation(whateverYouWant)` and append you templates.

**Comment by enikao** [comment]
Thanks for the hint.

I guess this works also through method calls as long as we never convert (implicitly) to `String`?

Example:
````
class MainGenerator {
  def gen() {
    new StringConcatenation("<br/>").append(doGenerate())
  }

  def doGenerate() '''
    This is
    My Text
    <<addSomething()>>
    <<addSomethingBroken()>>
    End of Text
  '''

  def CharSequence addSomething() {
    return '''this is

    text'''
  }

  def String addSomethingBroken() '''
    This won't
    work
  '''
}
````

**Comment by szarnekow** [comment]
Exactly.

**Comment by enikao** [comment]
Actually, it does:

````
import org.eclipse.xtend2.lib.StringConcatenation

class CustomNewline {
	static def void main(String[] args) {
		val result = new StringConcatenation("<br/>\r\n")
		
		result.append(doGenerate())
		
		println(result)
	}

	static def doGenerate() '''
		This is
		My Text
		«addSomething»
		«addSomethingBroken»
		End of Text
	'''

	static def CharSequence addSomething() {
		return '''
			this is
			
			text
		'''
	}

	static def String addSomethingBroken() '''
		This won't
		work
	'''
}
````
leads to
````
This is<br/>
My Text<br/>
this is<br/>
<br/>
text<br/>
This won't<br/>
work<br/>
End of Text<br/>

````

**Comment by szarnekow** [comment]
Yes, but only for newlines. If the method `addSomethingBroken` would use `<br/>`, the information would be duplicated in the final result

**Comment by cdietrich** [comment]
@szarnekow should we close this or is there anything todo?

**Comment by szarnekow** [comment]
I don't think this'll work since the compilation of template expression must remain independent from any injection magic or global state.

**Comment by szarnekow** [comment]
The best solution is still to tailor the eventual call to `toString` on the template expression to your needs, e.g. assuming you are writing the string into a file or into a stream, instead of doing `writer.write(myTemplate.toString())`, you'd do something of the shape
```
  StringConcatenation withUnixLineEndings = new StringConcatenation("\n");
  withUnixLineEndings.append(myTemplate);
  writer.write(withUnixLineEndings.toString());
```

**Comment by kjuenemann** [comment]
I know the workaround and I am using it (got a helper function `useUnixLineEndings()` ), but it feels a bit wrong that the whole team has to remember using it on every occasion. More so that the issue sometimes is not found in tests until you create merge to trunk. It is also a bit confusing for the team to see such errors pop up when our git repository is configured to use only \n lineendings.

How would you deal with these issues?

Maybe a solution would be to (optionally) use a custom environment variable, which is used by xtend only? I would be more willing to set up a new variable than changing `System.lineSeparator`, although maybe there are better ways.

I just thought it might be a good idea to bring up this topic again. But you guys probably thought it all through already.
