### ISSUE TITLE
Preferences for Errors/Warnings and local fields not working

### ISSUE THREAD

**Issue by UdoW** [eclipse/xtext-xtend#816]
I have a Xtend project where I have classes with active annotations which look like this:

```
class A{
   int number;
}
```
The default project settings for compiler errors and warning shows me this error:

The value of the field A.number is not used

I want to get rid of the warning by changing the project preferences. In the Xtend section I changed the preference "Value of local variable is not used" to Ignore.

(See attached screenshot)

But still the Xtend editor shows me the same warning.

Do I use the wrong preference or is the preference setting ignored by the editor?

**Comment by UdoW** [comment]
![image](https://user-images.githubusercontent.com/12225215/57910900-a4f54900-7886-11e9-8aee-ff1991fc7491.png)

**Comment by cdietrich** [comment]
hmm that is not a variable. that is a field

![Bildschirmfoto vom 2019-05-17 09-36-07](https://user-images.githubusercontent.com/238736/57911164-4aa8b800-7887-11e9-9380-0b94d55de20f.png)

**Comment by UdoW** [comment]
I change this preference setting, too but still the warning.

**Comment by UdoW** [comment]
Ahh, it is the setting you mentioned but the Xtend editor needs an update/refresh of the source code to change the markers.

**Comment by cdietrich** [comment]
Also: if the active annotation uses the field it should be tracked as used. so i wonder what you do in your aa.

**Comment by UdoW** [comment]
I do this by "primarySourceElement = field" right?

**Comment by cdietrich** [comment]
i assume so

**Comment by UdoW** [comment]
You can close the issue as it works now.

**Comment by cdietrich** [comment]
@UdoW created https://github.com/eclipse/xtext/issues/2476 for editor missbehaviour
