### ISSUE TITLE
Enhanced view in Package Explorer under Eclipse

### ISSUE THREAD

**Issue by tJeyhun** [eclipse/xtext-xtend#856]
One can see structure of Java files under Eclipse Project Explorer. Structure, fields and methods. But xtend file still need to be opened to see what is inside :)  We should see fields and methods and their visibility under Project Explorer.

**Comment by Hanksha** [comment]
I was thinking if it would it possible to reuse the one provided by JDT since we can map the xtend file to its generated java file.

**Comment by kthoms** [comment]
> I was thinking if it would it possible to reuse the one provided by JDT since we can map the xtend file to its generated java file.

This has to be examined. Likely this would be in internal JDT API, and we strongly discourage using internal API. In the past we had some situations where internal things broke our code. Unfortunately we had to use internal API at some places. That's not a problem of JDT, it is valid to refactor API that is internal.

But maybe you could have a look and come up with a solution proposal?

**Comment by Hanksha** [comment]
A part of it is public API like `org.eclipse.jdt.ui.StandardJavaElementContentProvider` which is subclassed by `org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider` and `org.eclipse.jdt.internal.ui.navigator.JavaNavigatorContentProvider`. But then we'd have to handle the logic when the element is double clicked to open and select it in the editor.

Another alternative would be to use the Xtend content and label providers of the outline view. Retrieve the AST model for the file and then delegate to them

**Comment by kthoms** [comment]
From reading `StandardJavaElementContentProvider` and `PackageExplorerContentProvider` I don't have a good feeling that these classes are the right way to solve this for Xtend.

I think it could be easier to follow the second path, i.e. reusing tha content / label providers and provide a `org.eclipse.ui.navigator.navigatorContent` extension.

**Comment by Hanksha** [comment]
That's what I thought as well.

**Comment by kthoms** [comment]
Could you try to provide a PR for it? Please consider that performance might be a thing to consider. It should be avoided that content tree extension has impact on UI responsiveness. I think the framework does already a good job on this, but just take this into mind and test with larger data.

**Comment by cdietrich** [comment]
i also wonder if there should be a preference to opt in/out (performance concerns)

**Comment by Hanksha** [comment]
Technically it won't have any impact until the user expands the node, from what I know the common navigator API doesn't get the children of a tree element until it is expanded.
If we want to prevent the UI freezing when it parses a big file we could put it in a background job and update the parent element once it is ready.

**Comment by szarnekow** [comment]
It's crucial that we do not do any heavy processing on the display thread. 
If by all means possible, parsing should be completely avoided and we should resort to mere index accesses.

**Comment by miklossy** [comment]
**Hint:** If the project has the` org.eclipse.sirius.nature.modelingproject` configured, the structure is already shown in the Project Explorer. Maybe it worth looking at their solution to get some inspiration.
![screenshot](https://user-images.githubusercontent.com/20393472/63933037-c0ace580-ca58-11e9-830f-ba99aa1c80c8.png)

**Comment by Hanksha** [comment]
@szarnekow If the methods and classes are already indexed it would be better indeed. Do you have any pointers on how to access the index for Xtend files?

**Comment by szarnekow** [comment]
Starting with an injected `@Inject IBuilderState` may be a worthwhile way to explore things. It should offer to query for an `IResourceDescription` by URI and the description in turn has `IEObjectDescriptions` - at least for Xtend these should allow to be visualized.

**Comment by Hanksha** [comment]
Great, I'll look into that, thanks.

**Comment by Hanksha** [comment]
@szarnekow I managed to setup a content provider and inject `IBuilderState`, then call `builderState.getResourceDescription(fileUri)` which returns one `IEObjectDescription` for each class in the file. From there I don't know how to get the declared constructors, fields and methods, how do I do that?

**Comment by kthoms** [comment]
@Hanksha sorry for coming back late. @szarnekow is on vacation for some weeks ATM.

That's actually a good question. From what I see in [`XtendResourceDescriptionStrategy`](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.core/src/org/eclipse/xtend/core/resource/XtendResourceDescriptionStrategy.java)  `IEObjectDescription` are created only for `JvmType`s, not for internals. I have not proof yet, but I think some code in `XtendResourceDescriptionStrategy` is actually dead code. When no `IEObjectDescription` is created for operations, fields etc., also user data won't be created.

This makes me think that you'd actually have to resolve the JvmType and explore its features once you need to show children.

**Comment by Hanksha** [comment]
@kthoms Thanks for the hints, I'll look into that.

**Comment by Hanksha** [comment]
I didn't progress much with that, @szarnekow any other idea?

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
