### ISSUE TITLE
Failing Ant tests

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-xtend#87]
* XtendCompilerAntTaskTest.testSrcdirAsAttr
* XtendCompilerAntTaskTest.testSrcdirAsNestedPath

fail after restructuring made for eclipse/xtext#1085.

**Comment by cdietrich** [comment]
@spoenemann what was the content of this change? eclipse/xtext#1085.

**Comment by cdietrich** [comment]
/Users/dietrich/xtext-dev/git/xtext-xtend/org.eclipse.xtend.core.tests/batch-compiler-data/ant/test.ant:84: Sources directory 'srcdir' is required.

**Comment by cdietrich** [comment]
mvn dependency:tree gives

[INFO] +- p2.eclipse-feature:org.eclipse.emf.ecore:jar:2.10.2.v20150123-0348:system
[INFO] +- p2.eclipse-plugin:org.eclipse.emf.ecore:jar:2.10.2.v20150123-0348:system

both will result in same jar name

**Comment by cdietrich** [comment]
@spoenemann a

```
<excludeGroupIds>p2.eclipse-feature</excludeGroupIds>
```

should do the trick

**Comment by cdietrich** [comment]
fix pushed to @spoenemann s branch
