### ISSUE TITLE
Add 'contains' method to Array-, Iterable-, and IteratorExtensions

### ISSUE THREAD

**Issue by teenriot** [eclipse/xtext-xtend#877]
Please add 'contains' method to ArrayExtensions and IterableExtensions.

I guess you already thought about and declined it, but i found no information about so i opened this ticket.

(I'm sorry for misleading title with 'List')

**Comment by riederm** [comment]
I created a pull request here: https://github.com/eclipse/xtext-lib/pull/229

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
