### ISSUE TITLE
Annotations marked as valid for "type use" cannot be used anywhere

### ISSUE THREAD

**Issue by ivaniesta14** [eclipse/xtext-xtend#908]
The following code does not compile¹:
```xtend
def @Nullable String getArg(@Nullable String arg){ arg }
```
Both annotation uses are tagged as invalid (`The annotation @Nullable is disallowed for this location`)
This also happens with fields and (local) variables.

---
¹ Using `org.eclipse.jdt.annotation.Nullable`, which is defined with `@Target({TYPE_USE})` as per source.

**Comment by cdietrich** [comment]
Duplicates https://github.com/eclipse/xtext/issues/2360
