### ISSUE TITLE
Implement Quickfix 'Add JUnit library to the buildpath/classpath'

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#919]
**JDT** offers a quickfix if in a Java Project the `org.junit.Test` is imported but the junit library is not found on the buildpath/classpath:
![screenshot](https://user-images.githubusercontent.com/20393472/64622821-35343c80-d3e8-11e9-978e-c67da174b73b.png)

The Xtend IDE should also offer a similar quickfix:
![screenshot2](https://user-images.githubusercontent.com/20393472/64622883-4bda9380-d3e8-11e9-94c7-d16311c7fbe3.png)

**Hint:** The Xtend IDE already offers a [quickfix](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java#L638) to add the Xbase lib to the classpath, a quickfix for adding the JUnit library could be implemented similarly.

**Comment by Hanksha** [comment]
@miklossy What version of JDT are you using to get that quick fix? I tried with the 2019-09 release and I could not get it, maybe my setup is missing something

**Comment by Hanksha** [comment]
JDT quick fix can add it both to the `.classpath` and the `META-INF/MANIFEST.MF`. 
![image](https://user-images.githubusercontent.com/6960133/67827616-7d7bfb00-fb0b-11e9-89e1-5462bf4dbe90.png)

For the latter should we use PDE to help with that (I'm guessing it's the PDE plugin that proposes that quick fix)? I noticed the `org.eclipse.xtend.ide` plugin doesn't have any dependency to PDE.

**Comment by miklossy** [comment]
@Hanksha I would not use PDE here, but implement the Quickfix analog to the [XtendLibClasspathAdder](https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/XtendLibClasspathAdder.java). It already supports adding the missing library both to the classpath and to the MANIFEST.MF file.

**Comment by Hanksha** [comment]
@miklossy Ok thanks I'll take a look at that.

**Comment by Hanksha** [comment]
I've got a quick fix working for adding junit 4 or 5 to the classpath.
![add_junit4](https://user-images.githubusercontent.com/6960133/69214734-a9d2e680-0ba2-11ea-9a55-aa45516d8d69.gif)
![add_junit5](https://user-images.githubusercontent.com/6960133/69214739-accdd700-0ba2-11ea-8f25-f3d81caebb9f.gif)

Is that enough or should we stick with the way JDT does with an extra dialog for it?
Also should the quick fix be shown only if JUnit plugin is present on the target platform? If so what's the best way to determine that?

**Comment by miklossy** [comment]
Nice. Could you create a PR?

**Comment by Hanksha** [comment]
Yes I will.

**Comment by szarnekow** [comment]
> Is that enough or should we stick with the way JDT does with an extra dialog for it?

No, we do not need a dialog.

> only if JUnit plugin is present on the target platform

You can probably use `org.eclipse.jdt.core.search.SearchEngine.searchAllTypeNames(char[], int, char[], int, int, IJavaSearchScope, TypeNameRequestor, int, IProgressMonitor)` with the JavaModel as of `org.eclipse.jdt.core.IJavaModel` as the search scope.

**Comment by Hanksha** [comment]
@szarnekow Wouldn't that be a too expensive operation to do in the quick fix provider? I was thinking I could check if the junit bundles are installed.

**Comment by szarnekow** [comment]
> @szarnekow Wouldn't that be a too expensive operation to do in the quick fix provider? I was thinking I could check if the junit bundles are installed.

Installed bundles are not necessarily the bundles from the target platform. If there is an efficient way to query that one, that would be perfect.

**Comment by cdietrich** [comment]
Fixed in 2.20

the target platform check (if possible) can be done later
