### ISSUE TITLE
Fix xtend-archetype integration test

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-xtend#92]
The changes done in #93 caused the xtend-archetype integration test to fail. It's probably related to the fact that xtend.core is no longer built in the same build.

The integration test is currently disabled with the option `-Dit-tests-skip=true` in the Jenkinsfile.

On the other hand, #18 seems to work again.

**Comment by cdietrich** [comment]
@spoenemann do both builds still use the same local maven repo?

**Comment by cdietrich** [comment]
it seems you did not adapt code like this one String localRepo = new File("../local-maven-repository/").getAbsolutePath();

**Comment by cdietrich** [comment]
additionally the gradle stuff is put to different repo
