### ISSUE TITLE
[compiler] Suppress unnecessary modifiers in interfaces

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#942]
```
interface FooItf {
	def void bar ()

       static class FooItfImpl implements FooItf {}
}
```

compiles to 
```
public interface FooItf {
  public abstract void bar();

  public static class FooItfImpl implements FooItf {}
}
```

In interfaces it the modifiers `public abstract` for methods are obsolete, the compiler should not write them.

For the inner class, the modifiers `public static` are obsolete.

**Comment by tivervac** [comment]
@kthoms AFAIK, removing the `static` on those inner classes is a non backwards compatible change.

**Comment by kthoms** [comment]
@tivervac As you can see from the outline the inner class has the static decorator. So leaving out `static` should be equivalent.

![screenshot 375](https://user-images.githubusercontent.com/265597/70981836-3abfb380-20b6-11ea-8114-502d2510e04e.png)

https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.1.3 :

> A member class of an interface is implicitly static (§9.5) so is never considered to be an inner class.

**Comment by tivervac** [comment]
Right, I forgot we were talking about interfaces

**Comment by kthoms** [comment]
TODO: Add release notes entry

**Comment by kthoms** [comment]
Documentation was added.

**Comment by szarnekow** [comment]
There is still room for improvements, e.g. we don't need `final` for parameters in interfaces and in abstract methods. Fields in interfaces are always `static final` - that can be improved, too.
Should we do this as part of this ticket?

**Comment by cdietrich** [comment]
@kthoms what about @szarnekow question
