### ISSUE TITLE
Create methods should have an accompanying existance check method

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/xtext-xtend#947]
Assume there is a create method called 'node(Object...)' that is used on multiple occurrences to create a new node in a graph or get the existing one generated by an earlier call. Now I want to just see if a node for some parameters has been created already without creating it at the same time by calling the create method again. As far as I can see this behavior can only be achieved by looking at the internal cached HashMap via reflection or caching the values manually, not using the create method at all.

I suggest that for every create method there should be an accompanying method to check if a value has already been created or not.
In the example the generated code for that method could look something like this:
```
boolean nodeExists(Object... os) {
    final ArrayList<?> _cacheKey = Lists.newArrayList(os);
    return _createCache_node.get(_cacheKey) != null;
}
```

**Comment by szarnekow** [comment]
You can already access the field without reflection:
```
class CreateCacheAccess {
	def create left + right concat(String left, String right) {
	}
	
	def boolean isCached(String left, String right) {
		// content assist after the leading underscore will reveal the field
		this._createCache_concat.containsKey(newArrayList(left, right))
	}
}
```

**Comment by NiklasRentzCAU** [comment]
This is exactly what I overlooked and needed. Thanks!
