### ISSUE TITLE
[maven] sporadic compilation errors

### ISSUE THREAD

**Issue by knutwannheden** [eclipse/xtext-xtend#963]
I am using the 2.18.0 Xtend Maven plugin and every once in a while our CI system reports build errors when compiling the Java code produced by Xtend. For example:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jOOQ-tools: Compilation failure: Compilation failure: 
[ERROR] /var/lib/jenkins/workspace/jooq-release-all_master/workspace/jOOQ-pro/jOOQ-tools/target/xtend-gen/main/org/jooq/xtend/Rows.java:[7810,4] error: not a statement
[ERROR] /var/lib/jenkins/workspace/jooq-release-all_master/workspace/jOOQ-pro/jOOQ-tools/target/xtend-gen/main/org/jooq/xtend/Rows.java:[7810,8] error: reached end of file while parsing
```

The error is not always reported against the same Xtend-generated Java class, but the Java source in question is always generated by Xtend. Also, when I look at the Java source after the fact, it looks perfectly fine, which is also very weird.

Has anyone else seen a similar thing happen?

**Comment by knutwannheden** [comment]
Here is another one I found in another build log today:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project jOOQ-tools: Compilation failure: Compilation failure: 
[ERROR] /var/lib/jenkins/workspace/_build-all_version-3.12.0-branch/workspace/jOOQ-pro/jOOQ-tools/target/xtend-gen/main/org/jooq/xtend/Constraint.java:[592,25] unclosed string literal
[ERROR] /var/lib/jenkins/workspace/_build-all_version-3.12.0-branch/workspace/jOOQ-pro/jOOQ-tools/target/xtend-gen/main/org/jooq/xtend/Constraint.java:[592,51] reached end of file while parsing
```

**Comment by cdietrich** [comment]
No I have never seen such a thing

**Comment by szarnekow** [comment]
Any chance that you can attach one of the broken generated files here?

**Comment by knutwannheden** [comment]
> Any chance that you can attach one of the broken generated files here?

The weird thing is that when I open the files afterwards they don't look weird at all, so I am really confused about what is going on.

**Comment by cdietrich** [comment]
>  when I open the files afterwards they don't look weird at all
thus is wonder if you run something in parallel that should not

**Comment by szarnekow** [comment]
Does it fail during stub generation or for the final generation step?

**Comment by cdietrich** [comment]
To me this looks like after the final generation (java compile by maven)

**Comment by knutwannheden** [comment]
Yes, it is the Java compiler which fails. Something running in parallel is also the only thing I could think of, but I can't see where this would be the case.

Anyway, since nobody else has seen this before, I will close the issue for now and assume it is a problem on my end. If I find something to the contrary, I will comment here.

Thanks for the feedback!

**Comment by knutwannheden** [comment]
It was indeed a problem on my side with concurrent builds, which weren't supposed to run in the same workspace :unamused: 

I am however still slightly surprised that `javac` was able to read a partially written file. But fixing that is hardly worth the effort.
