### ISSUE TITLE
Using JUnit's Assert.assertEquals leads to performance issues

### ISSUE THREAD

**Issue by lsotnk** [eclipse/xtext-xtend#983]
[assertproblem.zip](https://github.com/eclipse/xtext-xtend/files/4019257/assertproblem.zip)
Hi,

we've encountered some performance issues writing tests with Xtend.

There are two xtend-files in the attached project:
- assertproblem.Test1
- assertproblem.Test2
The only difference between the two files is the import declaration:
- Test1 imports Assert1.*
- Test2 imports Assert2.*

Assert1 is basically a partial copy of JUnit's Assert class.

On my computer it takes about 20 seconds to build Test1 and 4 seconds to build Test2. I've used Xtext Build Console to stop the time:

[Worker-99: Building workspace] Building assertproblem
[Worker-99: Building workspace] indexing platform:/resource/assertproblem/src/assertproblem/Test1.xtend
[Worker-99: Building workspace] Build assertproblem in 23735 ms
[Worker-99: Building workspace] Building assertproblem
[Worker-99: Building workspace] Build assertproblem in 1 ms
[Worker-118: Building workspace] Building assertproblem
[Worker-118: Building workspace] indexing platform:/resource/assertproblem/src/assertproblem/Test2.xtend
[Worker-118: Building workspace] Build assertproblem in 4758 ms
[Worker-118: Building workspace] Building assertproblem
[Worker-118: Building workspace] Build assertproblem in 0 ms

**Comment by cdietrich** [comment]
can you please provide a yourkit snapshot or a jvisualvm snapshot
and or a reproducing example.
also make sure no antivirus activity is involved in your measurements.

**Comment by lsotnk** [comment]
Hi. I've attached a project in the original post. Is the problem not reproducible for you with the provided project?

**Comment by cdietrich** [comment]
i can confirm the terrible build times.

[org.eclipse.equinox.launcher_1.5.600.v20191014-2022-2020-01-11.snapshot.txt](https://github.com/eclipse/xtext-xtend/files/4049103/org.eclipse.equinox.launcher_1.5.600.v20191014-2022-2020-01-11.snapshot.txt)

**Comment by cdietrich** [comment]
@szarnekow overload problem?

**Comment by szarnekow** [comment]
I’ll try to look into it next week. Overload resolution sounds like a possible (and likely) cause indeed.

**Comment by szarnekow** [comment]
The problem are not the overloads of the assertEquals methods, but the binary operations. These are heavily overloaded in the lib and all permutations need to be tried.

If I extract the expressions, that are passed as `actual` into local vars
```
actual = DFH....
assertEquals("foo",
						actual, "")
```
the compile time drops significantly from 15 seconds to 5 seconds.
When I remove all the binary operations and use a literal (`1`) instead, the project compiles in less than half a second.
Ideas how to improve the computational complexity, but improvements there require quite some time, I'm afraid.

**Comment by cdietrich** [comment]
i assume this to be enhanced by the 2.30 overload enhancements
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
