### ISSUE TITLE
Overload elvis/ safe navigation to work with getters

### ISSUE THREAD

**Issue by stevehickman** [eclipse/xtext-xtend#993]
XTend makes getters/setters invisible by stripping off the 'get'/'set' prefix and removing the trailing '()'. This is great/ consistent with information hiding. However, the '?.' operator appears to only work on actual features - it does not appear to work on getters, even though they look syntactically the same.

Further, attempting to use '?.' using 'getXXX()' does not work either.

Can the '?.' operator be extended to work with getters - since this is a very common use case?

**Comment by cdietrich** [comment]
Hi, i cannot follow you

```
	def demo() {
		a?.b?.c
		getA()?.getB()?.getC()
	}
```

```
public String demo() {
    String _xblockexpression = null;
    {
      B _b = null;
      if (this.a!=null) {
        _b=this.a.getB();
      }
      if (_b!=null) {
        _b.getC();
      }
      A _a = this.getA();
      B _b_1 = null;
      if (_a!=null) {
        _b_1=_a.getB();
      }
      String _c = null;
      if (_b_1!=null) {
        _c=_b_1.getC();
      }
      _xblockexpression = _c;
    }
    return _xblockexpression;
```

=> can you please provide a complete usecase where its not working?

**Comment by cdietrich** [comment]
from the docs
> myObj.myProperty // myObj.getMyProperty()  (.. in case myObj.myProperty is not visible.)

**Comment by stevehickman** [comment]
It will take me a a little time to strip the example down to the minimum. While I'm doing that, I'll refer to the generated Java to see at if I can detect what is happening.

**Comment by stevehickman** [comment]
Ahh... I see my error now.  It looks like the code generation is fine. My error was that I had things like this:
`	return (it as Entity).realizes?.realizes?.fullyQualifiedName.toString
`
when I should have this:
`	return (it as Entity).realizes?.realizes?.fullyQualifiedName?.toString
`
I had not addressed the problem that a null pointer early in the chain forces me to check for null pointers later on. I mistakenly assumed that the code would return as soon as it found a null pointer. Thanks for reminding me to look at the generated code.

**Comment by szarnekow** [comment]
FYI: It is not generally possible mark all subsequent calls as nullsafe since especially extension methods can be used to work with receivers that are null, e.g.
```return (it as Entity).realizes?.realizes?.fullyQualifiedName?.toString.isNullOrEmpty`
